### ISSUE TITLE
Key android.intent.extra.TEXT expected ArrayList<CharSequence> but value was a java.lang.String.  The default value <null> was returned.

### ISSUE THREAD

**Issue by bholendraofficial** [ACRA/acra#1005]
**Code**
```
CoreConfigurationBuilder builder = new CoreConfigurationBuilder(this);
        //core configuration:
        builder.withBuildConfigClass(BuildConfig.class)
                .withReportFormat(StringFormat.JSON)
                .withEnabled(true);

        builder.getPluginConfigurationBuilder(NotificationConfigurationBuilder.class)
                //required
                .withEnabled(true)
                //required
                .withResTitle(R.string.app_name)
                //required
                .withResText(R.string.app_name)
                //required
                .withResChannelName(R.string.app_name)
                //optional channel description
                .withResChannelDescription(R.string.app_name)
                //defaults to NotificationManager.IMPORTANCE_HIGH
                .withResChannelImportance(NotificationManager.IMPORTANCE_MAX)
                //optional, enables ticker text
                .withResTickerText(R.string.app_name)
                //defaults to android.R.drawable.stat_sys_warning
                .withResIcon(android.R.drawable.stat_sys_warning)
                //defaults to android.R.string.ok
                .withResSendButtonText(android.R.string.ok)
                //defaults to android.R.drawable.ic_menu_send
                .withResSendButtonIcon(android.R.drawable.ic_menu_send)
                //defaults to android.R.string.cancel
                .withResDiscardButtonText(android.R.string.cancel)
                //defaults to android.R.drawable.ic_menu_delete
                .withResDiscardButtonIcon(android.R.drawable.ic_menu_delete)
                //optional, enables inline comment button
                .withResSendWithCommentButtonText(R.string.notification_send_with_comment)
                //required if above is set
                .withResSendWithCommentButtonIcon(R.drawable.ic_baseline_send_24)
                //defaults to false
                .withSendOnClick(false);

        builder.getPluginConfigurationBuilder(MailSenderConfigurationBuilder.class)
                //required
                .withMailTo("bholendraofficial@gmail.com")
                //defaults to true
                .withReportAsFile(true)
                //defaults to ACRA-report.stacktrace
                .withReportFileName("Crash.json")
                //defaults to "<applicationId> Crash Report"
                .withSubject(getString(R.string.app_name)).withEnabled(true);

        ACRA.init(this, builder);
        ACRA.isACRASenderServiceProcess();

```
**Crash**
```
W/Bundle: Key android.intent.extra.TEXT expected ArrayList<CharSequence> but value was a java.lang.String.  The default value <null> was returned.
W/Bundle: Attempt to cast generated internal exception:
    java.lang.ClassCastException: java.lang.String cannot be cast to java.util.ArrayList
        at android.os.BaseBundle.getCharSequenceArrayList(BaseBundle.java:1343)
        at android.os.Bundle.getCharSequenceArrayList(Bundle.java:1146)
        at android.content.Intent.getCharSequenceArrayListExtra(Intent.java:9268)
        at android.content.Intent.migrateExtraStreamToClipData(Intent.java:12327)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1741)
        at android.app.ContextImpl.startActivity(ContextImpl.java:1135)
        at android.app.ContextImpl.startActivity(ContextImpl.java:1106)
        at android.content.ContextWrapper.startActivity(ContextWrapper.java:420)
        at org.acra.sender.EmailIntentSender.sendWithSelector(EmailIntentSender.kt:119)
        at org.acra.sender.EmailIntentSender.send(EmailIntentSender.kt:67)
        at org.acra.sender.ReportSender.send(ReportSender.kt:59)
        at org.acra.sender.ReportDistributor.sendCrashReport(ReportDistributor.kt:96)
        at org.acra.sender.ReportDistributor.distribute(ReportDistributor.kt:60)
        at org.acra.sender.SendingConductor.sendReports(SendingConductor.kt:50)
        at org.acra.scheduler.DefaultSenderScheduler.scheduleReportSending(DefaultSenderScheduler.kt:61)
        at org.acra.scheduler.SchedulerStarter.scheduleReports(SchedulerStarter.kt:49)
        at org.acra.builder.ReportExecutor.sendReport(ReportExecutor.kt:197)
        at org.acra.builder.ReportExecutor.execute(ReportExecutor.kt:135)
        at org.acra.builder.ReportBuilder.build(ReportBuilder.kt:151)
        at org.acra.reporter.ErrorReporterImpl.uncaughtException(ErrorReporterImpl.kt:105)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
        at java.lang.Thread.dispatchUncaughtException(Thread.java:2200)
```

**Comment by F43nd1r** [comment]
Your log lines start with `W`, meaning they are warnings, not errors. The stacktrace shown is known and can be safely ignored, as mail clients actually do expect a `String` in this field despite the message.
