### ISSUE TITLE
ACRA crashes on release builds with R8/ProGuard shrinking

### ISSUE THREAD

**Issue by czlucius** [ACRA/acra#1006]
**Required reading**
https://github.com/ACRA/acra/wiki/How-to-debug-ACRA

**Describe the bug**
With R8/Proguard, ACRA causes the app to crash on startup, specifically when creating the `MailSenderConfiguration`. 

I have tried adding the classes to my proguard keep files, as per

- https://github.com/ACRA/acra/wiki/ProGuard
- https://stackoverflow.com/questions/25776116/android-acra-and-proguard

ACRA (mail) still seems to crash.

Here's the crash log, `e.e.c.f` is .`kotlin.jvm.internal.DefaultConstructorMarker`
```
2022-02-22 13:26:34.886 26819-26819/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.czlucius.scan, PID: 26819
    java.lang.RuntimeException: Unable to create application com.czlucius.scan.App: java.lang.NoSuchMethodException: org.acra.config.MailSenderConfiguration.<init> [boolean, class java.lang.String, boolean, class java.lang.String, class java.lang.String, class java.lang.String, int, class e.e.c.f]
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7487)
        at android.app.ActivityThread.access$1700(ActivityThread.java:310)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2283)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8641)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
     Caused by: java.lang.NoSuchMethodException: org.acra.config.MailSenderConfiguration.<init> [boolean, class java.lang.String, boolean, class java.lang.String, class java.lang.String, class java.lang.String, int, class e.e.c.f]
        at java.lang.Class.getConstructor0(Class.java:2363)
        at java.lang.Class.getConstructor(Class.java:1759)
        at com.czlucius.scan.App.onCreate(App.java:72)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1211)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7482)
        at android.app.ActivityThread.access$1700(ActivityThread.java:310) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2283) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:226) 
        at android.os.Looper.loop(Looper.java:313) 
        at android.app.ActivityThread.main(ActivityThread.java:8641) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133) 
```
**Expected behavior**
App does not crash.
**Version**
 - Android: 12
 - ACRA 5.9.0-rc2 (mail)

Thanks

**Comment by czlucius** [comment]
This crash does not happen on debug builds where shrinking is disabled.

**Comment by czlucius** [comment]
In case you need the actual code, my code is open-source under AGPLv3, you can obtain it here:
https://github
com/czlucius/code-scanner

Thanks

**Comment by czlucius** [comment]
I fixed this by adding
```
-keep class org.acra.config.** {*;}
```
