### ISSUE TITLE
New process started by ACRA causes Firebase Crashlytics to crash with IllegalStateException

### ISSUE THREAD

**Issue by tciolkowskiN7** [ACRA/acra#1096]
**Describe the bug**

I'm using both ACRA and Firebase Crashlytics. When ACRA starts a new process, Android creates a new instance of Application class (MyApplication in the example) and onCreate() method of that class is called in ACRA process. 

```
package com.example.testapp;

import com.google.firebase.crashlytics.FirebaseCrashlytics;

public class MyApplication extends Application {

    @Override
    public void onCreate() {
        super.onCreate();

        FirebaseCrashlytics instance = FirebaseCrashlytics.getInstance();
        // ... use instance
    }
}
```

In the onCreate() method I reference FirebaseCrashlytics which causes the following exception (and a crash):

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.testapp:acra, PID: 29336
    java.lang.RuntimeException: Unable to create application com.example.testapp.MyApplication: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.example.testapp:acra. Make sure to call FirebaseApp.initializeApp(Context) first.
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5911)
        at android.app.ActivityThread.access$1100(ActivityThread.java:200)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1660)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6762)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.example.testapp:acra. Make sure to call FirebaseApp.initializeApp(Context) first.
        at com.google.firebase.FirebaseApp.getInstance(FirebaseApp.java:184)
        at com.google.firebase.crashlytics.FirebaseCrashlytics.getInstance(FirebaseCrashlytics.java:183)
        at com.example.testapp.MyApplication.onCreate(MyApplication.java:18)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1155)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5906)
        at android.app.ActivityThread.access$1100(ActivityThread.java:200) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1660) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6762) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
```

The exception message suggests to call FirebaseApp.initializeApp(Context) but the official docs of Firebase do not mention the need to call this and this comment suggests that FirebaseSDKs don't support multiple processes: https://stackoverflow.com/a/47764648

1. Is it possible to configure ACRA so that it doesn't start a new process?
2. Assuming that I need to reference FirebaseCrashlytics in onCreate() method, can you suggest any other way to avoid the crash?
3. Is it a good approach to check ACRA.isACRASenderServiceProcess() in onCreate() method and if it returns true to just return or don't reference FirebaseCrashlytics?

**Expected behavior**
FirebaseCrashlytics not crashing in the process started by ACRA.

**Version**
 - Android: 9
 - ACRA 5.7.0

**Comment by F43nd1r** [comment]
1. No, this is central to ACRAs architecture.
2. Answered by 3
3. Yes, this is the recommended way as also mentioned in the docs

**Comment by mikehardy** [comment]
Interesting! I work on crashlytics a lot as well, and separately an app that will crash in the ACRA sender process as well. Using item 3 as you mention works really well in all cases and is expected in crash-reporting design like ACRA.

Amusingly, to me, ACRA is able to send reports immediately because of this design - you do not have to restart the app - whereas crashlytics on android will not send the report until you restart the app. Why? ACRA has this architecture with a separate process while crashlytics is in process. Each approach has tradeoffs but ACRAs is pretty neat, with the exception of maybe needing these workarounds - probably why crashlytics didn't do it
