### ISSUE TITLE
Not working send e-mail with GMail on Android 13

### ISSUE THREAD

**Issue by henrichg** [ACRA/acra#1118]
Pixel 6, Android 13, Build number: T1B3.221003.003.
ACRA version: 5.9.6

Gmail is installed and working good. Autosync is enabled for GMail. But not working send e-mail from crash notification.

ACRA configuration in Application.attachBaseContext():

```
        CoreConfigurationBuilder builder = new CoreConfigurationBuilder()
                .withBuildConfigClass(BuildConfig.class)
                .withReportFormat(StringFormat.KEY_VALUE_LIST)
                .withAdditionalSharedPreferences(Arrays.asList(APPLICATION_PREFS_NAME));

        builder.withPluginConfigurations(
                new NotificationConfigurationBuilder()
                        .withChannelName(getString(R.string.notification_channel_crash_report))
                        .withChannelImportance(NotificationManager.IMPORTANCE_HIGH)
                        .withResIcon(R.drawable.ic_exclamation_notify)
                        .withTitle(getString(R.string.acra_notification_title))
                        .withText(getString(R.string.acra_notification_text))
                        .withResSendButtonIcon(0)
                        .withResDiscardButtonIcon(0)
                        .withSendOnClick(true)
                        .withEnabled(true)
                        .build(),
                new MailSenderConfigurationBuilder()
                        .withMailTo("henrich.gron@gmail.com")
                        .withSubject("PhoneProfilesPlus" + packageVersion + " - " + getString(R.string.acra_email_subject_text))
                        .withBody(body)
                        .withReportAsFile(true)
                        .withReportFileName("crash_report.txt")
                        .withEnabled(true)
                        .build()
        );

```
Crash log generated after application start:

```
16:40:22.646 ACRA                                 E  Failed to send crash reports for /data/user/0/sk.henrichg.phoneprofilesplus/app_ACRA-approved/2022-10-07T17:01:51.976+02:00.stacktrace
                                                     org.acra.sender.ReportSenderException: Policy marked this task as incomplete. ACRA will try to send this report again.
                                                     	at org.acra.sender.ReportDistributor.sendCrashReport(ReportDistributor.kt:109)
                                                     	at org.acra.sender.ReportDistributor.distribute(ReportDistributor.kt:65)
                                                     	at org.acra.sender.SendingConductor.sendReports(SendingConductor.kt:50)
                                                     	at org.acra.scheduler.DefaultSenderScheduler.scheduleReportSending(DefaultSenderScheduler.kt:61)
                                                     	at org.acra.scheduler.SchedulerStarter.scheduleReports(SchedulerStarter.kt:49)
                                                     	at org.acra.startup.StartupProcessorExecutor.processReports$lambda-5$lambda-4(StartupProcessorExecutor.kt:60)
                                                     	at org.acra.startup.StartupProcessorExecutor.$r8$lambda$o2NE53IEwtcT_aLpWXA2a4JC9OE(Unknown Source:0)
                                                     	at org.acra.startup.StartupProcessorExecutor$$ExternalSyntheticLambda0.run(Unknown Source:6)
                                                     	at java.lang.Thread.run(Thread.java:1012)
                                                     Caused by: org.acra.sender.ReportSenderException: No email client found
                                                     	at org.acra.sender.EmailIntentSender.sendWithSelector(EmailIntentSender.kt:124)
                                                     	at org.acra.sender.EmailIntentSender.send(EmailIntentSender.kt:66)
                                                     	at org.acra.sender.ReportSender.send(ReportSender.kt:59)
                                                     	at org.acra.sender.ReportDistributor.sendCrashReport(ReportDistributor.kt:101)
                                                     	at org.acra.sender.ReportDistributor.distribute(ReportDistributor.kt:65) 
                                                     	at org.acra.sender.SendingConductor.sendReports(SendingConductor.kt:50) 
                                                     	at org.acra.scheduler.DefaultSenderScheduler.scheduleReportSending(DefaultSenderScheduler.kt:61) 
                                                     	at org.acra.scheduler.SchedulerStarter.scheduleReports(SchedulerStarter.kt:49) 
                                                     	at org.acra.startup.StartupProcessorExecutor.processReports$lambda-5$lambda-4(StartupProcessorExecutor.kt:60) 
                                                     	at org.acra.startup.StartupProcessorExecutor.$r8$lambda$o2NE53IEwtcT_aLpWXA2a4JC9OE(Unknown Source:0) 
                                                     	at org.acra.startup.StartupProcessorExecutor$$ExternalSyntheticLambda0.run(Unknown Source:6) 
                                                     	at java.lang.Thread.run(Thread.java:1012) 
                                                     Caused by: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.SEND_MULTIPLE flg=0x10000001 clip={null {U(content)}} (has extras) sel=act=android.intent.action.SENDTO dat=mailto: flg=0x10000000} }
                                                     	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2200)
                                                     	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1839)
                                                     	at android.app.ContextImpl.startActivity(ContextImpl.java:1101)
                                                     	at android.app.ContextImpl.startActivity(ContextImpl.java:1072)
                                                     	at android.content.ContextWrapper.startActivity(ContextWrapper.java:432)
                                                     	at org.acra.sender.EmailIntentSender.sendWithSelector(EmailIntentSender.kt:122)
                                                     	at org.acra.sender.EmailIntentSender.send(EmailIntentSender.kt:66) 
                                                     	at org.acra.sender.ReportSender.send(ReportSender.kt:59) 
                                                     	at org.acra.sender.ReportDistributor.sendCrashReport(ReportDistributor.kt:101) 
                                                     	at org.acra.sender.ReportDistributor.distribute(ReportDistributor.kt:65) 
                                                     	at org.acra.sender.SendingConductor.sendReports(SendingConductor.kt:50) 
                                                     	at org.acra.scheduler.DefaultSenderScheduler.scheduleReportSending(DefaultSenderScheduler.kt:61) 
                                                     	at org.acra.scheduler.SchedulerStarter.scheduleReports(SchedulerStarter.kt:49) 
                                                     	at org.acra.startup.StartupProcessorExecutor.processReports$lambda-5$lambda-4(StartupProcessorExecutor.kt:60) 
                                                     	at org.acra.startup.StartupProcessorExecutor.$r8$lambda$o2NE53IEwtcT_aLpWXA2a4JC9OE(Unknown Source:0) 
                                                     	at org.acra.startup.StartupProcessorExecutor$$ExternalSyntheticLambda0.run(Unknown Source:6) 
                                                     	at java.lang.Thread.run(Thread.java:1012) 

```

**Comment by mikehardy** [comment]
>   Caused by: org.acra.sender.ReportSenderException: No email client found

https://github.com/ACRA/acra/issues?q=is%3Aissue+%22no+email+client+found%22

Probably missing AndroidManifest changes required on Android 11+

https://github.com/ACRA/acra/issues/787#issuecomment-646536149

I do not believe this is documented (could probably use a note here https://github.com/ACRA/acra/blob/master/web/docs/Senders.mdx#sending-reports-by-email - if this solves it for you please hit the edit button and propose a PR! :pray: ) but it was easy to find searching the issues

**Comment by henrichg** [comment]
These queries are added in manifest file long time, since reported it in issue #787. :-(

**Comment by mikehardy** [comment]
Curious behavior for sure, I have not seen that type of failure unless the queries are missing *or* the phone really does not have anything registered for the intent. I help maintain react-native-share (which is Intent-based...) so I've seen this a bunch and it has always been one of those two things in the path.

But you never know with software, maybe I should prepare to be surprised here...

You can test intents on the command line to probe whether handling works or not - similar to (but not exactly...) like this https://stackoverflow.com/questions/28802115/i-am-trying-to-test-android-deep-link-urls-through-adb-to-launch-my-app if you haven't tried.

**Comment by henrichg** [comment]
OK, tested the same version in Pixel 3a, Android 12, latest firmware + GMail. And working sending e-mail witg GMail.

Then, by me, problem is Android 13, in my Pixel 6 is latest beta formware version, maybe problem is with this (beta).

**Comment by henrichg** [comment]
Why is not possible to using Intent.ACTION_SENDTO? This working in my application also in Pixel 6. Also with file attachment. This intent action is not deprecated.

**Comment by F43nd1r** [comment]
> Why is not possible to using Intent.ACTION_SENDTO? This working in my application also in Pixel 6. Also with file attachment. This intent action is not deprecated.

sendto with attachment is nonstandard. Some gmail versions support it, most other email applications don't. Also send_multiple isn't deprecated either.

**Comment by henrichg** [comment]
This is in my application, working also in Pixel 6. Is this possible to use it in ACRA mail sender?

```
// Intent for Intent.ACTION_SENDTO
Intent emailIntent = new Intent(Intent.ACTION_SENDTO, Uri.fromParts("mailto", emailAddress, null));
emailIntent.putExtra(Intent.EXTRA_SUBJECT, "PhoneProfilesPlus" + packageVersion + " - " + activity.getString(R.string.export_data_email_subject));
emailIntent.putExtra(Intent.EXTRA_TEXT, activity.getEmailBodyText());
emailIntent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);

// this fills list of intents with all intents returned from queryIntentActivities(emailIntent, 0);
// and yes, this generates intents with Intent.ACTION_SEND_MULTIPLE
List<ResolveInfo> resolveInfo = context.getPackageManager().queryIntentActivities(emailIntent, 0);
List<LabeledIntent> intents = new ArrayList<>();
for (ResolveInfo info : resolveInfo) {
    Intent intent = new Intent(Intent.ACTION_SEND_MULTIPLE);

    // set component with package name and activty from ResolveInfo
    intent.setComponent(new ComponentName(info.activityInfo.packageName, info.activityInfo.name));

    intent.putExtra(Intent.EXTRA_EMAIL, new String[]{emailAddress});
    intent.putExtra(Intent.EXTRA_SUBJECT, "PhoneProfilesPlus" + packageVersion + " - " + activity.getString(R.string.export_data_email_subject));
    intent.putExtra(Intent.EXTRA_TEXT, activity.getEmailBodyText());
    intent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);

    // files as attachments
    intent.putParcelableArrayListExtra(Intent.EXTRA_STREAM, uris);

    // generated and added labeled intent for chooser
    intents.add(new LabeledIntent(intent, info.activityInfo.packageName, info.loadLabel(context.getPackageManager()), info.icon));
}

// this starts chooser for all intents in list; when in list are more intents, opened is for user list of these intents
if (intents.size() > 0) {
    try {
        Intent chooser = Intent.createChooser(intents.get(0), context.getString(R.string.email_chooser));
        chooser.putExtra(Intent.EXTRA_INITIAL_INTENTS, intents.toArray(new LabeledIntent[intents.size()]));
        activity.startActivity(chooser);
    } catch (Exception e) {
        //Log.e("EditorActivity.ExportAsyncTask.onPostExecute", Log.getStackTraceString(e));
    }
}

```

**Comment by F43nd1r** [comment]
No, similar code had issues in the past, see #834

**Comment by henrichg** [comment]
Hm, not good. :-( 
Then how to fix this problem for Android 13? I will waiting for final Android 13 release in Pixel 6 and also for my Galaxy S21 and will testing it again.

**Comment by F43nd1r** [comment]
I'll need to debug this myself, but as I'm strechted quite thin between projects I can't promise anything soon.

If you have an implementation that works for you (but might not in general), you can always register it as a custom sender.

**Comment by RGregat** [comment]
I have the same issue starting with version 5.9.0. Version 5.8.4 is working on my Pixel 6 Pro with Android 13.

With 5.9.0 I get actually no hint what the issue is, with 5.9.6 I get the following exception

```
Failed to send crash reports for /data/user/0/com.example.dev/app_ACRA-approved/2022-10-25T16:42:00.201+02:00.stacktrace
org.acra.sender.ReportSenderException: Policy marked this task as incomplete. ACRA will try to send this report again.
    at org.acra.sender.ReportDistributor.sendCrashReport(ReportDistributor.kt:104)
    at org.acra.sender.ReportDistributor.distribute(ReportDistributor.kt:60)
    at org.acra.sender.SendingConductor.sendReports(SendingConductor.kt:50)
    at org.acra.scheduler.DefaultSenderScheduler.scheduleReportSending(DefaultSenderScheduler.kt:61)
    at org.acra.scheduler.SchedulerStarter.scheduleReports(SchedulerStarter.kt:49)
    at org.acra.startup.StartupProcessorExecutor.processReports$lambda-5$lambda-4(StartupProcessorExecutor.kt:56)
    at org.acra.startup.StartupProcessorExecutor.$r8$lambda$o2NE53IEwtcT_aLpWXA2a4JC9OE(Unknown Source:0)
    at org.acra.startup.StartupProcessorExecutor$$ExternalSyntheticLambda0.run(Unknown Source:6)
    at java.lang.Thread.run(Thread.java:1012)
Caused by: org.acra.sender.ReportSenderException: No email client found
    at org.acra.sender.EmailIntentSender.sendWithSelector(EmailIntentSender.kt:121)
    at org.acra.sender.EmailIntentSender.send(EmailIntentSender.kt:67)
    at org.acra.sender.ReportSender.send(ReportSender.kt:59)
    at org.acra.sender.ReportDistributor.sendCrashReport(ReportDistributor.kt:96)
    at org.acra.sender.ReportDistributor.distribute(ReportDistributor.kt:60) 
    at org.acra.sender.SendingConductor.sendReports(SendingConductor.kt:50) 
    at org.acra.scheduler.DefaultSenderScheduler.scheduleReportSending(DefaultSenderScheduler.kt:61) 
    at org.acra.scheduler.SchedulerStarter.scheduleReports(SchedulerStarter.kt:49) 
    at org.acra.startup.StartupProcessorExecutor.processReports$lambda-5$lambda-4(StartupProcessorExecutor.kt:56) 
    at org.acra.startup.StartupProcessorExecutor.$r8$lambda$o2NE53IEwtcT_aLpWXA2a4JC9OE(Unknown Source:0) 
    at org.acra.startup.StartupProcessorExecutor$$ExternalSyntheticLambda0.run(Unknown Source:6) 
    at java.lang.Thread.run(Thread.java:1012) 
Caused by: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.SEND_MULTIPLE flg=0x10000001 clip={null {U(content)}} (has extras) sel=act=android.intent.action.SENDTO dat=mailto: flg=0x10000000} }
    at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2161)
    at android.app.Instrumentation.execStartActivity(Instrumentation.java:1805)
    at android.app.ContextImpl.startActivity(ContextImpl.java:1101)
    at android.app.ContextImpl.startActivity(ContextImpl.java:1072)
    at android.content.ContextWrapper.startActivity(ContextWrapper.java:432)
    at org.acra.sender.EmailIntentSender.sendWithSelector(EmailIntentSender.kt:119)
    at org.acra.sender.EmailIntentSender.send(EmailIntentSender.kt:67) 
    at org.acra.sender.ReportSender.send(ReportSender.kt:59) 
    at org.acra.sender.ReportDistributor.sendCrashReport(ReportDistributor.kt:96) 
    at org.acra.sender.ReportDistributor.distribute(ReportDistributor.kt:60) 
    at org.acra.sender.SendingConductor.sendReports(SendingConductor.kt:50) 
    at org.acra.scheduler.DefaultSenderScheduler.scheduleReportSending(DefaultSenderScheduler.kt:61) 
    at org.acra.scheduler.SchedulerStarter.scheduleReports(SchedulerStarter.kt:49) 
    at org.acra.startup.StartupProcessorExecutor.processReports$lambda-5$lambda-4(StartupProcessorExecutor.kt:56) 
    at org.acra.startup.StartupProcessorExecutor.$r8$lambda$o2NE53IEwtcT_aLpWXA2a4JC9OE(Unknown Source:0) 
    at org.acra.startup.StartupProcessorExecutor$$ExternalSyntheticLambda0.run(Unknown Source:6) 
    at java.lang.Thread.run(Thread.java:1012) 
```

**Comment by henrichg** [comment]
@F43nd1r, exist documentation, how to develop custom email sender? Thank you very much.
Is problem with Java? Im my application is used Java, not Kotlin.

**Comment by F43nd1r** [comment]
Documentation for custom extensions is [here](http://www.acra.ch/docs/Custom-Extensions). `ReportSenderFactory` is the entry type in this case.
Java or Kotlin should not make a difference.

**Comment by henrichg** [comment]
Not good, custom sender is not called :-(

1. in app build.gradle added: 
```
    annotationProcessor("com.google.auto.service:auto-service:1.0.1")
    compileOnly("com.google.auto.service:auto-service-annotations:1.0.1")
```
2. created ReportSender and ReportSenderFactory by java example
3. in ACRA configuration is used MailSenderConfigurationBuilder()

What is wrong?

**Comment by F43nd1r** [comment]
Hard to tell, check debug logs if your class shows up.

**Comment by henrichg** [comment]
Hm interesting:
- Samsung Galaxy S10 (Android 10), S21 (Android 12),do not use it. By me. No logs are in logcat.
- Pixel 6 (Android 13) - use it and working, but in logs are also old exceptions. Why?

```
Failed to send crash reports for /data/user/0/sk.henrichg.phoneprofilesplus/app_ACRA-approved/2022-11-08T19:38:42.145+01:00.stacktrace
org.acra.sender.ReportSenderException: Policy marked this task as incomplete. ACRA will try to send this report again.
...
```

**Comment by F43nd1r** [comment]
There should be a [debug ](http://www.acra.ch/docs/How-to-debug#gathering-logs)line telling you which report senders and factories are loaded. Check which senders are active

**Comment by henrichg** [comment]
Log: https://drive.google.com/file/d/1wCtPb5M8Fg60T361cPJxbOm4nTy7x9eF/view?usp=drivesdk
I
In it is logcat from:
- Galaxy S21 -> default ReportSender was called
- Pixel 6 -> my custom ReportSender was called

**Comment by henrichg** [comment]
Yesterday was upgraded my Galaxy S21 to OneUI 5, Android 13, official upgrade.
And sending e-mails do not work at all, with and without a custom ReportSender.

Log: https://drive.google.com/file/d/1CC77EC7aGsfYrVrhIN2gknLCSGCWlmxK/view?usp=drivesdk

**Comment by jefflongo** [comment]
Also encountering this issue on S22+ Android 13. Is there any current fixes or workarounds?

**Comment by yuriykulikov** [comment]
I am also experiencing this on Android 13. I can only see these 2 suspicious lines:
```
2022-11-27 12:33:25.490  2341-4522  PackageManager          pid-2341                             W  Intent does not match component's intent filter: Intent { act=android.intent.action.SEND_MULTIPLE flg=0x10000000 (has extras) sel=act=android.intent.action.SENDTO dat=mailto: flg=0x10000000} }

2022-11-27 12:33:25.490  2341-4522  PackageManager          pid-2341                             W  Access blocked: ComponentInfo{com.google.android.gm/com.google.android.gm.ComposeActivityGmailExternal}
```

Followed by an exception:
```
2022-11-27 12:33:25.490  8817-8817  Bundle                  com.better.alarm                     W  Key android.intent.extra.TEXT expected ArrayList<java.lang.CharSequence> but value was of a different type.  The default value <null> was returned.
2022-11-27 12:33:25.491  8817-8817  Bundle                  com.better.alarm                     W  Attempt to cast generated internal exception:
                                                                                                    java.lang.ClassCastException: Cannot cast java.lang.String to java.util.ArrayList
                                                                                                    	at java.lang.Class.cast(Class.java:2479)
                                                                                                    	at android.os.BaseBundle.getValueAt(BaseBundle.java:405)
                                                                                                    	at android.os.BaseBundle.getValue(BaseBundle.java:374)
                                                                                                    	at android.os.BaseBundle.getArrayList(BaseBundle.java:1486)
                                                                                                    	at android.os.BaseBundle.getCharSequenceArrayList(BaseBundle.java:1529)
                                                                                                    	at android.os.Bundle.getCharSequenceArrayList(Bundle.java:1204)
                                                                                                    	at android.content.Intent.getCharSequenceArrayListExtra(Intent.java:9053)
                                                                                                    	at android.content.Intent.migrateExtraStreamToClipData(Intent.java:12089)
                                                                                                    	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1799)
                                                                                                    	at android.app.ContextImpl.startActivity(ContextImpl.java:1101)
                                                                                                    	at android.app.ContextImpl.startActivity(ContextImpl.java:1072)
                                                                                                    	at android.content.ContextWrapper.startActivity(ContextWrapper.java:432)
                                                                                                    	at org.acra.sender.EmailIntentSender.sendWithSelector(EmailIntentSender.kt:122)
                                                                                                    	at org.acra.sender.EmailIntentSender.send(EmailIntentSender.kt:66)
                                                                                                    	at org.acra.sender.ReportSender.send(ReportSender.kt:59)
                                                                                                    	at org.acra.sender.ReportDistributor.sendCrashReport(ReportDistributor.kt:101)
                                                                                                    	at org.acra.sender.ReportDistributor.distribute(ReportDistributor.kt:65)
                                                                                                    	at org.acra.sender.SendingConductor.sendReports(SendingConductor.kt:50)
                                                                                                    	at org.acra.scheduler.DefaultSenderScheduler.scheduleReportSending(DefaultSenderScheduler.kt:61)
                                                                                                    	at org.acra.scheduler.SchedulerStarter.scheduleReports(SchedulerStarter.kt:49)
                                                                                                    	at org.acra.builder.ReportExecutor.sendReport(ReportExecutor.kt:197)
                                                                                                    	at org.acra.builder.ReportExecutor.execute(ReportExecutor.kt:132)
                                                                                                    	at org.acra.builder.ReportBuilder.build(ReportBuilder.kt:151)
                                                                                                    	at org.acra.reporter.ErrorReporterImpl.handleSilentException(ErrorReporterImpl.kt:118)
```

**Comment by F43nd1r** [comment]
@yuriykulikov that warning is indeed part of the problem. The ClassCastException is not, it has to be ignored as I can't prevent it from appearing in the logs. Has been there for a long time but doesn't matter.

---

Investigation shows the problem is with gmail and [Android 13 security behaviour changes](https://developer.android.com/about/versions/13/behavior-changes-all#intents). Basically gmail doesn't match intents with a selector or without a mime type anymore.

I had to implement a double fallback to match it on my device.
Unfortunately this also means #831 might still show up on android 13+ devices.

**Comment by henrichg** [comment]
@F43nd1r, 5.9.7 works! :-)

Tested in Pixel 6, Android 13, installed only GMail.

Thank you very much.

**Comment by yuriykulikov** [comment]
@F43nd1r unfortunately the issue is still present in `5.9.7`, Pixel 6a, Android 13, Gmail. I can only see these suspicious lines in the logs:
```
2022-12-30 20:02:31.549 29618-29618 ACRA                    com.better.alarm.debug               I  Sending report /data/user/0/com.better.alarm.debug/app_ACRA-approved/2022-12-30T20:02:31.537+01:00-IS_SILENT.stacktrace
2022-12-30 20:02:31.560  1685-7546  PackageManager          pid-1685                             W  Intent does not match component's intent filter: Intent { act=android.intent.action.SEND flg=0x10000000 (has extras) sel=act=android.intent.action.SENDTO dat=mailto: flg=0x10000000} }
2022-12-30 20:02:31.560  1685-7546  PackageManager          pid-1685                             W  Access blocked: ComponentInfo{com.google.android.gm/com.google.android.gm.ComposeActivityGmailExternal}
```

**Comment by arcanewater** [comment]
We are again having this trouble with Android 13 and Gmail, one thing i spotted is that if i only have gmail and there is no selector it does not work, but if i have another email client (ex. outlook) and i select in chooser Gmail it works normally. We are using latest 5.9.7 version and this started happening recently (previously it worked okay)
