### ISSUE TITLE
HttpSender not sending anything

### ISSUE THREAD

**Issue by aminecmi** [ACRA/acra#1163]
Hi,

I'm not receiving any bug reports to my acrarium instance. Everything was working fine, and suddenly, I stopped receiving reports.

I tried looking in the debug logs, but I can't find what would be the issue.

```
2023-02-19 21:10:04.526   552-552   JobServiceContext       system_server                        W  Time-out while trying to bind 1e9faef #u0a165/0 MYAPP/org.acra.sender.JobSenderService, dropping.
2023-02-19 21:10:05.107 18210-18210 ACRA                    bou...ps.MYAPP  E  ACRA caught a NotFoundException for MYAPP
                                                                                                    android.content.res.Resources$NotFoundException
                                                                                                    	at MYAPP.HomeActivity.onOptionsItemSelected(HomeActivity.kt:603)
                                                                                                    	at android.app.Activity.onMenuItemSelected(Activity.java:4343)
                                                                                                    	at androidx.activity.ComponentActivity.onMenuItemSelected(ComponentActivity.java:514)
                                                                                                    	at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:265)
                                                                                                    	at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:266)
                                                                                                    	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:110)
                                                                                                    	at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:66)
                                                                                                    	at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:221)
                                                                                                    	at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:781)
                                                                                                    	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:836)
                                                                                                    	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:159)
                                                                                                    	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:987)
                                                                                                    	at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
                                                                                                    	at android.widget.AdapterView.performItemClick(AdapterView.java:330)
                                                                                                    	at android.widget.AbsListView.performItemClick(AbsListView.java:1197)
                                                                                                    	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3190)
                                                                                                    	at android.widget.AbsListView$3.run(AbsListView.java:4166)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7842)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
2023-02-19 21:10:05.107 18210-18210 ACRA                    bou...ps.MYAPP  D  Building report
2023-02-19 21:10:05.108 18210-18210 ACRA                    bou...ps.MYAPP  D  Starting collectors with priority FIRST
2023-02-19 21:10:05.109 18210-18359 ACRA                    bou...ps.MYAPP  D  Calling collector org.acra.collector.StacktraceCollector
2023-02-19 21:10:05.109 18210-18358 ACRA                    bou...ps.MYAPP  D  Calling collector org.acra.collector.LogCatCollector
2023-02-19 21:10:05.109 18210-18357 ACRA                    bou...ps.MYAPP  D  Calling collector org.acra.collector.DropBoxCollector
2023-02-19 21:10:05.109 18210-18357 ACRA                    bou...ps.MYAPP  D  Collector org.acra.collector.DropBoxCollector completed
2023-02-19 21:10:05.109 18210-18359 ACRA                    bou...ps.MYAPP  D  Collector org.acra.collector.StacktraceCollector completed
2023-02-19 21:10:05.110 18210-18358 ACRA                    bou...ps.MYAPP  D  Retrieving logcat output (buffer:default)...
2023-02-19 21:10:05.115 18210-18358 ACRA                    bou...ps.MYAPP  D  Collector org.acra.collector.LogCatCollector completed
2023-02-19 21:10:05.116 18210-18210 ACRA                    bou...ps.MYAPP  D  Finished collectors with priority FIRST
2023-02-19 21:10:05.116 18210-18210 ACRA                    bou...ps.MYAPP  D  Starting collectors with priority NORMAL
2023-02-19 21:10:05.116 18210-18359 ACRA                    bou...ps.MYAPP  D  Calling collector org.acra.collector.CustomDataCollector
2023-02-19 21:10:05.116 18210-18359 ACRA                    bou...ps.MYAPP  D  Collector org.acra.collector.CustomDataCollector completed
2023-02-19 21:10:05.116 18210-18363 ACRA                    bou...ps.MYAPP  D  Calling collector org.acra.collector.DeviceIdCollector
2023-02-19 21:10:05.116 18210-18363 ACRA                    bou...ps.MYAPP  D  Collector org.acra.collector.DeviceIdCollector completed
2023-02-19 21:10:05.116 18210-18358 ACRA                    bou...ps.MYAPP  D  Calling collector org.acra.collector.ConfigurationCollector
2023-02-19 21:10:05.116 18210-18357 ACRA                    bou...ps.MYAPP  D  Calling collector org.acra.collector.DeviceFeaturesCollector
2023-02-19 21:10:05.116 18210-18359 ACRA                    bou...ps.MYAPP  D  Calling collector org.acra.collector.MemoryInfoCollector
2023-02-19 21:10:05.116 18210-18357 ACRA                    bou...ps.MYAPP  D  Collector org.acra.collector.DeviceFeaturesCollector completed
2023-02-19 21:10:05.116 18210-18363 ACRA                    bou...ps.MYAPP  D  Calling collector org.acra.collector.SharedPreferencesCollector
2023-02-19 21:10:05.117 18210-18357 ACRA                    bou...ps.MYAPP  D  Calling collector org.acra.collector.SettingsCollector
2023-02-19 21:10:05.117 18210-18363 ACRA                    bou...ps.MYAPP  D  Collector org.acra.collector.SharedPreferencesCollector completed
2023-02-19 21:10:05.117 18210-18367 ACRA                    bou...ps.MYAPP  D  Calling collector org.acra.collector.SimpleValuesCollector
2023-02-19 21:10:05.117 18210-18357 ACRA                    bou...ps.MYAPP  D  Collector org.acra.collector.SettingsCollector completed
2023-02-19 21:10:05.118 18210-18366 ACRA                    bou...ps.MYAPP  D  Calling collector org.acra.collector.ReflectionCollector
2023-02-19 21:10:05.118 18210-18364 ACRA                    bou...ps.MYAPP  D  Calling collector org.acra.collector.DisplayManagerCollector
2023-02-19 21:10:05.119 18210-18364 ACRA                    bou...ps.MYAPP  D  Collector org.acra.collector.DisplayManagerCollector completed
2023-02-19 21:10:05.119 18210-18359 ACRA                    bou...ps.MYAPP  D  Collector org.acra.collector.MemoryInfoCollector completed
2023-02-19 21:10:05.120 18210-18365 ACRA                    bou...ps.MYAPP  D  Calling collector org.acra.collector.PackageManagerCollector
2023-02-19 21:10:05.120 18210-18368 ACRA                    bou...ps.MYAPP  D  Calling collector org.acra.collector.TimeCollector
2023-02-19 21:10:05.121 18210-18358 ACRA                    bou...ps.MYAPP  D  Collector org.acra.collector.ConfigurationCollector completed
2023-02-19 21:10:05.122 18210-18365 ACRA                    bou...ps.MYAPP  D  Collector org.acra.collector.PackageManagerCollector completed
2023-02-19 21:10:05.123 18210-18366 ACRA                    bou...ps.MYAPP  D  Collector org.acra.collector.ReflectionCollector completed
2023-02-19 21:10:05.123 18210-18368 ACRA                    bou...ps.MYAPP  D  Collector org.acra.collector.TimeCollector completed
2023-02-19 21:10:05.124 18210-18367 ACRA                    bou...ps.MYAPP  D  Collector org.acra.collector.SimpleValuesCollector completed
2023-02-19 21:10:05.124 18210-18210 ACRA                    bou...ps.MYAPP  D  Finished collectors with priority NORMAL
2023-02-19 21:10:05.124 18210-18210 ACRA                    bou...ps.MYAPP  D  Starting collectors with priority LATE
2023-02-19 21:10:05.125 18210-18366 ACRA                    bou...ps.MYAPP  D  Calling collector org.acra.collector.ThreadCollector
2023-02-19 21:10:05.125 18210-18366 ACRA                    bou...ps.MYAPP  D  Collector org.acra.collector.ThreadCollector completed
2023-02-19 21:10:05.125 18210-18368 ACRA                    bou...ps.MYAPP  D  Calling collector org.acra.collector.LogFileCollector
2023-02-19 21:10:05.125 18210-18368 ACRA                    bou...ps.MYAPP  W  APPLICATION_LOG was enabled but applicationLogFile was not set. No application log will be recorded.
2023-02-19 21:10:05.125 18210-18368 ACRA                    bou...ps.MYAPP  D  Collector org.acra.collector.LogFileCollector completed
2023-02-19 21:10:05.125 18210-18367 ACRA                    bou...ps.MYAPP  D  Calling collector org.acra.collector.MediaCodecListCollector
2023-02-19 21:10:05.125 18210-18367 ACRA                    bou...ps.MYAPP  D  Collector org.acra.collector.MediaCodecListCollector completed
2023-02-19 21:10:05.125 18210-18210 ACRA                    bou...ps.MYAPP  D  Finished collectors with priority LATE
2023-02-19 21:10:05.125 18210-18210 ACRA                    bou...ps.MYAPP  D  Finishing activities prior to killing the Process
2023-02-19 21:10:05.134 18210-18210 ACRA                    bou...ps.MYAPP  D  Finished class MYAPP.HomeActivity
2023-02-19 21:10:05.138 18210-18210 ACRA                    bou...ps.MYAPP  D  Writing crash report file /data/user/0/MYAPP/app_ACRA-unapproved/2023-02-19T21:10:05.122+01:00.stacktrace
2023-02-19 21:10:05.141 18210-18210 ACRA                    bou...ps.MYAPP  D  ServicePluginLoader loading services from ServiceLoader : java.util.ServiceLoader[org.acra.interaction.ReportInteraction]
2023-02-19 21:10:05.144 18210-18210 ACRA                    bou...ps.MYAPP  D  Checking plugin Configurations : [org.acra.config.ToastConfiguration@49eeace, org.acra.config.HttpSenderConfiguration@42e5da] for class : class org.acra.config.ToastConfiguration
2023-02-19 21:10:05.145 18210-18210 ACRA                    bou...ps.MYAPP  D  Checking plugin Configuration : org.acra.config.ToastConfiguration@49eeace against plugin class : class org.acra.config.ToastConfiguration
2023-02-19 21:10:05.145 18210-18210 ACRA                    bou...ps.MYAPP  D  Loaded ReportInteraction of type org.acra.interaction.ToastInteraction
2023-02-19 21:10:05.146 18210-18369 ACRA                    bou...ps.MYAPP  D  Calling ReportInteraction of class org.acra.interaction.ToastInteraction
2023-02-19 21:10:05.146 18210-18369 ACRA                    bou...ps.MYAPP  D  Checking plugin Configurations : [org.acra.config.ToastConfiguration@49eeace, org.acra.config.HttpSenderConfiguration@42e5da] for class : class org.acra.config.ToastConfiguration
2023-02-19 21:10:05.146 18210-18369 ACRA                    bou...ps.MYAPP  D  Checking plugin Configuration : org.acra.config.ToastConfiguration@49eeace against plugin class : class org.acra.config.ToastConfiguration
2023-02-19 21:10:07.259 18210-18210 ACRA                    bou...ps.MYAPP  D  Mark 2023-02-19T21:10:05.122+01:00.stacktrace as approved.
2023-02-19 21:10:07.259 18210-18210 ACRA                    bou...ps.MYAPP  D  Schedule report sending
2023-02-19 21:10:07.260 18210-18210 ACRA                    bou...ps.MYAPP  D  Using PluginLoader to find ReportSender factories
2023-02-19 21:10:07.260 18210-18210 ACRA                    bou...ps.MYAPP  D  ServicePluginLoader loading services from ServiceLoader : java.util.ServiceLoader[org.acra.sender.ReportSenderFactory]
2023-02-19 21:10:07.261 18210-18210 ACRA                    bou...ps.MYAPP  D  Checking plugin Configurations : [org.acra.config.ToastConfiguration@49eeace, org.acra.config.HttpSenderConfiguration@42e5da] for class : class org.acra.config.HttpSenderConfiguration
2023-02-19 21:10:07.261 18210-18210 ACRA                    bou...ps.MYAPP  D  Checking plugin Configuration : org.acra.config.ToastConfiguration@49eeace against plugin class : class org.acra.config.HttpSenderConfiguration
2023-02-19 21:10:07.261 18210-18210 ACRA                    bou...ps.MYAPP  D  Checking plugin Configuration : org.acra.config.HttpSenderConfiguration@42e5da against plugin class : class org.acra.config.HttpSenderConfiguration
2023-02-19 21:10:07.261 18210-18210 ACRA                    bou...ps.MYAPP  D  Loaded ReportSenderFactory of type org.acra.sender.HttpSenderFactory
2023-02-19 21:10:07.261 18210-18210 ACRA                    bou...ps.MYAPP  D  reportSenderFactories : [org.acra.sender.HttpSenderFactory@ea84893]
2023-02-19 21:10:07.261 18210-18210 ACRA                    bou...ps.MYAPP  D  Checking plugin Configurations : [org.acra.config.ToastConfiguration@49eeace, org.acra.config.HttpSenderConfiguration@42e5da] for class : class org.acra.config.HttpSenderConfiguration
2023-02-19 21:10:07.261 18210-18210 ACRA                    bou...ps.MYAPP  D  Checking plugin Configuration : org.acra.config.ToastConfiguration@49eeace against plugin class : class org.acra.config.HttpSenderConfiguration
2023-02-19 21:10:07.261 18210-18210 ACRA                    bou...ps.MYAPP  D  Checking plugin Configuration : org.acra.config.HttpSenderConfiguration@42e5da against plugin class : class org.acra.config.HttpSenderConfiguration
2023-02-19 21:10:07.261 18210-18210 ACRA                    bou...ps.MYAPP  D  Adding reportSender : org.acra.sender.HttpSender@875e0d0
2023-02-19 21:10:07.264 18210-18210 ACRA                    bou...ps.MYAPP  D  Using PluginLoader to find ReportSender factories
2023-02-19 21:10:07.264 18210-18210 ACRA                    bou...ps.MYAPP  D  ServicePluginLoader loading services from ServiceLoader : java.util.ServiceLoader[org.acra.sender.ReportSenderFactory]
2023-02-19 21:10:07.265 18210-18210 ACRA                    bou...ps.MYAPP  D  Checking plugin Configurations : [org.acra.config.ToastConfiguration@49eeace, org.acra.config.HttpSenderConfiguration@42e5da] for class : class org.acra.config.HttpSenderConfiguration
2023-02-19 21:10:07.265 18210-18210 ACRA                    bou...ps.MYAPP  D  Checking plugin Configuration : org.acra.config.ToastConfiguration@49eeace against plugin class : class org.acra.config.HttpSenderConfiguration
2023-02-19 21:10:07.265 18210-18210 ACRA                    bou...ps.MYAPP  D  Checking plugin Configuration : org.acra.config.HttpSenderConfiguration@42e5da against plugin class : class org.acra.config.HttpSenderConfiguration
2023-02-19 21:10:07.265 18210-18210 ACRA                    bou...ps.MYAPP  D  Loaded ReportSenderFactory of type org.acra.sender.HttpSenderFactory
2023-02-19 21:10:07.265 18210-18210 ACRA                    bou...ps.MYAPP  D  reportSenderFactories : [org.acra.sender.HttpSenderFactory@904daef]
2023-02-19 21:10:07.265 18210-18210 ACRA                    bou...ps.MYAPP  D  Checking plugin Configurations : [org.acra.config.ToastConfiguration@49eeace, org.acra.config.HttpSenderConfiguration@42e5da] for class : class org.acra.config.HttpSenderConfiguration
2023-02-19 21:10:07.265 18210-18210 ACRA                    bou...ps.MYAPP  D  Checking plugin Configuration : org.acra.config.ToastConfiguration@49eeace against plugin class : class org.acra.config.HttpSenderConfiguration
2023-02-19 21:10:07.265 18210-18210 ACRA                    bou...ps.MYAPP  D  Checking plugin Configuration : org.acra.config.HttpSenderConfiguration@42e5da against plugin class : class org.acra.config.HttpSenderConfiguration
2023-02-19 21:10:07.265 18210-18210 ACRA                    bou...ps.MYAPP  D  Adding reportSender : org.acra.sender.HttpSender@5a039fc
2023-02-19 21:10:07.265 18210-18210 ACRA                    bou...ps.MYAPP  D  Wait for Interactions + worker ended. Kill Application ? true
2023-02-19 21:10:07.267   552-579   ActivityManager         system_server                        I  Start proc 18377:MYAPP:acra/u0a165 for service {MYAPP/org.acra.sender.JobSenderService}
---------------------------- PROCESS ENDED (18210) for package MYAPP ----------------------------
---------------------------- PROCESS STARTED (18377) for package MYAPP ----------------------------
2023-02-19 21:10:07.522 18377-18377 ACRA                    bou...ps.MYAPP  D  ACRA processName='MYAPP:acra'
2023-02-19 21:10:07.522 18377-18377 ACRA                    bou...ps.MYAPP  D  Not initialising ACRA to listen for uncaught Exceptions as this is the SendWorker process and we only send reports, we don't capture them to avoid infinite loops
2023-02-19 21:10:07.524 18377-18377 ACRA                    bou...ps.MYAPP  D  Registered content provider for authority MYAPP.acra
2023-02-19 21:10:07.525 18377-18377 ACRA                    bou...ps.MYAPP  D  ACRA processName='MYAPP:acra'
2023-02-19 21:10:07.535 18377-18377 AndroidRuntime          bou...ps.MYAPP  E  FATAL EXCEPTION: main
                                                                                                    Process: MYAPP:acra, PID: 18377
                                                                                                    java.lang.RuntimeException: Unable to create application MYAPP.MyApp: java.lang.NullPointerException
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6739)
                                                                                                    	at android.app.ActivityThread.access$1500(ActivityThread.java:256)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2090)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7842)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
                                                                                                    Caused by: java.lang.NullPointerException
                                                                                                    	at com.russhwolf.settings.NoArgKt.Settings(NoArg.kt:32)
                                                                                                    	at MYAPP.service.AppSettingsService.<init>(AppSettingsService.kt:6)
                                                                                                    	at MYAPP.DI.ModulesKt$networkModule$2$1.invoke(modules.kt:12)
                                                                                                    	at MYAPP.DI.ModulesKt$networkModule$2$1.invoke(modules.kt:12)
                                                                                                    	at org.kodein.di.bindings.Singleton$getFactory$1$1$1.invoke(standardBindings.kt:134)
                                                                                                    	at org.kodein.di.bindings.SingletonReference.make(references.kt:34)
                                                                                                    	at org.kodein.di.bindings.Singleton$getFactory$1$1.invoke(standardBindings.kt:134)
                                                                                                    	at org.kodein.di.bindings.Singleton$getFactory$1$1.invoke(standardBindings.kt:134)
                                                                                                    	at org.kodein.di.bindings.StandardScopeRegistry.getOrCreate(scopes.kt:66)
                                                                                                    	at org.kodein.di.bindings.Singleton$getFactory$1.invoke(standardBindings.kt:134)
                                                                                                    	at org.kodein.di.bindings.Singleton$getFactory$1.invoke(standardBindings.kt:131)
                                                                                                    	at org.kodein.di.DIContainer$DefaultImpls$provider$$inlined$toProvider$1.invoke(curry.kt:14)
                                                                                                    	at org.kodein.di.internal.DirectDIBaseImpl.Instance(DirectDIImpl.kt:30)
                                                                                                    	at MYAPP.DI.ModulesKt$networkModule$2$2.invoke(modules.kt:16)
                                                                                                    	at MYAPP.DI.ModulesKt$networkModule$2$2.invoke(modules.kt:13)
                                                                                                    	at org.kodein.di.bindings.Singleton$getFactory$1$1$1.invoke(standardBindings.kt:134)
                                                                                                    	at org.kodein.di.bindings.SingletonReference.make(references.kt:34)
                                                                                                    	at org.kodein.di.bindings.Singleton$getFactory$1$1.invoke(standardBindings.kt:134)
                                                                                                    	at org.kodein.di.bindings.Singleton$getFactory$1$1.invoke(standardBindings.kt:134)
                                                                                                    	at org.kodein.di.bindings.StandardScopeRegistry.getOrCreate(scopes.kt:66)
                                                                                                    	at org.kodein.di.bindings.Singleton$getFactory$1.invoke(standardBindings.kt:134)
                                                                                                    	at org.kodein.di.bindings.Singleton$getFactory$1.invoke(standardBindings.kt:131)
                                                                                                    	at org.kodein.di.DIContainer$DefaultImpls$provider$$inlined$toProvider$1.invoke(curry.kt:14)
                                                                                                    	at org.kodein.di.internal.DirectDIBaseImpl.Instance(DirectDIImpl.kt:30)
                                                                                                    	at MYAPP.MyApp$di$2$3.invoke(MyApp.kt:195)
                                                                                                    	at MYAPP.MyApp$di$2$3.invoke(MyApp.kt:40)
                                                                                                    	at org.kodein.di.bindings.Singleton$getFactory$1$1$1.invoke(standardBindings.kt:134)
                                                                                                    	at org.kodein.di.bindings.SingletonReference.make(references.kt:34)
                                                                                                    	at org.kodein.di.bindings.Singleton$getFactory$1$1.invoke(standardBindings.kt:134)
                                                                                                    	at org.kodein.di.bindings.Singleton$getFactory$1$1.invoke(standardBindings.kt:134)
                                                                                                    	at org.kodein.di.bindings.StandardScopeRegistry.getOrCreate(scopes.kt:66)
                                                                                                    	at org.kodein.di.bindings.Singleton$getFactory$1.invoke(standardBindings.kt:134)
                                                                                                    	at org.kodein.di.bindings.Singleton$getFactory$1.invoke(standardBindings.kt:131)
                                                                                                    	at org.kodein.di.DIContainer$DefaultImpls$provider$$inlined$toProvider$1.invoke(curry.kt:14)
                                                                                                    	at org.kodein.di.DIAwareKt$Instance$1.invoke(DIAware.kt:209)
                                                                                                    	at org.kodein.di.DIAwareKt$Instance$1.invoke(DIAware.kt:207)
                                                                                                    	at org.kodein.di.DIProperty$provideDelegate$1.invoke(properties.kt:57)
                                                                                                    	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
2023-02-19 21:10:07.547   552-720   ActivityManager         system_server                        I  Process MYAPP:acra (pid 18377) has died: fg  TRNB
---------------------------- PROCESS ENDED (18377) for package MYAPP ----------------------------
2023-02-19 21:10:07.547   552-720   ActivityManager         system_server                        W  Scheduling restart of crashed service MYAPP/org.acra.sender.JobSenderService in 1000ms for connection
2023-02-19 21:10:08.596   552-579   ActivityManager         system_server                        I  Start proc 18406:MYAPP:acra/u0a165 for service {MYAPP/org.acra.sender.JobSenderService}
---------------------------- PROCESS STARTED (18406) for package MYAPP ----------------------------
2023-02-19 21:10:08.868 18406-18406 ACRA                    bou...ps.MYAPP  D  ACRA processName='MYAPP:acra'
2023-02-19 21:10:08.868 18406-18406 ACRA                    bou...ps.MYAPP  D  Not initialising ACRA to listen for uncaught Exceptions as this is the SendWorker process and we only send reports, we don't capture them to avoid infinite loops
2023-02-19 21:10:08.870 18406-18406 ACRA                    bou...ps.MYAPP  D  Registered content provider for authority MYAPP.acra
2023-02-19 21:10:08.872 18406-18406 ACRA                    bou...ps.MYAPP  D  ACRA processName='MYAPP:acra'
2023-02-19 21:10:08.881 18406-18406 AndroidRuntime          bou...ps.MYAPP  E  FATAL EXCEPTION: main
                                                                                                    Process: MYAPP:acra, PID: 18406
                                                                                                    java.lang.RuntimeException: Unable to create application MYAPP.MyApp: java.lang.NullPointerException
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6739)
                                                                                                    	at android.app.ActivityThread.access$1500(ActivityThread.java:256)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2090)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7842)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
                                                                                                    Caused by: java.lang.NullPointerException
                                                                                                    	at com.russhwolf.settings.NoArgKt.Settings(NoArg.kt:32)
                                                                                                    	at MYAPP.service.AppSettingsService.<init>(AppSettingsService.kt:6)
                                                                                                    	at MYAPP.DI.ModulesKt$networkModule$2$1.invoke(modules.kt:12)
                                                                                                    	at MYAPP.DI.ModulesKt$networkModule$2$1.invoke(modules.kt:12)
                                                                                                    	at org.kodein.di.bindings.Singleton$getFactory$1$1$1.invoke(standardBindings.kt:134)
                                                                                                    	at org.kodein.di.bindings.SingletonReference.make(references.kt:34)
                                                                                                    	at org.kodein.di.bindings.Singleton$getFactory$1$1.invoke(standardBindings.kt:134)
                                                                                                    	at org.kodein.di.bindings.Singleton$getFactory$1$1.invoke(standardBindings.kt:134)
                                                                                                    	at org.kodein.di.bindings.StandardScopeRegistry.getOrCreate(scopes.kt:66)
                                                                                                    	at org.kodein.di.bindings.Singleton$getFactory$1.invoke(standardBindings.kt:134)
                                                                                                    	at org.kodein.di.bindings.Singleton$getFactory$1.invoke(standardBindings.kt:131)
                                                                                                    	at org.kodein.di.DIContainer$DefaultImpls$provider$$inlined$toProvider$1.invoke(curry.kt:14)
                                                                                                    	at org.kodein.di.internal.DirectDIBaseImpl.Instance(DirectDIImpl.kt:30)
                                                                                                    	at MYAPP.DI.ModulesKt$networkModule$2$2.invoke(modules.kt:16)
                                                                                                    	at MYAPP.DI.ModulesKt$networkModule$2$2.invoke(modules.kt:13)
                                                                                                    	at org.kodein.di.bindings.Singleton$getFactory$1$1$1.invoke(standardBindings.kt:134)
                                                                                                    	at org.kodein.di.bindings.SingletonReference.make(references.kt:34)
                                                                                                    	at org.kodein.di.bindings.Singleton$getFactory$1$1.invoke(standardBindings.kt:134)
                                                                                                    	at org.kodein.di.bindings.Singleton$getFactory$1$1.invoke(standardBindings.kt:134)
                                                                                                    	at org.kodein.di.bindings.StandardScopeRegistry.getOrCreate(scopes.kt:66)
                                                                                                    	at org.kodein.di.bindings.Singleton$getFactory$1.invoke(standardBindings.kt:134)
                                                                                                    	at org.kodein.di.bindings.Singleton$getFactory$1.invoke(standardBindings.kt:131)
                                                                                                    	at org.kodein.di.DIContainer$DefaultImpls$provider$$inlined$toProvider$1.invoke(curry.kt:14)
                                                                                                    	at org.kodein.di.internal.DirectDIBaseImpl.Instance(DirectDIImpl.kt:30)
                                                                                                    	at MYAPP.MyApp$di$2$3.invoke(MyApp.kt:195)
                                                                                                    	at MYAPP.MyApp$di$2$3.invoke(MyApp.kt:40)
                                                                                                    	at org.kodein.di.bindings.Singleton$getFactory$1$1$1.invoke(standardBindings.kt:134)
                                                                                                    	at org.kodein.di.bindings.SingletonReference.make(references.kt:34)
                                                                                                    	at org.kodein.di.bindings.Singleton$getFactory$1$1.invoke(standardBindings.kt:134)
                                                                                                    	at org.kodein.di.bindings.Singleton$getFactory$1$1.invoke(standardBindings.kt:134)
                                                                                                    	at org.kodein.di.bindings.StandardScopeRegistry.getOrCreate(scopes.kt:66)
                                                                                                    	at org.kodein.di.bindings.Singleton$getFactory$1.invoke(standardBindings.kt:134)
                                                                                                    	at org.kodein.di.bindings.Singleton$getFactory$1.invoke(standardBindings.kt:131)
                                                                                                    	at org.kodein.di.DIContainer$DefaultImpls$provider$$inlined$toProvider$1.invoke(curry.kt:14)
                                                                                                    	at org.kodein.di.DIAwareKt$Instance$1.invoke(DIAware.kt:209)
                                                                                                    	at org.kodein.di.DIAwareKt$Instance$1.invoke(DIAware.kt:207)
                                                                                                    	at org.kodein.di.DIProperty$provideDelegate$1.invoke(properties.kt:57)
                                                                                                    	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
2023-02-19 21:10:08.890   552-2514  ActivityManager         system_server                        I  Process MYAPP:acra (pid 18406) has died: fg  TRNB
2023-02-19 21:10:08.890   552-2514  ActivityManager         system_server                        W  Scheduling restart of crashed service MYAPP/org.acra.sender.JobSenderService in 1800000ms for connection
---------------------------- PROCESS ENDED (18406) for package MYAPP ----------------------------

```

Any help would be great.

Thanks.

**Version**
 - Android: 12
 - ACRA 5.9.7

**Comment by F43nd1r** [comment]
Looks like something in your application tries to initialize in our sender process. Try to disable any unneeded initialization code when in sender process, see http://www.acra.ch/docs/Troubleshooting-Guide#applicationoncreate

**Comment by aminecmi** [comment]
This fixed my issue, but I can't figure out why it did work at some point.

Thanks.
