### ISSUE TITLE
java.lang.InternalError: Thread starting during runtime shutdown

### ISSUE THREAD

**Issue by riclage** [ACRA/acra#136]
I'm getting users reporting the following error via the Play Store reporting:

at java.lang.Thread.nativeCreate(Native Method)
at java.lang.Thread.start(Thread.java:1042)
at org.apache.http.impl.conn.tsccm.AbstractConnPool.enableConnectionGC(AbstractConnPool.java:140)
at org.apache.http.impl.conn.tsccm.ThreadSafeClientConnManager.createConnectionPool(ThreadSafeClientConnManager.java:120)
at org.apache.http.impl.conn.tsccm.ThreadSafeClientConnManager.<init>(ThreadSafeClientConnManager.java:98)
at org.acra.e.c.a(HttpRequest.java:214)
at org.acra.e.c.a(HttpRequest.java:141)
at org.acra.sender.HttpSender.a(HttpSender.java:225)
at org.acra.g.a(SendWorker.java:179)
at org.acra.g.a(SendWorker.java:141)
at org.acra.g.run(SendWorker.java:77)

Since it's from users, I can't really know at what point this is occurring. Any ideas? I'm using Acra version 4.5.0.

**Comment by xing634325131** [comment]
it occur again.
1.
```
java.lang.InternalError: Thread starting during runtime shutdown
	at java.lang.Thread.nativeCreate(Native Method)
	at java.lang.Thread.start(Thread.java:1063)
	at java.lang.ProcessManager.<init>(ProcessManager.java:62)
	at java.lang.ProcessManager.<clinit>(ProcessManager.java:335)
	at java.lang.Runtime.exec(Runtime.java:173)
	at java.lang.Runtime.exec(Runtime.java:128)
```
2.
```
java.lang.InternalError: Thread starting during runtime shutdown
	at java.lang.Thread.nativeCreate(Native Method)
	at java.lang.Thread.start(Thread.java:1063)
	at org.apache.http.impl.conn.tsccm.AbstractConnPool.enableConnectionGC(AbstractConnPool.java:140)
	at org.apache.http.impl.conn.tsccm.ThreadSafeClientConnManager.createConnectionPool(ThreadSafeClientConnManager.java:120)
	at org.apache.http.impl.conn.tsccm.ThreadSafeClientConnManager.<init>(ThreadSafeClientConnManager.java:98)
	at rq.a(Unknown Source)
```

**Comment by william-ferguson-au** [comment]
Not from ACRA-4.6.0+ it didn't because ACRA no longer uses ThreadSafeClientConnManager.

**Comment by xing634325131** [comment]
Can you tell me what the problem led to this? it's very important for me.

**Comment by william-ferguson-au** [comment]
Your problem is coming from `at rq.a(Unknown Source)`.
Find out what that is (it appears to be Proguarded).

**Comment by xmenxwk** [comment]
The problem exists in acra4.7, Android 5.1.1. Device D5803.


> java.lang.InternalError: Thread starting during runtime shutdown
> 	at java.lang.Thread.nativeCreate(Native Method)
> 	 at java.lang.Thread.start(Thread.java:1063)
> 	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:920)
> 	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1336)
> 	at com.android.okhttp.ConnectionPool.scheduleCleanupAsRequired(ConnectionPool.java:367)
> 	at com.android.okhttp.ConnectionPool.get(ConnectionPool.java:265)
> 	at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:109)
> 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:272)
> 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:211)
> 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:382)
> 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:106)
> 	at org.acra.util.HttpRequest.send(SourceFile:123)
> 	at org.acra.sender.HttpSender.send(SourceFile:245)
> 	at org.acra.SendWorker.sendCrashReport(SourceFile:181)
> 	at org.acra.SendWorker.checkAndSendReports(SourceFile:140)
> 	at org.acra.SendWorker.run(SourceFile:76)

**Comment by Ph1b** [comment]
Please re-open this, same crash:

> java.lang.InternalError: Thread starting during runtime shutdown
	at java.lang.Thread.nativeCreate(Native Method)
	at java.lang.Thread.start(Thread.java:1063)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:920)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1336)
	at com.android.okhttp.ConnectionPool.get(ConnectionPool.java:206)
	at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:109)
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:272)
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:211)
	at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:373)
	at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:106)
	at org.acra.util.HttpRequest.send(HttpRequest.java:122)
	at org.acra.sender.HttpSender.send(HttpSender.java:245)
	at org.acra.SendWorker.sendCrashReport(SendWorker.java:181)
	at org.acra.SendWorker.checkAndSendReports(SendWorker.java:140)
	at org.acra.SendWorker.run(SendWorker.java:76)

**Comment by william-ferguson-au** [comment]
It is not the same crash as the original issue.
