### ISSUE TITLE
ACRA doesn't support SSL SNI

### ISSUE THREAD

**Issue by Crazyphil** [ACRA/acra#164]
Android's built-in HttpClient implementation doesn't support SNI (Server Name Indication) in versions <4.2 and has to be explicitly enabled in more recent versions, which means that if your ACRA report collection service is running HTTPS on a shared IP address, sending the bug report will fail with the exception cited below.

Because the submission form might use credentials, it's a good idea not to disclose them to third parties through using insecure connections. [This blog post](http://blog.dev001.net/post/67082904181/android-using-sni-and-tlsv1-2-with-apache-httpclient) shows how SNI can be enabled on any Android version down to 2.3.
The change proposed in pull request #141 is a first step, but in my opinion, a SNI-aware SocketFactory should be the default.

```
    org.acra.sender.ReportSenderException: Error while sending FORM report via Http POST
            at org.acra.sender.HttpSender.send(HttpSender.java:228)
            at org.acra.SendWorker.sendCrashReport(SendWorker.java:179)
            at org.acra.SendWorker.checkAndSendReports(SendWorker.java:141)
            at org.acra.SendWorker.run(SendWorker.java:77)
     Caused by: javax.net.ssl.SSLException: hostname in certificate didn't match: <myacra.example.com> != <mainsslserver.example.com>
            at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:185)
            at org.apache.http.conn.ssl.BrowserCompatHostnameVerifier.verify(BrowserCompatHostnameVerifier.java:54)
            at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:114)
            at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:95)
            at org.apache.http.conn.ssl.SSLSocketFactory.createSocket(SSLSocketFactory.java:381)
            at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:165)
            at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:164)
            at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:119)
            at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:360)
            at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555)
            at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487)
            at org.acra.util.HttpRequest.send(HttpRequest.java:152)
            at org.acra.sender.HttpSender.send(HttpSender.java:225)
            at org.acra.SendWorker.sendCrashReport(SendWorker.java:179)
            at org.acra.SendWorker.checkAndSendReports(SendWorker.java:141)
            at org.acra.SendWorker.run(SendWorker.java:77)
```

**Comment by Crazyphil** [comment]
Implemented in PR #221
