### ISSUE TITLE
ACRA.init(this) has error 

### ISSUE THREAD

**Issue by chintan90** [ACRA/acra#220]
i am developing one app called nomino. it is already made app and i am trying to run this app for check how it works but when i try to run it i am getting this error in android log-cat. you will find error below.

java.lang.NoClassDefFoundError: org.acra.ACRA
at com.ten5studios.nomino.Nomino.onCreate(Nomino.java:16)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4344)
at android.app.ActivityThread.access$1500(ActivityThread.java:135)
at android.app.ActivityThread.access$1500(ActivityThread.java:135)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5017)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
at dalvik.system.NativeStart.main(Native Method)

**Comment by william-ferguson-au** [comment]
This means that ACRA is not in your APK at runtime.
Make sure you have included the library and that you are not excluding the
classes using Proguard.
ᐧ

**Comment by chintan90** [comment]
i have included ACRA.jar as a external library and all errors of ACRA also gone. But still i am getting this error.

**Comment by william-ferguson-au** [comment]
As I said, it means that ACRA is not in your APK at runtime.
You have not correctly included the ACRA library.

**Comment by chintan90** [comment]
Can you send me the link of the ACRA library?

**Comment by william-ferguson-au** [comment]
You can download from Maven Central at
http://mvnrepository.com/artifact/ch.acra/acra/4.6.0RC1
ᐧ
