### ISSUE TITLE
Is there a way of getting a dump of local variables in the top 1-2 functions in the stack trace?

### ISSUE THREAD

**Issue by somghosh** [ACRA/acra#226]
As of now I just get the below stack trace along with system wide variables, but I would also want to get the various variable dump in the onPostNetworkRequest() at the top of the stack so that I know which variable in that line was null. How can I do this?

	java.lang.NullPointerException
	at com.gmspartners.earthmiles.views.mainthreetabs.mefragment.MeFragment$3.onPostNetworkRequest(MeFragment.java:267)
	at com.gmspartners.earthmiles.globalstate.App$6.failure(App.java:772)
	at retrofit.CallbackRunnable$2.run(CallbackRunnable.java:53)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5586)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by william-ferguson-au** [comment]
Not in any generic way.

If you have many variables that could be throwing an NPE on a single line
then it smells like a need to refactor.


ᐧ

**Comment by KevinGaudin** [comment]
You can only explicitly track some variables values by adding their
name+values to the report's custom data.

Le jeu. 22 janv. 2015 12:52, William Ferguson <notifications@github.com> a
écrit :
