### ISSUE TITLE
Dialog doesn't show up if exception occurs in Application class before main activity is created

### ISSUE THREAD

**Issue by camerr** [ACRA/acra#270]
In this case report is not send either, because user can not confirm dialog. I'm using version 4.6.2.

I have following annotation on Application class:
@ReportsCrashes(
        mode = ReportingInteractionMode.DIALOG,
        resDialogText = R.string.crash_dialog_text,
        resDialogTitle = R.string.crash_dialog_title,
        resDialogCommentPrompt = R.string.crash_dialog_comment_prompt
)

And onCreate snippet:
    @Override
    public void onCreate() {
        ACRA.init(this);
        JiraAcraReportSender jiraAcraReportSender = new JiraAcraReportSender();
        ACRA.getErrorReporter().setReportSender(jiraAcraReportSender);

        super.onCreate();
...

And stack trace for database downgrade exception:

05-06 14:47:54.752    8345-8345/si.microgramm.simpos.lite D/ACRA﹕ ACRA is enabled for si.microgramm.simpos.lite, initializing...
05-06 14:47:54.752    8345-8345/si.microgramm.simpos.lite D/ACRA﹕ Using default Report Fields
05-06 14:47:54.772    8345-8345/si.microgramm.simpos.lite D/ACRA﹕ Looking for error files in /data/data/si.microgramm.simpos.lite/files
05-06 14:47:54.772    8345-8345/si.microgramm.simpos.lite D/ACRA﹕ Deleting file 1430916420000.stacktrace
05-06 14:47:54.772    8345-8345/si.microgramm.simpos.lite D/ACRA﹕ Looking for error files in /data/data/si.microgramm.simpos.lite/files
05-06 14:47:54.792    8345-8345/si.microgramm.simpos.lite D/AndroidRuntime﹕ Shutting down VM
05-06 14:47:54.792    8345-8345/si.microgramm.simpos.lite W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0x40c6c300)
05-06 14:47:54.792    8345-8345/si.microgramm.simpos.lite E/ACRA﹕ ACRA caught a RuntimeException for si.microgramm.simpos.lite
    java.lang.RuntimeException: Unable to create application si.microgramm.simpos.lite.SimposLiteApplication: android.database.sqlite.SQLiteException: Can't downgrade database from version 37 to 36
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4154)
            at android.app.ActivityThread.access$1300(ActivityThread.java:130)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1255)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4745)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: android.database.sqlite.SQLiteException: Can't downgrade database from version 37 to 36
            at android.database.sqlite.SQLiteOpenHelper.onDowngrade(SQLiteOpenHelper.java:361)
            at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:255)
            at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:164)
            at si.microgramm.android.commons.db.DatabaseHelper.getWritableDatabase(DatabaseHelper.java:71)
            at si.microgramm.android.commons.db.SqlLiteEntityManager.<init>(SqlLiteEntityManager.java:27)
            at si.microgramm.android.commons.db.CachedEntityManager.<init>(CachedEntityManager.java:14)
            at si.microgramm.simpos.client.android.db.PosSettingsEntityManager.<init>(PosSettingsEntityManager.java:41)
            at si.microgramm.simpos.client.android.db.PosSettingsEntityManager.<init>(PosSettingsEntityManager.java:37)
            at si.microgramm.simpos.client.android.lite.LocaleProvider.getLocale(LocaleProvider.java:16)
            at si.microgramm.simpos.lite.SimposLiteApplication.onCreate(SimposLiteApplication.java:55)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:999)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4151)
            at android.app.ActivityThread.access$1300(ActivityThread.java:130)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1255)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4745)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
            at dalvik.system.NativeStart.main(Native Method)
05-06 14:47:54.792    8345-8345/si.microgramm.simpos.lite D/ACRA﹕ Building report
05-06 14:47:54.792    8345-8345/si.microgramm.simpos.lite D/ACRA﹕ Using default Report Fields
05-06 14:47:54.802    8345-8348/si.microgramm.simpos.lite D/dalvikvm﹕ GC_CONCURRENT freed 330K, 19% free 5516K/6791K, paused 1ms+1ms, total 14ms
05-06 14:47:54.802    8345-8345/si.microgramm.simpos.lite D/dalvikvm﹕ WAIT_FOR_CONCURRENT_GC blocked 7ms
05-06 14:47:54.952    8345-8348/si.microgramm.simpos.lite D/dalvikvm﹕ GC_CONCURRENT freed 318K, 20% free 5594K/6919K, paused 11ms+2ms, total 22ms

If mode is changed to TOAST, it works OK.

**Comment by william-ferguson-au** [comment]
If you'd like to check out branch https://github.com/ACRA/acra/tree/issue_270, build it, integrrate it into your project and post the log it should have enough extra log info to determine whta is going on.

**Comment by camerr** [comment]
Of course. Here you go.

05-07 13:53:24.412  26161-26161/si.microgramm.simpos.lite D/ACRA﹕ ACRA is enabled for si.microgramm.simpos.lite, initializing...
05-07 13:53:24.412  26161-26161/si.microgramm.simpos.lite D/ACRA﹕ Using default Report Fields
05-07 13:53:24.432  26161-26161/si.microgramm.simpos.lite D/ACRA﹕ Looking for error files in /data/data/si.microgramm.simpos.lite/files
05-07 13:53:24.432  26161-26161/si.microgramm.simpos.lite D/ACRA﹕ Looking for error files in /data/data/si.microgramm.simpos.lite/files
05-07 13:53:24.452  26161-26161/si.microgramm.simpos.lite D/AndroidRuntime﹕ Shutting down VM
05-07 13:53:24.452  26161-26161/si.microgramm.simpos.lite W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0x40c6c300)
05-07 13:53:24.472  26161-26161/si.microgramm.simpos.lite E/ACRA﹕ ACRA caught a RuntimeException for si.microgramm.simpos.lite
    java.lang.RuntimeException: Unable to create application si.microgramm.simpos.lite.SimposLiteApplication: android.database.sqlite.SQLiteException: Can't downgrade database from version 37 to 36
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4154)
            at android.app.ActivityThread.access$1300(ActivityThread.java:130)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1255)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4745)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: android.database.sqlite.SQLiteException: Can't downgrade database from version 37 to 36
            at android.database.sqlite.SQLiteOpenHelper.onDowngrade(SQLiteOpenHelper.java:361)
            at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:255)
            at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:164)
            at si.microgramm.android.commons.db.DatabaseHelper.getWritableDatabase(DatabaseHelper.java:71)
            at si.microgramm.android.commons.db.SqlLiteEntityManager.<init>(SqlLiteEntityManager.java:27)
            at si.microgramm.android.commons.db.CachedEntityManager.<init>(CachedEntityManager.java:14)
            at si.microgramm.simpos.client.android.db.PosSettingsEntityManager.<init>(PosSettingsEntityManager.java:41)
            at si.microgramm.simpos.client.android.db.PosSettingsEntityManager.<init>(PosSettingsEntityManager.java:37)
            at si.microgramm.simpos.client.android.lite.LocaleProvider.getLocale(LocaleProvider.java:16)
            at si.microgramm.simpos.lite.SimposLiteApplication.onCreate(SimposLiteApplication.java:55)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:999)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4151)
            at android.app.ActivityThread.access$1300(ActivityThread.java:130)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1255)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4745)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
            at dalvik.system.NativeStart.main(Native Method)
05-07 13:53:24.472  26161-26161/si.microgramm.simpos.lite D/ACRA﹕ Building report
05-07 13:53:24.472  26161-26161/si.microgramm.simpos.lite D/ACRA﹕ reportingInteractionMode=DIALOG shouldDisplayToast=false alwaysAcceptsReports=false reportBuilder#mEndsApplicationtrue
05-07 13:53:24.472  26161-26161/si.microgramm.simpos.lite D/ACRA﹕ Using default Report Fields
05-07 13:53:24.482  26161-26165/si.microgramm.simpos.lite D/dalvikvm﹕ GC_CONCURRENT freed 322K, 19% free 5517K/6791K, paused 13ms+4ms, total 29ms
05-07 13:53:24.482  26161-26161/si.microgramm.simpos.lite D/dalvikvm﹕ WAIT_FOR_CONCURRENT_GC blocked 6ms
05-07 13:53:24.692  26161-26165/si.microgramm.simpos.lite D/dalvikvm﹕ GC_CONCURRENT freed 333K, 20% free 5598K/6919K, paused 12ms+1ms, total 30ms
05-07 13:53:24.802  26161-26161/si.microgramm.simpos.lite I/ACRA﹕ READ_LOGS granted! ACRA can include LogCat and DropBox data.
05-07 13:53:24.822  26161-26161/si.microgramm.simpos.lite D/ACRA﹕ Retrieving logcat output...
05-07 13:53:24.832  26161-26165/si.microgramm.simpos.lite D/dalvikvm﹕ GC_CONCURRENT freed 511K, 22% free 5608K/7111K, paused 2ms+3ms, total 36ms
05-07 13:53:24.862  26161-26161/si.microgramm.simpos.lite D/ACRA﹕ Writing crash report file 1430999604000.stacktrace.
05-07 13:53:24.892  26161-26165/si.microgramm.simpos.lite D/dalvikvm﹕ GC_CONCURRENT freed 402K, 21% free 5680K/7111K, paused 12ms+3ms, total 36ms
05-07 13:53:24.892  26161-26161/si.microgramm.simpos.lite D/dalvikvm﹕ WAIT_FOR_CONCURRENT_GC blocked 14ms
05-07 13:53:24.922  26161-26161/si.microgramm.simpos.lite D/dalvikvm﹕ GC_FOR_ALLOC freed 139K, 22% free 5644K/7175K, paused 15ms, total 15ms
05-07 13:53:24.932  26161-26179/si.microgramm.simpos.lite D/ACRA﹕ Waiting for Toast
05-07 13:53:24.932  26161-26179/si.microgramm.simpos.lite D/ACRA﹕ Finished waiting for Toast
05-07 13:53:24.932  26161-26179/si.microgramm.simpos.lite D/ACRA﹕ Creating CrashReportDialog for 1430999604000.stacktrace
05-07 13:53:24.932  26161-26179/si.microgramm.simpos.lite D/ACRA﹕ Creating DialogIntent for 1430999604000.stacktrace exception=java.lang.RuntimeException: Unable to create application si.microgramm.simpos.lite.SimposLiteApplication: android.database.sqlite.SQLiteException: Can't downgrade database from version 37 to 36

**Comment by william-ferguson-au** [comment]
Cool. So we can see that it is getting to https://github.com/ACRA/acra/blob/issue_270/src/main/java/org/acra/ErrorReporter.java#L848

Starting the dialog Activity in a new Task (ie new application) at https://github.com/ACRA/acra/blob/issue_270/src/main/java/org/acra/ErrorReporter.java#L851

But I don't see log for https://github.com/ACRA/acra/blob/issue_270/src/main/java/org/acra/ErrorReporter.java#L854

So I would expect to see a dialog and then the log from line 854

**Comment by camerr** [comment]
You don't see log for L854 because I've pasted filtered log - sorry. This one shows more.
https://gist.github.com/camerr/c642962f3150503fb2a4

I've also noticed that exception occurs 2 times in row. When I deploy app on different, faster Android 5.0 device even 3 times (without manually restarting app).

**Comment by camerr** [comment]
Log with newest ErrorReporter class.
https://gist.github.com/camerr/02e15c483e90ce65b300

**Comment by william-ferguson-au** [comment]
OK, what's happening is that because your app is crashing in the Application#onCreate itself there is no way for th dialog to be shown as the dialog creates a brand new (separate instance) of your application so that the crashing instance can expire.

But starting the new instance itself causes a crash.

You should really try and make your Application startup be bullet proof.
The alternate is to use another notification mechanism than dialog which can be accomplished within the dying instance.

**Comment by camerr** [comment]
Exception was produced when I accidentally run some old branch on newest database from my IDE. It is really not an issue for us. I just thought you might be interested in because in some way it is a bug, because it does not happen what is expected.

Now, when I know how you show dialog, I agree that situations like this can not be covered using dialog unless you find completely different approach (or not) :)
