### ISSUE TITLE
Error while retrieving Media crash data

### ISSUE THREAD

**Issue by jarofgreen** [ACRA/acra#273]
Android 4.4.4

05-26 10:40:13.106  27314-27314/org.brokenopenapp.acratest E/ACRA﹕ Error while retrieving crash data
    java.lang.NullPointerException
            at org.acra.collector.MediaCodecListCollector.collectCapabilitiesForType(MediaCodecListCollector.java:216)
            at org.acra.collector.MediaCodecListCollector.collecMediaCodecList(MediaCodecListCollector.java:155)
            at org.acra.collector.CrashReportDataFactory.createCrashData(CrashReportDataFactory.java:350)
            at org.acra.ErrorReporter.report(ErrorReporter.java:741)
            at org.acra.ErrorReporter.access$1400(ErrorReporter.java:82)
            at org.acra.ErrorReporter$ReportBuilder.send(ErrorReporter.java:1131)
            at org.acra.ErrorReporter.handleException(ErrorReporter.java:646)
            at org.brokenopenapp.acratest.MainActivity.crashRuntimeException(MainActivity.java:38)
            at org.brokenopenapp.acratest.MainActivity.onClickCrash1(MainActivity.java:21)

**Comment by william-ferguson-au** [comment]
I believe this branch solves your issue.
Could you please check it out, build it and confirm.

https://github.com/ACRA/acra/tree/issue-273

**Comment by jarofgreen** [comment]
Yes, thanks! Nexus 7, Android 4.4.4:

```

0: OMX.Nvidia.mp4.decode
isEncoder: false
Supported types: [video/mp4v-es]
video/mp4v-es color formats:COLOR_FormatYUV420Planar
video/mp4v-es profile levels:MPEG4ProfileSimple-MPEG4Level5,MPEG4ProfileAdvancedSimple-MPEG4Level5



1: OMX.Nvidia.h263.decode
isEncoder: false
Supported types: [video/3gpp]
video/3gpp color formats:COLOR_FormatYUV420Planar
video/3gpp profile levels:H263ProfileBaseline-H263Level50



2: OMX.Nvidia.h264.decode
isEncoder: false
Supported types: [video/avc]
video/avc color formats:COLOR_FormatYUV420Planar
video/avc profile levels:1AVCProfileBaseline-AVCLevel41,2AVCProfileMain-AVCLevel41,8AVCProfileHigh-AVCLevel41



3: OMX.Nvidia.mpeg2v.decode
isEncoder: false
Supported types: [video/mpeg2]
video/mpeg2 color formats:COLOR_FormatYUV420Planar
video/mpeg2 profile levels:0-1



4: OMX.Nvidia.mp2.decoder
isEncoder: false
Supported types: [audio/mpeg-L2]



5: OMX.google.mp3.decoder
isEncoder: false
Supported types: [audio/mpeg]



6: OMX.google.amrnb.decoder
isEncoder: false
Supported types: [audio/3gpp]



7: OMX.google.amrwb.decoder
isEncoder: false
Supported types: [audio/amr-wb]



8: OMX.google.aac.decoder
isEncoder: false
Supported types: [audio/mp4a-latm]



9: OMX.google.g711.alaw.decoder
isEncoder: false
Supported types: [audio/g711-alaw]



10: OMX.google.g711.mlaw.decoder
isEncoder: false
Supported types: [audio/g711-mlaw]



11: OMX.google.vorbis.decoder
isEncoder: false
Supported types: [audio/vorbis]



12: OMX.google.gsm.decoder
isEncoder: false
Supported types: [audio/gsm]



13: OMX.google.mpeg4.decoder
isEncoder: false
Supported types: [video/mp4v-es]
video/mp4v-es color formats:COLOR_FormatYUV420Planar



14: OMX.google.h263.decoder
isEncoder: false
Supported types: [video/3gpp]
video/3gpp color formats:COLOR_FormatYUV420Planar



15: OMX.google.h264.decoder
isEncoder: false
Supported types: [video/avc]
video/avc color formats:COLOR_FormatYUV420Planar



16: OMX.google.vp8.decoder
isEncoder: false
Supported types: [video/x-vnd.on2.vp8]
video/x-vnd.on2.vp8 color formats:COLOR_FormatYUV420Planar



17: OMX.google.vp9.decoder
isEncoder: false
Supported types: [video/x-vnd.on2.vp9]
video/x-vnd.on2.vp9 color formats:COLOR_FormatYUV420Planar



18: OMX.Nvidia.mp4.encoder
isEncoder: true
Supported types: [video/mp4v-es]
video/mp4v-es color formats:COLOR_FormatYUV420Planar,COLOR_FormatSurface
video/mp4v-es profile levels:MPEG4ProfileSimple-MPEG4Level5



19: OMX.Nvidia.h263.encoder
isEncoder: true
Supported types: [video/3gpp]
video/3gpp color formats:COLOR_FormatYUV420Planar,COLOR_FormatSurface
video/3gpp profile levels:H263ProfileBaseline-H263Level60



20: OMX.Nvidia.h264.encoder
isEncoder: true
Supported types: [video/avc]
video/avc color formats:COLOR_FormatYUV420Planar,COLOR_FormatSurface
video/avc profile levels:1AVCProfileBaseline-AVCLevel41



21: OMX.google.amrnb.encoder
isEncoder: true
Supported types: [audio/3gpp]



22: OMX.google.amrwb.encoder
isEncoder: true
Supported types: [audio/amr-wb]



23: OMX.google.aac.encoder
isEncoder: true
Supported types: [audio/mp4a-latm]



24: OMX.google.flac.encoder
isEncoder: true
Supported types: [audio/flac]



25: OMX.google.vp8.encoder
isEncoder: true
Supported types: [video/x-vnd.on2.vp8]
video/x-vnd.on2.vp8 color formats:COLOR_FormatYUV420Planar,COLOR_FormatYUV420SemiPlanar,COLOR_FormatSurface
video/x-vnd.on2.vp8 profile levels:1-1



26: AACEncoder
isEncoder: true
Supported types: [audio/mp4a-latm]



27: OMX.google.raw.decoder
isEncoder: false
Supported types: [audio/raw]

```

**Comment by william-ferguson-au** [comment]
Merged
