### ISSUE TITLE
formkey error

### ISSUE THREAD

**Issue by noog** [ACRA/acra#282]
hello
i have imported acra 4.6.2 in eclipse
i added acra to the build path (right click)
but i have this error 

The attribute formKey is undefined for the annotation type ReportsCrashes

if i remove formKey the application lanch but acra don't works

can you help me ?

thanks

**Comment by william-ferguson-au** [comment]
formKey has been delegated for 2 years and was removed in 4.6

Post your ACRA configuration including your formkey attribute.

William

**Comment by an-arhos** [comment]
Hi,
I have the same issue.

This is my annotation
@ReportsCrashes(
//	    formKey = "", // This is required for backward compatibility but not used
//	    formUri = "http://www.backendofyourchoice.com/reportpath"
		mailTo = "mail@gmail.com"
		//,
  //      mode = ReportingInteractionMode.TOAST,
  //      resToastText = R.string.crash_toast_text
	)

I added acra to build path, allowed internet connection,
but acra does not innitiate.

I need help.
Thanks.

**Comment by william-ferguson-au** [comment]
You have configured ACRA to send mail on a crash.
What do you mean ACRA does not initiate?
What symptoms are you seeing?

**Comment by an-arhos** [comment]
I don't get any mail on crash.
In log cat there is nothing about acra.

**Comment by milesich** [comment]
I think you forgot the actual init part `ACRA.init(this);` You can read more about it here https://github.com/ACRA/acra/wiki/BasicSetup

**Comment by an-arhos** [comment]
Thank you for your replay, but as I wrote in my first post i have init part in my OnCreate method.

**Comment by william-ferguson-au** [comment]
You won't get mail sent in the background from a crash as that is not possible with Android. You should get your mail app opened with some prefilled fields about the crash that the user can then send to you.

Show the code in which you are testing the crash.
Show the logcat.

**Comment by an-arhos** [comment]
I am intentionally creating exeption
```java
String pri="1234";
String kad=pri.substring(0,pri.indexOf("kako"));
```
and this is my logcat
```java
08-28 13:33:08.310: I/System.out(30086): Debugger has connected
08-28 13:33:08.310: I/System.out(30086): waiting for debugger to settle...
08-28 13:33:08.510: I/System.out(30086): waiting for debugger to settle...
08-28 13:33:08.701: I/System.out(30086): waiting for debugger to settle...
08-28 13:33:08.901: I/System.out(30086): waiting for debugger to settle...
08-28 13:33:09.101: I/System.out(30086): waiting for debugger to settle...
08-28 13:33:09.301: I/System.out(30086): waiting for debugger to settle...
08-28 13:33:09.501: I/System.out(30086): waiting for debugger to settle...
08-28 13:33:09.702: I/System.out(30086): waiting for debugger to settle...
08-28 13:33:09.902: I/System.out(30086): waiting for debugger to settle...
08-28 13:33:10.102: I/System.out(30086): waiting for debugger to settle...
08-28 13:33:10.302: I/System.out(30086): waiting for debugger to settle...
08-28 13:33:10.502: I/System.out(30086): waiting for debugger to settle...
08-28 13:33:10.703: I/System.out(30086): waiting for debugger to settle...
08-28 13:33:10.903: I/System.out(30086): waiting for debugger to settle...
08-28 13:33:11.103: I/System.out(30086): waiting for debugger to settle...
08-28 13:33:11.303: I/System.out(30086): waiting for debugger to settle...
08-28 13:33:11.503: I/System.out(30086): waiting for debugger to settle...
08-28 13:33:11.704: I/System.out(30086): waiting for debugger to settle...
08-28 13:33:11.914: I/System.out(30086): debugger has settled (1382)
08-28 13:33:21.603: W/dalvikvm(30086): threadid=1: thread exiting with uncaught exception (group=0x40e34390)
08-28 13:33:21.653: E/AndroidRuntime(30086): FATAL EXCEPTION: main
08-28 13:33:21.653: E/AndroidRuntime(30086): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.anonce/com.example.anonce.oglasi}: java.lang.StringIndexOutOfBoundsException: length=4; regionStart=0; regionLength=-1
08-28 13:33:21.653: E/AndroidRuntime(30086): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2355)
08-28 13:33:21.653: E/AndroidRuntime(30086): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2391)
08-28 13:33:21.653: E/AndroidRuntime(30086): 	at android.app.ActivityThread.access$600(ActivityThread.java:151)
08-28 13:33:21.653: E/AndroidRuntime(30086): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1335)
08-28 13:33:21.653: E/AndroidRuntime(30086): 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-28 13:33:21.653: E/AndroidRuntime(30086): 	at android.os.Looper.loop(Looper.java:155)
08-28 13:33:21.653: E/AndroidRuntime(30086): 	at android.app.ActivityThread.main(ActivityThread.java:5511)
08-28 13:33:21.653: E/AndroidRuntime(30086): 	at java.lang.reflect.Method.invokeNative(Native Method)
08-28 13:33:21.653: E/AndroidRuntime(30086): 	at java.lang.reflect.Method.invoke(Method.java:511)
08-28 13:33:21.653: E/AndroidRuntime(30086): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029)
08-28 13:33:21.653: E/AndroidRuntime(30086): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:796)
08-28 13:33:21.653: E/AndroidRuntime(30086): 	at dalvik.system.NativeStart.main(Native Method)
08-28 13:33:21.653: E/AndroidRuntime(30086): Caused by: java.lang.StringIndexOutOfBoundsException: length=4; regionStart=0; regionLength=-1
08-28 13:33:21.653: E/AndroidRuntime(30086): 	at java.lang.String.startEndAndLength(String.java:593)
08-28 13:33:21.653: E/AndroidRuntime(30086): 	at java.lang.String.substring(String.java:1474)
08-28 13:33:21.653: E/AndroidRuntime(30086): 	at com.example.anonce.njuskalo.onGetResult(njuskalo.java:86)
08-28 13:33:21.653: E/AndroidRuntime(30086): 	at com.example.anonce.njuskalo.<init>(njuskalo.java:69)
08-28 13:33:21.653: E/AndroidRuntime(30086): 	at com.example.anonce.oglasi.onCreate(oglasi.java:77)
08-28 13:33:21.653: E/AndroidRuntime(30086): 	at android.app.Activity.performCreate(Activity.java:5066)
08-28 13:33:21.653: E/AndroidRuntime(30086): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1101)
08-28 13:33:21.653: E/AndroidRuntime(30086): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2311)
08-28 13:33:21.653: E/AndroidRuntime(30086): 	... 11 more
08-28 13:33:21.733: D/Process(30086): killProcess, pid=30086
08-28 13:33:21.733: D/Process(30086): dalvik.system.VMStack.getThreadStackTrace(Native Method)
08-28 13:33:21.733: D/Process(30086): java.lang.Thread.getStackTrace(Thread.java:599)
08-28 13:33:21.733: D/Process(30086): android.os.Process.killProcess(Process.java:951)
08-28 13:33:21.733: D/Process(30086): com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:108)
08-28 13:33:21.743: D/Process(30086): java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
08-28 13:33:21.743: D/Process(30086): java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
08-28 13:33:21.743: D/Process(30086): dalvik.system.NativeStart.main(Native Method)

```

**Comment by william-ferguson-au** [comment]
Show your Application class and show the log from when your app strats up because it doesn't look like ACRA has been initialised.

**Comment by an-arhos** [comment]
This is my app class
```java
package com.example.anonce;

import java.io.File;

import org.acra.*;
import org.acra.annotation.*;

import android.app.Application;
import android.content.Context;
import android.content.ContextWrapper;
import android.content.Intent;
import android.database.sqlite.SQLiteDatabase;
import anonce.ProdajaDataSource;

@ReportsCrashes(
//	    formKey = "", // This is required for backward compatibility but not used
//	    formUri = "http://www.backendofyourchoice.com/reportpath"
		mailTo = "mistikmm@gmail.com"
		,
//        mode = ReportingInteractionMode.TOAST,
//        resToastText = R.string.crash_toast_text
	)

public class anonce extends Application {
	
	static final String dbName="anonce";
	Context context = this;
	private ProdajaDataSource datasource;
	String res;
	SQLiteDatabase db= null;
	
	String dana="30";
	
	oglasi oglasi;
	HelpActivity hact;

	@Override
	public void onCreate() {
		super.onCreate();
				
		//The following line triggers the initialization of ACRA
		ACRA.init(this);
		
		Intent intent;
		
if(!checkDataBase(this))
		{
			   datasource = new ProdajaDataSource(this);
			    db=datasource.open();
			    intent = new Intent(this, HelpActivity.class);
				intent.putExtra("prv","1"); 
		}
else
		{
			db = SQLiteDatabase.openDatabase(this.getDatabasePath(dbName).getAbsolutePath(),null,SQLiteDatabase.OPEN_READWRITE);
			intent = new Intent(this, oglasi.class);
			
		}


startActivity(intent);
		
	}
	
	private boolean checkDataBase(ContextWrapper context) {
		File dbFile = context.getDatabasePath(dbName);
	    return dbFile.exists();
}

}	

```

and the log above is log from the start.

**Comment by william-ferguson-au** [comment]
The log above is **not** from the start of your app.
It is only from when you connected a debugger to your already running app.

**Comment by an-arhos** [comment]
I updated my post.
This is all I get.

**Comment by william-ferguson-au** [comment]
Post your AndroidManifest.
Add some log to the start of your `Application.onCreate()` and capture the log again.
It doens't look like your Application class is being called.

**Comment by an-arhos** [comment]
I added
		Log.w(dbName, "no network");
before
		super.onCreate();
and got this

```java
08-30 10:57:08.070: E/Trace(17646): error opening trace file: No such file or directory (2)
08-30 10:57:08.090: W/ActivityThread(17646): Application com.example.anonce is waiting for the debugger on port 8100...
08-30 10:57:08.101: I/System.out(17646): Sending WAIT chunk
08-30 10:57:08.311: I/System.out(17646): Debugger has connected
08-30 10:57:08.311: I/System.out(17646): waiting for debugger to settle...
08-30 10:57:08.511: I/System.out(17646): waiting for debugger to settle...
08-30 10:57:08.711: I/System.out(17646): waiting for debugger to settle...
08-30 10:57:08.921: I/System.out(17646): waiting for debugger to settle...
08-30 10:57:09.121: I/System.out(17646): waiting for debugger to settle...
08-30 10:57:09.332: I/System.out(17646): waiting for debugger to settle...
08-30 10:57:09.532: I/System.out(17646): waiting for debugger to settle...
08-30 10:57:09.732: I/System.out(17646): waiting for debugger to settle...
08-30 10:57:09.932: I/System.out(17646): waiting for debugger to settle...
08-30 10:57:10.132: I/System.out(17646): waiting for debugger to settle...
08-30 10:57:10.343: I/System.out(17646): waiting for debugger to settle...
08-30 10:57:10.543: I/System.out(17646): waiting for debugger to settle...
08-30 10:57:10.743: I/System.out(17646): waiting for debugger to settle...
08-30 10:57:10.943: I/System.out(17646): waiting for debugger to settle...
08-30 10:57:11.143: I/System.out(17646): waiting for debugger to settle...
08-30 10:57:11.344: I/System.out(17646): waiting for debugger to settle...
08-30 10:57:11.544: I/System.out(17646): waiting for debugger to settle...
08-30 10:57:11.744: I/System.out(17646): waiting for debugger to settle...
08-30 10:57:11.944: I/System.out(17646): waiting for debugger to settle...
08-30 10:57:12.144: I/System.out(17646): debugger has settled (1325)
08-30 10:57:18.781: W/dalvikvm(17646): threadid=1: thread exiting with uncaught exception (group=0x40e34390)
08-30 10:57:18.851: E/AndroidRuntime(17646): FATAL EXCEPTION: main
08-30 10:57:18.851: E/AndroidRuntime(17646): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.anonce/com.example.anonce.oglasi}: java.lang.StringIndexOutOfBoundsException: length=4; regionStart=0; regionLength=-1
08-30 10:57:18.851: E/AndroidRuntime(17646): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2355)
08-30 10:57:18.851: E/AndroidRuntime(17646): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2391)
08-30 10:57:18.851: E/AndroidRuntime(17646): 	at android.app.ActivityThread.access$600(ActivityThread.java:151)
08-30 10:57:18.851: E/AndroidRuntime(17646): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1335)
08-30 10:57:18.851: E/AndroidRuntime(17646): 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-30 10:57:18.851: E/AndroidRuntime(17646): 	at android.os.Looper.loop(Looper.java:155)
08-30 10:57:18.851: E/AndroidRuntime(17646): 	at android.app.ActivityThread.main(ActivityThread.java:5511)
08-30 10:57:18.851: E/AndroidRuntime(17646): 	at java.lang.reflect.Method.invokeNative(Native Method)
08-30 10:57:18.851: E/AndroidRuntime(17646): 	at java.lang.reflect.Method.invoke(Method.java:511)
08-30 10:57:18.851: E/AndroidRuntime(17646): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029)
08-30 10:57:18.851: E/AndroidRuntime(17646): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:796)
08-30 10:57:18.851: E/AndroidRuntime(17646): 	at dalvik.system.NativeStart.main(Native Method)
08-30 10:57:18.851: E/AndroidRuntime(17646): Caused by: java.lang.StringIndexOutOfBoundsException: length=4; regionStart=0; regionLength=-1
08-30 10:57:18.851: E/AndroidRuntime(17646): 	at java.lang.String.startEndAndLength(String.java:593)
08-30 10:57:18.851: E/AndroidRuntime(17646): 	at java.lang.String.substring(String.java:1474)
08-30 10:57:18.851: E/AndroidRuntime(17646): 	at com.example.anonce.njuskalo.onGetResult(njuskalo.java:86)
08-30 10:57:18.851: E/AndroidRuntime(17646): 	at com.example.anonce.njuskalo.<init>(njuskalo.java:69)
08-30 10:57:18.851: E/AndroidRuntime(17646): 	at com.example.anonce.oglasi.onCreate(oglasi.java:77)
08-30 10:57:18.851: E/AndroidRuntime(17646): 	at android.app.Activity.performCreate(Activity.java:5066)
08-30 10:57:18.851: E/AndroidRuntime(17646): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1101)
08-30 10:57:18.851: E/AndroidRuntime(17646): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2311)
08-30 10:57:18.851: E/AndroidRuntime(17646): 	... 11 more
08-30 10:57:18.931: D/Process(17646): killProcess, pid=17646
08-30 10:57:18.931: D/Process(17646): dalvik.system.VMStack.getThreadStackTrace(Native Method)
08-30 10:57:18.931: D/Process(17646): java.lang.Thread.getStackTrace(Thread.java:599)
08-30 10:57:18.931: D/Process(17646): android.os.Process.killProcess(Process.java:951)
08-30 10:57:18.931: D/Process(17646): com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:108)
08-30 10:57:18.931: D/Process(17646): java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
08-30 10:57:18.931: D/Process(17646): java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
08-30 10:57:18.931: D/Process(17646): dalvik.system.NativeStart.main(Native Method)
```
and here is manifest
```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.anonce"
    android:versionCode="1"
    android:versionName="1.0" >
    
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
           <uses-permission android:name="android.permission.READ_LOGS" />
        <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_INTERNAL_STORAGE" />

    <uses-sdk
        android:minSdkVersion="14"
        android:targetSdkVersion="22" />

    
    <application
        android:allowBackup="true"
        android:icon="@drawable/ic_launcher"
        android:label="anonce"
        android:theme="@style/CustomTheme" >
        <activity
            android:name=".HelpActivity"
            android:label="anonce"
            android:configChanges="orientation|keyboardHidden|screenSize" >
 
        </activity>

        <activity
            android:name=".oglasi"
            android:label="anonce"
            android:configChanges="orientation|keyboardHidden|screenSize" >
                       <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>

</manifest>
```

**Comment by milesich** [comment]
You are missing `android:name="anonce"` in your application declaration.

**Comment by an-arhos** [comment]
I added that and got this
```java
08-30 11:17:01.265: E/Trace(27278): error opening trace file: No such file or directory (2)
08-30 11:17:01.295: I/System.out(27278): Sending WAIT chunk
08-30 11:17:01.295: W/ActivityThread(27278): Application com.example.anonce is waiting for the debugger on port 8100...
08-30 11:17:01.495: I/System.out(27278): Debugger has connected
08-30 11:17:01.495: I/System.out(27278): waiting for debugger to settle...
08-30 11:17:01.695: I/System.out(27278): waiting for debugger to settle...
08-30 11:17:01.895: I/System.out(27278): waiting for debugger to settle...
08-30 11:17:02.095: I/System.out(27278): waiting for debugger to settle...
08-30 11:17:02.296: I/System.out(27278): waiting for debugger to settle...
08-30 11:17:02.496: I/System.out(27278): waiting for debugger to settle...
08-30 11:17:02.696: I/System.out(27278): waiting for debugger to settle...
08-30 11:17:02.896: I/System.out(27278): waiting for debugger to settle...
08-30 11:17:03.106: I/System.out(27278): waiting for debugger to settle...
08-30 11:17:03.307: I/System.out(27278): waiting for debugger to settle...
08-30 11:17:03.507: I/System.out(27278): waiting for debugger to settle...
08-30 11:17:03.707: I/System.out(27278): waiting for debugger to settle...
08-30 11:17:03.907: I/System.out(27278): waiting for debugger to settle...
08-30 11:17:04.107: I/System.out(27278): waiting for debugger to settle...
08-30 11:17:04.298: I/System.out(27278): waiting for debugger to settle...
08-30 11:17:04.498: I/System.out(27278): waiting for debugger to settle...
08-30 11:17:04.698: I/System.out(27278): waiting for debugger to settle...
08-30 11:17:04.898: I/System.out(27278): debugger has settled (1330)
08-30 11:17:05.439: W/anonce(27278): no network
08-30 11:17:12.796: D/ACRA(27278): ACRA is enabled for com.example.anonce, intializing...
08-30 11:17:13.006: W/ACRA(27278): com.example.anonce reports will be sent by email (if accepted by user).
08-30 11:17:13.016: D/ACRA(27278): Looking for error files in /data/data/com.example.anonce/files
08-30 11:17:13.226: D/ACRA(27278): Looking for error files in /data/data/com.example.anonce/files
```
so acra is initializing.
Thank you William and thank you milesich.
but now I am not sure where do I put error files and in what form?

**Comment by milesich** [comment]
You do not put error files anywhere. When your application crash ACRA will create an error file and next time your application start, ACRA will send that error file to your ACRA backend. In your case it will open email client with the error and its on the user to send it or not.

**Comment by an-arhos** [comment]
Thank you.

**Comment by william-ferguson-au** [comment]
Good to know.
Thanks @milesich
