### ISSUE TITLE
Unable to catch real cause of crash (in some cases)

### ISSUE THREAD

**Issue by ymsf** [ACRA/acra#302]
I've just started using acra. I am using acra with AndroidStudio 1.3.2 with following in the build.gradle: -
dependencies {
    ...
    compile 'ch.acra:acra:4.5.0'
}

I have also deliberately added an error (causing a crash) to one of the activities (by using a null pointer).

Everything seems to be functioning nicely (and the app does crash when it ought to), except that the crash report being sent is not related to my above referred code. 

The stack trace being shown is: -

```
java.lang.InternalError: Thread starting during runtime shutdown
	at java.lang.Thread.nativeCreate(Native Method)
	at java.lang.Thread.start(Thread.java:1063)
	at org.apache.http.impl.conn.tsccm.AbstractConnPool.enableConnectionGC(AbstractConnPool.java:145)
	at org.apache.http.impl.conn.tsccm.ThreadSafeClientConnManager.createConnectionPool(ThreadSafeClientConnManager.java:125)
	at org.apache.http.impl.conn.tsccm.ThreadSafeClientConnManager.<init>(ThreadSafeClientConnManager.java:103)
	at org.acra.util.HttpRequest.getHttpClient(HttpRequest.java:214)
	at org.acra.util.HttpRequest.send(HttpRequest.java:141)
	at org.acra.sender.HttpSender.send(HttpSender.java:225)
	at org.acra.SendWorker.sendCrashReport(SendWorker.java:179)
	at org.acra.SendWorker.checkAndSendReports(SendWorker.java:141)
	at org.acra.SendWorker.run(SendWorker.java:77)
```

Curiously, if I just do `throw new NullPointerException();` instead of using a null pointer for crashing the app, I get two crash reports on the server, one for the NPE and the other for orca as stated above.

**Comment by william-ferguson-au** [comment]
Try with the latest version of ACRA which is 4.6.2

**Comment by ymsf** [comment]
I'm now using 4.6.2 (had read somewhere that 4.5.0 is latest stale version).

Now, when i do ```throw new NullPointerException();``` I get one single crash report on the server, as expected.
But when I cause a crash by using a null pointer (at the same place where I throw the NPE), I get no crash report on the server.
Log output (covering cycle: Start app > Crash app > Start app), after removing some irrelevant lines, is as following: -
```
08-30 10:16:36.572    1978-1978/in.whoopee.myportfolio D/ACRA﹕ ACRA is enabled for in.whoopee.myportfolio, initializing...
08-30 10:16:36.572    1978-1978/in.whoopee.myportfolio D/ACRA﹕ Using custom Report Fields
08-30 10:16:36.577    1978-1978/in.whoopee.myportfolio D/ACRA﹕ Looking for error files in /data/data/in.whoopee.myportfolio/files
08-30 10:16:36.603    1978-2014/in.whoopee.myportfolio I/GAv4﹕ Dry run enabled. Would have sent hit: ht=1440909996601, _v=ma7.5.71, a=1402403098, aid=in.whoopee.myportfolio, an=My Portfolio, av=0.3.3-beta, cd=in.whoopee.myportfolio.MainActivity, cid=2bd83f43-4e01-43d0-988a-73d76810b99a, sc=start, sr=768x1184, t=screenview, tid=UA-57182414-2, ul=en-us, v=1
08-30 10:16:36.609    1978-2018/in.whoopee.myportfolio D/OpenGLRenderer﹕ Use EGL_SWAP_BEHAVIOR_PRESERVED: true
08-30 10:16:36.610    1978-1978/in.whoopee.myportfolio D/﹕ HostConnection::get() New Host Connection established 0xa5c790b0, tid 1978
08-30 10:16:36.611    1978-1978/in.whoopee.myportfolio D/Atlas﹕ Validating map...
08-30 10:16:36.628    1978-2018/in.whoopee.myportfolio D/﹕ HostConnection::get() New Host Connection established 0xa5c792e0, tid 2018
08-30 10:16:36.632    1978-2018/in.whoopee.myportfolio I/OpenGLRenderer﹕ Initialized EGL, version 1.4
08-30 10:16:36.687    1978-2018/in.whoopee.myportfolio D/OpenGLRenderer﹕ Enabling debug mode 0
08-30 10:16:36.711    1978-2018/in.whoopee.myportfolio W/EGL_emulation﹕ eglSurfaceAttrib not implemented
08-30 10:16:36.711    1978-2018/in.whoopee.myportfolio W/OpenGLRenderer﹕ Failed to set EGL_SWAP_BEHAVIOR on surface 0xa5ca2320, error=EGL_SUCCESS
08-30 10:16:36.740    1978-2019/in.whoopee.myportfolio D/NavUpdateService﹕ NAV update skipped.
08-30 10:16:54.770    1978-1978/in.whoopee.myportfolio D/AndroidRuntime﹕ Shutting down VM
08-30 10:16:54.770    1978-1978/in.whoopee.myportfolio E/ACRA﹕ ACRA caught a RuntimeException for in.whoopee.myportfolio
    java.lang.RuntimeException: Unable to resume activity {in.whoopee.myportfolio/in.whoopee.myportfolio.MfInvestedSchemeDetailActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.gms.ads.AdView.resume()' on a null object reference
            at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2989)
            at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3020)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2395)
            at android.app.ActivityThread.access$800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5257)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.gms.ads.AdView.resume()' on a null object reference
            at in.whoopee.myportfolio.MfInvestedSchemeDetailActivity.onResume(MfInvestedSchemeDetailActivity.java:44)
            at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1257)
            at android.app.Activity.performResume(Activity.java:6076)
            at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2978)
            at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3020)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2395)
            at android.app.ActivityThread.access$800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5257)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
08-30 10:17:09.866    2275-2275/in.whoopee.myportfolio D/ACRA﹕ ACRA is enabled for in.whoopee.myportfolio, initializing...
08-30 10:17:09.866    2275-2275/in.whoopee.myportfolio D/ACRA﹕ Using custom Report Fields
08-30 10:17:09.869    2275-2275/in.whoopee.myportfolio D/ACRA﹕ Looking for error files in /data/data/in.whoopee.myportfolio/files
08-30 10:17:09.898    2275-2296/in.whoopee.myportfolio D/OpenGLRenderer﹕ Use EGL_SWAP_BEHAVIOR_PRESERVED: true
08-30 10:17:09.900    2275-2275/in.whoopee.myportfolio D/﹕ HostConnection::get() New Host Connection established 0xb3ffa210, tid 2275
08-30 10:17:09.902    2275-2275/in.whoopee.myportfolio D/Atlas﹕ Validating map...
08-30 10:17:09.906    2275-2297/in.whoopee.myportfolio D/NavUpdateService﹕ NAV update skipped.
08-30 10:17:09.931    2275-2292/in.whoopee.myportfolio W/GAv4﹕ AnalyticsService not registered in the app manifest. Hits might not be delivered reliably. See http://goo.gl/8Rd3yj for instructions.
08-30 10:17:09.947    2275-2296/in.whoopee.myportfolio D/﹕ HostConnection::get() New Host Connection established 0xb3ffa640, tid 2296
08-30 10:17:09.952    2275-2292/in.whoopee.myportfolio I/GAv4﹕ Dry run enabled. Would have sent hit: ht=1440910029893, _v=ma7.5.71, a=411204396, aid=in.whoopee.myportfolio, an=My Portfolio, av=0.3.3-beta, cd=in.whoopee.myportfolio.MainActivity, cid=2bd83f43-4e01-43d0-988a-73d76810b99a, sc=start, sr=768x1184, t=screenview, tid=UA-57182414-2, ul=en-us, v=1
08-30 10:17:09.956    2275-2296/in.whoopee.myportfolio I/OpenGLRenderer﹕ Initialized EGL, version 1.4
08-30 10:17:10.009    2275-2296/in.whoopee.myportfolio D/OpenGLRenderer﹕ Enabling debug mode 0
08-30 10:17:10.028    2275-2296/in.whoopee.myportfolio W/EGL_emulation﹕ eglSurfaceAttrib not implemented
08-30 10:17:10.028    2275-2296/in.whoopee.myportfolio W/OpenGLRenderer﹕ Failed to set EGL_SWAP_BEHAVIOR on surface 0xa50339e0, error=EGL_SUCCESS
```

**Comment by william-ferguson-au** [comment]
There is no difference to ACRA how the NPE is generated, so something else in your app/config is causing the difference is behaviour.

What version of Android are your testing on?
Are you testing on the emulator or a device?
What does your ACRA config look like?

**Comment by ymsf** [comment]
I'm testing on emulator using Android 5.1.
With ACRA configuration, I hope you meant the following: -
```
@ReportsCrashes(formUri = "http://www.who****************.php",
        customReportContent = {
                ReportField.APP_VERSION_CODE,
                ReportField.APP_VERSION_NAME,
                ReportField.ANDROID_VERSION,
                ReportField.PHONE_MODEL,
                ReportField.USER_CRASH_DATE,
                ReportField.STACK_TRACE
        },
        mode = ReportingInteractionMode.SILENT)
public class MyApplication extends Application {

    private Tracker mTracker;

    @Override
    public void onCreate() {
        super.onCreate();

        GoogleAnalytics googleAnalytics = GoogleAnalytics.getInstance(this);
        if (BuildConfig.DEBUG)
            googleAnalytics.setDryRun(true);

        mTracker = googleAnalytics.newTracker("***********");
        mTracker.enableAutoActivityTracking(true);
        //mTracker.enableExceptionReporting(true);

        Utility.scheduleAlarms(this);

        ACRA.init(this);
    }
```
I am using Android Studio 1.3.2 and I have following in build.gradle: -
```
dependencies {
    compile 'com.google.android.gms:play-services-ads:7.5.0'
    compile 'com.google.android.gms:play-services-analytics:7.5.0'
    compile 'ch.acra:acra:4.6.2'
}
```
***.php is a custom script developed my me.

Sorry for taking so much time, I just wanted to make sure that I was not doing something obviously wrong.

**Comment by ymsf** [comment]
I am sorry and happy to say that I've tracked the problem and it was due to my erroneous php script; I was not properly escaping the strings before submitting to mysql (the crash reports not getting saved on the server contained `'` in the stack trace).
Sorry for taking your precious time.

**Comment by william-ferguson-au** [comment]
Great. Glad it's working for you
