### ISSUE TITLE
Crash report is not send on ACRA 4.7 RC1 - TrustManagerFactory is not initialized

### ISSUE THREAD

**Issue by RazorPT** [ACRA/acra#307]
I tried crashing the app with ACRA 4.7 RC1 but when i try it i always get this error:

09-28 22:37:25.657  17799-17869/? E/ACRA﹕ Unknown json subtree type, see issue #186
09-28 21:52:48.389    5332-5367/? E/ACRA﹕ Failed to send crash reports for 1543173220508-approved.stacktrace
    java.lang.IllegalStateException: TrustManagerFactory is not initialized
            at com.android.org.conscrypt.TrustManagerFactoryImpl.engineGetTrustManagers(TrustManagerFactoryImpl.java:77)
            at javax.net.ssl.TrustManagerFactory.getTrustManagers(TrustManagerFactory.java:219)
            at org.acra.util.HttpRequest.send(HttpRequest.java:84)
            at org.acra.sender.HttpSender.send(HttpSender.java:245)
            at org.acra.SendWorker.sendCrashReport(SendWorker.java:181)
            at org.acra.SendWorker.checkAndSendReports(SendWorker.java:140)
            at org.acra.SendWorker.run(SendWorker.java:76)

Edit: the crash is being sent if i use ACRA 4.6.2, i am using gradle

Edit2: i noctied this also on the log:
 D/ACRA﹕ Connect to https://testapps.cloudant.com/acra-testapp/_design/acra-storage/_update/report
09-28 22:35:09.235  16507-16536/? E/ACRA﹕ ACRA caught a InternalError for com.blogspot.test.testapp
    java.lang.InternalError: Thread starting during runtime shutdown
            at java.lang.Thread.nativeCreate(Native Method)
            at java.lang.Thread.start(Thread.java:1063)
            at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:921)
            at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1337)
            at com.android.okhttp.ConnectionPool.addConnection(ConnectionPool.java:208)
            at com.android.okhttp.ConnectionPool.recycle(ConnectionPool.java:198)
            at com.android.okhttp.OkHttpClient$1.recycle(OkHttpClient.java:111)
            at com.android.okhttp.internal.http.HttpConnection$AbstractSource.endOfInput(HttpConnection.java:377)
            at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:426)
            at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:349)
            at java.io.InputStream.read(InputStream.java:162)
            at com.a.a.a.a.a(SourceFile:238)
            at com.a.a.a.a.a(SourceFile:123)
            at com.a.a.k.run(SourceFile:112)

**Comment by william-ferguson-au** [comment]
Thanks for checking out RC1.

What version of Android did you run your test on?
Not sure why I'm not seeing the same thing, but I have an idea on how to mitigate.

The 2nd stacktrace is a problem generated by your app. Certain versions of Android won't let you start a Thread during VM shutdown, and at com.a.a.a.a.a(SourceFile:238) is doing so when it tries to read the InputStream from a URLConnection.

**Comment by RazorPT** [comment]
Hi there i tested it on my Nexus 5 running Android Marshmallow Preview 3

**Comment by RazorPT** [comment]
I also tested it on my Samsung Galaxy Tab 2 7.0 running Cyanogen 12.1 (Android 5.1) and it throws the same error so its not a Marshmallow issue

**Comment by RazorPT** [comment]
This is what i am using for the configuration of acra in case its relevant

@ReportsCrashes(
formUri = "https://testapps.cloudant.com/acra-testapp/_design/acra-storage/_update/report", reportType = org.acra.sender.HttpSender.Type.JSON, httpMethod = org.acra.sender.HttpSender.Method.PUT, formUriBasicAuthLogin = "blablabla", formUriBasicAuthPassword = "blablab2"// ,
// Your usual ACRA configuration
// mode = ReportingInteractionMode.TOAST,
// resToastText = R.string.crash_toast_text
)

**Comment by william-ferguson-au** [comment]
Still not sure how to stop HttpUrlConnection from starting a thread on shutdown. I suspect when I was testing it must have been prepopulated by something else.

**Comment by RazorPT** [comment]
Hi William i just noticed your code change and seems to me that it will fix my issue, would it be possible to update the maven repository with the latest code so i can test with gradle? Thank you

**Comment by william-ferguson-au** [comment]
We still need to work out how to stop HttpUrlConnection from trying to start a Thread when making a connection.

**Comment by xedo** [comment]
I also got it (acra:4.7.0-RC.1) after enable ProGuard:
````
10-02 17:01:30.717  17174-17209/? D/ACRA﹕ Connect to https://xxx.cloudant.com/acra-xxx/_design/acra-storage/_update/report
10-02 17:01:30.752  17174-17209/? E/ACRA﹕ Failed to send crash reports for xxxxxxx-approved.stacktrace
    java.lang.IllegalStateException: TrustManagerFactory is not initialized
            at com.android.org.conscrypt.TrustManagerFactoryImpl.engineGetTrustManagers(TrustManagerFactoryImpl.java:77)
            at javax.net.ssl.TrustManagerFactory.getTrustManagers(TrustManagerFactory.java:219)
            at org.acra.util.HttpRequest.send(HttpRequest.java:84)
            at org.acra.sender.HttpSender.send(HttpSender.java:245)
            at org.acra.SendWorker.sendCrashReport(SendWorker.java:181)
            at org.acra.SendWorker.checkAndSendReports(SendWorker.java:140)
            at org.acra.SendWorker.run(SendWorker.java:76)
````

proguard config:
````
-keepattributes SourceFile,LineNumberTable
-keepattributes *Annotation*
-keep class org.acra.** { *; }
