### ISSUE TITLE
4.7.0-RC2 can't find class  net.iharder

### ISSUE THREAD

**Issue by Gentrium** [ACRA/acra#326]
I have this exception when trying  to send Report with login and Password
 java.lang.NoClassDefFoundError: net.iharder.Base64
                                                               at org.acra.util.HttpRequest.send(HttpRequest.java:92)
                                                               at org.acra.sender.HttpSender.send(HttpSender.java:245)
                                                               at org.acra.SendWorker.sendCrashReport(SendWorker.java:181)
                                                               at org.acra.SendWorker.checkAndSendReports(SendWorker.java:140)
                                                               at org.acra.SendWorker.run(SendWorker.java:76)

**Comment by william-ferguson-au** [comment]
`net.iharder:base64` is a declared dependency. See https://repo1.maven.org/maven2/ch/acra/acra/4.7.0-RC.2/acra-4.7.0-RC.2.pom

You build tool should have picked that up and included it.
