### ISSUE TITLE
ACRA   java.lang.NoClassDefFoundError:

### ISSUE THREAD

**Issue by ndeokar** [ACRA/acra#349]
i am having trouble in adding the lib to the project.
i have added the compile path to the build.gradle
even i have initialized the ACRA in AppController.

everything is well in place while i compile the app. but once i launch the app i stack trace says this

@ReportsCrashes(
        httpMethod = HttpSender.Method.POST,
        reportType=org.acra.sender.HttpSender.Type.JSON,
        formUri = "http://192.168.0.104:8080/MutterflyWS/rest/acra/add",
        mode = ReportingInteractionMode.TOAST,
        resToastText = R.string.crash_toast_text,
        additionalSharedPreferences={"MutterflyAppPref"}
)

public class AppController extends Application {

    @Override
    public void onCreate() {
        super.onCreate();

        // The following line triggers the initialization of ACRA
       ACRA.init(this);
    }

}

:13:02.100 30713-30713/com.skcsllp.mutterfly E/AndroidRuntime: FATAL EXCEPTION: main                                                                       java.lang.NoClassDefFoundError: org.acra.ErrorReporter$1
                                                                           at org.acra.ErrorReporter.<clinit>(ErrorReporter.java:110)
                                                                           at org.acra.ACRA.init(ACRA.java:178)
                                                                           at org.acra.ACRA.init(ACRA.java:136)
                                                                           at org.acra.ACRA.init(ACRA.java:121)
                                                                           at com.skcsllp.mutterfly.Global.AppController.onCreate(AppController.java:43)
                                                                           at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
                                                                           at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4684)
                                                                           at android.app.ActivityThread.access$1400(ActivityThread.java:159)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1376)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                           at android.os.Looper.loop(Looper.java:176)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5419)
                                                                           at java.lang.reflect.Method.invokeNative(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:525)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
                                                                           at dalvik.system.NativeStart.main(Native Method)

**Comment by william-ferguson-au** [comment]
Since it has found the ACRA and ErrorReporter classes at runtime then the ACRA library has been included. But if it can't find ErrorReporter$1 then some of the ACRA library is missing.

Are you using Proguard to remove/obfuscate classes?

**Comment by ndeokar** [comment]
Thank you for reply... here is build.gradle

android {
    compileSdkVersion 23
    buildToolsVersion '23.0.2'

    defaultConfig {
        applicationId "com.skcsllp.mutterfly"
        minSdkVersion 15
        targetSdkVersion 19
        versionCode 26
        versionName "2.2.2.1"
        // Enabling multidex support.
         multiDexEnabled true

    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }


    packagingOptions {
        exclude 'META-INF/LICENSE.txt'
    }


}



dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.android.support:appcompat-v7:23.1.1'
    compile 'com.google.android.gms:play-services:8.3.0'
    compile 'com.facebook.android:facebook-android-sdk:4.1.0'
    compile 'com.github.bumptech.glide:glide:3.6.1'
    //ACRA Crash reports
    compile 'ch.acra:acra:4.6.2'
    compile 'com.android.support:support-v4:23.1.1'
    compile 'com.android.support:recyclerview-v7:23.1.1'

}

**Comment by william-ferguson-au** [comment]
As it says in the ACRA Proguard doco, you need to include extra Proguard config for ACRA.
https://github.com/ACRA/acra/wiki/ProGuard

**Comment by ndeokar** [comment]
i am confused with what exactly i should add... i should i just update the acra ver to 4.7? kindly suggest

**Comment by william-ferguson-au** [comment]
You need to include these ACRA specific Proguard config into your Proguard file:

```
#ACRA specifics
# Restore some Source file names and restore approximate line numbers in the stack traces,
# otherwise the stack traces are pretty useless
-keepattributes SourceFile,LineNumberTable

# ACRA needs "annotations" so add this... 
# Note: This may already be defined in the default "proguard-android-optimize.txt"
# file in the SDK. If it is, then you don't need to duplicate it. See your
# "project.properties" file to get the path to the default "proguard-android-optimize.txt".
-keepattributes *Annotation*

# Keep all the ACRA classes
-keep class org.acra.** { *; }

# Don't warn about removed methods from AppCompat
-dontwarn android.support.v4.app.NotificationCompat*
```

**Comment by ndeokar** [comment]
thanks a ton! it worked.. proguard was skipping acra class files...

**Comment by ndeokar** [comment]
i havent made any gradle level changes but still same issue started again... with same stack trace..i have  included ACRA specific Proguard config in my Proguard file

**Comment by F43nd1r** [comment]
Proguard shouldn't even be active, because your configuration disables it (for the release build).
If you want to make sure that proguard is always disabled, include this buildType:
`debug{
    minifyEnabled false
}`

But I think the problem lies elsewhere.
You could try to clean your project, or to use a newer version of acra.

**Comment by william-ferguson-au** [comment]
Yep, use ACRA-4.8.1 and this is not an issue.
