### ISSUE TITLE
Getting "Resource is not a ColorStateList (color or path): TypedValue{t=0x2/d=0x101009b a=3}" on Huawei device API 19

### ISSUE THREAD

**Issue by Sdghasemi** [ACRA/acra#363]
I strangely get the following exception with ACRA 4.6.2 on a reported Huawei device. It's so weird, cause ACRA is running on my device with API21 and working like a charm, but I'm facing this problem on API19. Even when the user tries to send error with clicking on the error reporting notification to open dialog, no dialog opens and a new notification get created again and so on.

**Here is the stack trace:**
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sdghasemi.Scheduler/org.acra.CrashReportDialog}: android.content.res.Resources$NotFoundException: Resource is not a ColorStateList (color or path): TypedValue{t=0x2/d=0x101009b a=3}
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2264)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2313)
at android.app.ActivityThread.access$1100(ActivityThread.java:141)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1238)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5336)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:681)
at dalvik.system.NativeStart.main(Native Method)
Caused by: android.content.res.Resources$NotFoundException: Resource is not a ColorStateList (color or path): TypedValue{t=0x2/d=0x101009b a=3}
at android.content.res.Resources.loadColorStateList(Resources.java:2301)
at com.huawei.android.content.res.ResourcesEx.loadColorStateList(ResourcesEx.java:752)
at android.content.res.TypedArray.getColorStateList(TypedArray.java:370)
at android.widget.TextView.<init>(TextView.java:711)
at android.widget.TextView.<init>(TextView.java:637)
at android.widget.TextView.<init>(TextView.java:633)
at org.acra.CrashReportDialog.buildCustomView(CrashReportDialog.java:67)
at org.acra.CrashReportDialog.onCreate(CrashReportDialog.java:43)
at android.app.Activity.performCreate(Activity.java:5302)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1090)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2228)
... 11 more
android.content.res.Resources$NotFoundException: Resource is not a ColorStateList (color or path): TypedValue{t=0x2/d=0x101009b a=3}
at android.content.res.Resources.loadColorStateList(Resources.java:2301)
at com.huawei.android.content.res.ResourcesEx.loadColorStateList(ResourcesEx.java:752)
at android.content.res.TypedArray.getColorStateList(TypedArray.java:370)
at android.widget.TextView.<init>(TextView.java:711)
at android.widget.TextView.<init>(TextView.java:637)
at android.widget.TextView.<init>(TextView.java:633)
at org.acra.CrashReportDialog.buildCustomView(CrashReportDialog.java:67)
at org.acra.CrashReportDialog.onCreate(CrashReportDialog.java:43)
at android.app.Activity.performCreate(Activity.java:5302)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1090)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2228)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2313)
at android.app.ActivityThread.access$1100(ActivityThread.java:141)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1238)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5336)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:681)
at dalvik.system.NativeStart.main(Native Method)

```
Is there a way to fix it? Any help would be appreciated

**Comment by william-ferguson-au** [comment]
@Sdghasemi can you please post your ACRA config.

**Comment by Sdghasemi** [comment]
@william-ferguson-au Here you are.
I'm using `@ReportCrashes()` annotation to configure ACRA as described in the documentation:

`@ReportsCrashes(
        httpMethod = HttpSender.Method.PUT,
        reportType = HttpSender.Type.JSON,
        formUri = "https://__________________________/report",
        formUriBasicAuthLogin = "_______",
        formUriBasicAuthPassword = "______________",
        socketTimeout = 30000,
        logcatArguments = { "-t", "200", "-v", "long" },
        // DIALOG FORM
        mode = ReportingInteractionMode.NOTIFICATION
        resDialogText = R.string.crash_dialog_text,
        resDialogIcon = R.drawable.ic_warning_black_96dp,
        resDialogTitle = R.string.crash_dialog_title,
        resDialogCommentPrompt = R.string.crash_dialog_comment_prompt,
        resDialogEmailPrompt = R.string.crash_user_email_label,
        resDialogPositiveButtonText = R.string.crash_dialog_positive_button_text,
        resDialogNegativeButtonText = R.string.crash_dialog_negative_button_text,
        resDialogOkToast = R.string.crash_dialog_ok_toast,
        // NOTIFICATION FORM
        resNotifTickerText = R.string.crash_notif_ticker_text,
        resNotifTitle = R.string.crash_notif_title,
        resNotifText = R.string.crash_notif_text,
        resNotifIcon = android.R.drawable.stat_notify_error
)`

**Comment by william-ferguson-au** [comment]
Have you tried compiling your app against API 19 SDK?

At a guess it won't work because you appear to be using a Material Design colour : @color/primary_material_light
And the Material Design palette is Android 21+
See http://developer.android.com/training/material/theme.html

**Comment by Sdghasemi** [comment]
@william-ferguson-au I'm using `@color/primary_material_light` from Android support v7 AppCompat.
The problem can't come up there since I'm also using this color as `colorPrimary` in my app theme.
And I can't compile my project below 21 SDK since the`AppCompat` is using v21 resouces.
On the other hand I'm also using this dialog theme on all `AlertDialog`s in my project and it runs without problem.
This is the code I'm creating dialog with in my app in case you need it:
`protected static android.support.v7.app.AlertDialog getAlertDlgInstance(Context context){
        return new AlertDialog.Builder(context, R.style.Theme_AppBaseTheme_AlertDialogStyle).create();
    }
    protected static void createAlertDialog(android.support.v7.app.AlertDialog dialog, Context context, String tile, String message, int icon, boolean cancelable, @Nullable View customView, @Nullable String positiveButtonText, @Nullable String negativeButtonText, @Nullable View.OnClickListener positiveListener, @Nullable View.OnClickListener negativeListener) {
        if (tile != null) dialog.setTitle(tile);
        if (message != null) dialog.setMessage(message);
        if (icon != -1) dialog.setIcon(icon);
        dialog.setCancelable(cancelable);
        if (cancelable && negativeButtonText != null && negativeListener != null) dialog.setOnCancelListener(new DialogInterface.OnCancelListener() {
            @Override
            public void onCancel(DialogInterface dlg) {
                negativeListener.onClick(dialog.getButton(DialogInterface.BUTTON_NEGATIVE));
            }
        });
        if (customView != null) {
            int padding = (int) (20 * (context.getResources().getDisplayMetrics().densityDpi / 160f));
            dialog.setView(customView, padding, 0, padding, 0);
        }
        if (positiveButtonText != null) dialog.setButton(DialogInterface.BUTTON_POSITIVE, positiveButtonText, new DialogInterface.OnClickListener() {
            @Override
            public void onClick(DialogInterface dialogInterface, int i) {

            }
        });
        if (negativeButtonText != null) dialog.setButton(DialogInterface.BUTTON_NEGATIVE, negativeButtonText, new DialogInterface.OnClickListener() {
            @Override
            public void onClick(DialogInterface dialogInterface, int i) {

            }
        });
        dialog.show();
        dialog.getWindow().setBackgroundDrawable(new ColorDrawable(android.graphics.Color.TRANSPARENT));

        if (positiveButtonText != null) {
            dialog.getButton(DialogInterface.BUTTON_POSITIVE).setTextAppearance(context, R.style.Theme_AppBaseTheme_AlertDialogStyle_PositiveButtonTextAppearance);
            dialog.getButton(DialogInterface.BUTTON_POSITIVE).setOnClickListener(positiveListener);
        }
        if (negativeButtonText != null) {
            dialog.getButton(DialogInterface.BUTTON_NEGATIVE).setTextColor(context.getResources().getColor(R.color.app_theme_semi_dark));
            dialog.getButton(DialogInterface.BUTTON_NEGATIVE).setOnClickListener(negativeListener);
        }
    }`

I'm using that in my entire whole app which runs fine.
Here is **values/styles.xml** for dialog theme:
`    <style name="Theme.AppBaseTheme.AlertDialogStyle" parent="Theme.AppCompat.Light.Dialog.Alert">
        <item name="colorAccent">?attr/app_theme</item>
        <item name="android:textColorPrimary">@color/app_theme_semi_dark</item>
        <item name="android:windowTitleStyle">@style/Theme.AppBaseTheme.AlertDialogStyle.TitleTextAppearance</item>
        <item name="android:background">@drawable/dialog_rounded_corners_bg</item>
    </style>
    <style name="Theme.AppBaseTheme.AlertDialogStyle.TitleTextAppearance">
        <item name="android:textColor">@color/full_black</item>
        <item name="android:textAppearance">@style/TextAppearance.AppCompat.Title</item>
    </style>
    <style name="Theme.AppBaseTheme.AlertDialogStyle.PositiveButtonTextAppearance">
        <item name="android:textColor">?attr/app_theme</item>
        <item name="android:textAllCaps">false</item>
        <item name="android:textStyle">bold</item>
    </style>`

**Comment by william-ferguson-au** [comment]
Well, it's dying when it tries to create a TextView in the crash report Dialog. You have configured a theme for that Activity. Something about that theme is not compatible with API 19.

I would recommend using an empty extension of the default theme and then slowly adding your theming back until it breaks.

**Comment by william-ferguson-au** [comment]
I would also recommend upgrading to ACRA-4.8.1

**Comment by Sdghasemi** [comment]
Finally found the problem!
I was configuring dialog theme with new `Theme.AppCompat.Light.Dialog.Alert` which requires to invoke only with **`android.support.v7.app.AlertDialog.Builder(Context ctx, int theme)`** and also needs to pass declared theme as theme parameter in its Builder constructor. While ACRA (all dialog versions) uses **`android.app.AlertDialog`** that uses device default dialog theme from each SDK API version to illustrate the dialog.
The problem solved when I used default dialog theme for each SDK version as my `CrashDialog` theme. (as described [here](https://github.com/ACRA/acra/wiki/AdvancedUsage#dialog))

Thank you very much for your quick support.
It really helped narrow it down

**Comment by william-ferguson-au** [comment]
That's great.
