### ISSUE TITLE
ConfigurationBuilder.build() generates NPE if no @ReportCrashes annotation exists on Application

### ISSUE THREAD

**Issue by william-ferguson-au** [ACRA/acra#365]
And  .build();  method fails with 

```
Caused by: java.lang.NullPointerException: Attempt to get length of null array
at org.acra.config.ACRAConfiguration.copyArray(ACRAConfiguration.java:1232)
at org.acra.config.ACRAConfiguration.<init>(ACRAConfiguration.java:113)
at org.acra.config.ConfigurationBuilder.build(ConfigurationBuilder.java:163)
```

cause annotationConfig.additionalDropBoxTags is  null .

**Comment by william-ferguson-au** [comment]
NB teh work around is add an empty @ReportCrashes annotation to your Application class.
