### ISSUE TITLE
NullPointerException deleting unset reports from old app version

### ISSUE THREAD

**Issue by DrDerico** [ACRA/acra#369]
Hi! I catched this exception with Acra 4.8.1

```
Caused by: java.lang.NullPointerException
	at java.util.TimSort.sort(TimSort.java:169)
	at java.util.Arrays.sort(Arrays.java:2090)
	at org.acra.file.BulkReportDeleter.deleteReports(BulkReportDeleter.java:31)
	at org.acra.util.ApplicationStartupProcessor.deleteUnsentReportsFromOldAppVersion(ApplicationStartupProcessor.java:43)
	at org.acra.ACRA.init(ACRA.java:216)
	at com.drderico.towerd.myApp.onCreate(myApp.java:22)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:969)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:3290)
	... 10 more
```

**Comment by william-ferguson-au** [comment]
Thanks
