### ISSUE TITLE
ACRA 4.8.2 breaks DB copy on start

### ISSUE THREAD

**Issue by kaiwinter** [ACRA/acra#379]
My app comes with an SQLite database which I copy into the app´s database directory on first start. This was working without any problems for a long time. Now I was updating my ACRA dependency from 4.5.0 to 4.8.2 and the app begins to crash on start occasionally.

I´ve tested 4.6.0 and 4.7.0 and it seems to work in both versions.

This is the stacktrace. There must be a reason why the `onCreate()` method of my `Application` class gets called two times. The second call results in a second copy operation while the first is still in progress. This corrupts the database somehow. This happens with 4.8.2 only.

```
02-23 13:34:11.173 404-463/system_process D/MobileDataStateTracker: default: setPolicyDataEnable(enabled=true)
02-23 13:34:11.469 404-463/system_process D/MobileDataStateTracker: default: setPolicyDataEnable(enabled=true)
02-23 13:34:11.721 404-463/system_process D/MobileDataStateTracker: default: setPolicyDataEnable(enabled=true)
02-23 13:34:11.973 404-463/system_process D/MobileDataStateTracker: default: setPolicyDataEnable(enabled=true)
02-23 13:34:12.233 404-463/system_process D/MobileDataStateTracker: default: setPolicyDataEnable(enabled=true)
02-23 13:34:12.369 30830-30830/? D/AndroidRuntime: CheckJNI is OFF
02-23 13:34:12.373 30830-30830/? D/dalvikvm: Trying to load lib libjavacore.so 0x0
02-23 13:34:12.377 30830-30830/? D/dalvikvm: Added shared lib libjavacore.so 0x0
02-23 13:34:12.381 30830-30830/? D/dalvikvm: Trying to load lib libnativehelper.so 0x0
02-23 13:34:12.381 30830-30830/? D/dalvikvm: Added shared lib libnativehelper.so 0x0
02-23 13:34:12.429 30830-30830/? D/AndroidRuntime: Calling main entry com.android.commands.pm.Pm
02-23 13:34:12.429 404-425/system_process W/ActivityManager: No content provider found for permission revoke: file:///data/local/tmp/my.package.ads
02-23 13:34:12.445 404-425/system_process W/ActivityManager: No content provider found for permission revoke: file:///data/local/tmp/my.package.ads
02-23 13:34:12.445 404-425/system_process I/PackageManager: Copying native libraries to /data/app-lib/vmdl-263167069
02-23 13:34:12.461 404-425/system_process D/dalvikvm: GC_FOR_ALLOC freed 666K, 45% free 6142K/10992K, paused 6ms, total 6ms
02-23 13:34:12.493 404-425/system_process D/dalvikvm: GC_FOR_ALLOC freed 684K, 42% free 6378K/10992K, paused 7ms, total 7ms
02-23 13:34:12.509 404-425/system_process D/dalvikvm: GC_FOR_ALLOC freed 970K, 42% free 6391K/10992K, paused 6ms, total 6ms
02-23 13:34:12.529 404-425/system_process D/dalvikvm: GC_FOR_ALLOC freed 978K, 42% free 6397K/10992K, paused 6ms, total 6ms
02-23 13:34:12.645 404-425/system_process D/dalvikvm: GC_FOR_ALLOC freed 964K, 42% free 6408K/10992K, paused 7ms, total 7ms
02-23 13:34:12.645 404-425/system_process I/PackageManager: Running dexopt on: my.package.ads
02-23 13:34:13.125 30841-30841/? D/dalvikvm: DexOpt: load 45ms, verify+opt 331ms, 4035068 bytes
02-23 13:34:13.169 404-421/system_process I/ActivityManager: Force stopping package my.package.ads appid=10050 user=-1
02-23 13:34:13.185 404-418/system_process D/BackupManagerService: Received broadcast Intent { act=android.intent.action.PACKAGE_ADDED dat=package:my.package.ads flg=0x8000010 (has extras) }
02-23 13:34:13.189 404-430/system_process W/ResourceType: Failure getting entry for 0x7f060000 (t=5 e=0) in package 0 (error -75)
02-23 13:34:13.189 404-418/system_process V/BackupManagerService: addPackageParticipantsLocked: #1
02-23 13:34:13.193 404-439/system_process I/InputReader: Reconfiguring input devices.  changes=0x00000010
02-23 13:34:13.209 404-430/system_process W/RecognitionManagerService: no available voice recognition services found for user 0
02-23 13:34:13.221 404-425/system_process D/dalvikvm: GC_EXPLICIT freed 1015K, 46% free 5940K/10992K, paused 0ms+1ms, total 23ms
02-23 13:34:13.225 598-598/com.android.launcher D/dalvikvm: GC_FOR_ALLOC freed 1283K, 20% free 6664K/8288K, paused 3ms, total 3ms
02-23 13:34:13.229 30830-30830/? D/AndroidRuntime: Shutting down VM
02-23 13:34:13.229 30830-30836/? D/jdwp: Got wake-up signal, bailing out of select
02-23 13:34:13.229 30830-30836/? D/dalvikvm: Debugger has detached; object registry had 1 entries
02-23 13:34:13.533 30848-30848/? D/AndroidRuntime: CheckJNI is OFF
02-23 13:34:13.537 30848-30848/? D/dalvikvm: Trying to load lib libjavacore.so 0x0
02-23 13:34:13.537 30848-30848/? D/dalvikvm: Added shared lib libjavacore.so 0x0
02-23 13:34:13.541 30848-30848/? D/dalvikvm: Trying to load lib libnativehelper.so 0x0
02-23 13:34:13.541 30848-30848/? D/dalvikvm: Added shared lib libnativehelper.so 0x0
02-23 13:34:13.581 30848-30848/? D/AndroidRuntime: Calling main entry com.android.commands.am.Am
02-23 13:34:13.581 30848-30848/? D/dalvikvm: Note: class Landroid/app/ActivityManagerNative; has 163 unimplemented (abstract) methods
02-23 13:34:13.585 404-11059/system_process I/ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 cmp=my.package.ads/.FragmentMainActivity} from pid 30848
02-23 13:34:13.593 30848-30848/? D/AndroidRuntime: Shutting down VM
02-23 13:34:13.593 30848-30854/? D/dalvikvm: Debugger has detached; object registry had 1 entries
02-23 13:34:13.593 30857-30857/? D/dalvikvm: Late-enabling CheckJNI
02-23 13:34:13.593 30848-30856/? I/AndroidRuntime: NOTE: attach of thread 'Binder_1' failed
02-23 13:34:13.601 404-800/system_process I/ActivityManager: Start proc my.package.ads for activity my.package.ads/.FragmentMainActivity: pid=30857 uid=10050 gids={50050, 3003, 1015, 1028}
02-23 13:34:13.605 404-459/system_process I/qtaguid: Failed write_ctrl(s 1 10050) res=-1 errno=1
02-23 13:34:13.605 404-459/system_process W/NetworkManagementSocketTagger: setKernelCountSet(10050, 1) failed with errno -1
02-23 13:34:13.609 30857-30857/? D/MyTag: MyApplication.onCreate
02-23 13:34:13.613 30857-30863/? D/dalvikvm: Debugger has detached; object registry had 1 entries
02-23 13:34:13.613 30857-30857/? I/ACRA: Migrating unsent ACRA reports to new file locations
02-23 13:34:13.613 30857-30857/? I/ACRA: Migrated 0 unsent reports
02-23 13:34:13.613 30857-30857/? I/ACRA: ACRA is enabled for my.package.ads, initializing...
02-23 13:34:13.637 30857-30860/? D/dalvikvm: GC_CONCURRENT freed 256K, 14% free 2597K/3020K, paused 2ms+0ms, total 11ms
02-23 13:34:13.661 404-463/system_process D/MobileDataStateTracker: default: setPolicyDataEnable(enabled=true)
02-23 13:34:13.693 30872-30872/? D/dalvikvm: Late-enabling CheckJNI
02-23 13:34:13.697 30857-30857/? D/MyTag: MyDao()
02-23 13:34:13.697 30857-30857/? I/MyTag: openDatabase()
02-23 13:34:13.697 30857-30857/? D/MyTag: Copying database initially
02-23 13:34:13.697 404-11358/system_process I/ActivityManager: Start proc my.package.ads:acra for service my.package.ads/org.acra.sender.SenderService: pid=30872 uid=10050 gids={50050, 3003, 1015, 1028}
02-23 13:34:13.701 404-463/system_process D/MobileDataStateTracker: default: setPolicyDataEnable(enabled=true)
02-23 13:34:13.741 404-463/system_process D/MobileDataStateTracker: default: setPolicyDataEnable(enabled=true)
02-23 13:34:13.761 30872-30872/? D/MyTag: MyApplication.onCreate
02-23 13:34:13.769 30872-30872/? D/MyTag: MyDao()
02-23 13:34:13.769 30872-30872/? I/MyTag: openDatabase()
02-23 13:34:13.777 30872-30872/? D/MyTag: Using existing database
02-23 13:34:13.785 30872-30872/? E/SQLiteLog: (11) database corruption at line 51791 of [00bb9c9ce4]
02-23 13:34:13.785 30872-30872/? E/SQLiteLog: (11) database disk image is malformed
02-23 13:34:13.785 30872-30872/? E/DefaultDatabaseErrorHandler: Corruption reported by sqlite on database: /data/data/my.package.ads/databases/embedded.db
02-23 13:34:13.785 30872-30872/? E/DefaultDatabaseErrorHandler: deleting the database file: /data/data/my.package.ads/databases/embedded.db
02-23 13:34:13.785 30872-30872/? E/SQLiteLog: (14) cannot open file at line 30191 of [00bb9c9ce4]
02-23 13:34:13.785 30872-30872/? E/SQLiteLog: (14) os_unix.c:30191: (2) open(/data/data/my.package.ads/databases/embedded.db) - 
02-23 13:34:13.793 30872-30872/? E/SQLiteDatabase: Failed to open database '/data/data/my.package.ads/databases/embedded.db'.
	android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
		 at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
		 at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:209)
		 at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
		 at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
		 at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
		 at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
		 at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:804)
		 at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:792)
		 at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
		 at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:669)
		 at my.package.database.SQLiteHelper.<init>(SQLiteHelper.java:47)
		 at my.package.database.MyDao.<init>(MyDao.java:67)
		 at my.package.database.MyDao.getInstance(MyDao.java:59)
		 at my.package.MyApplication.onCreate(MyApplication.java:45)
		 at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
		 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4444)
		 at android.app.ActivityThread.access$1300(ActivityThread.java:141)
		 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316)
		 at android.os.Handler.dispatchMessage(Handler.java:99)
		 at android.os.Looper.loop(Looper.java:137)
		 at android.app.ActivityThread.main(ActivityThread.java:5103)
		 at java.lang.reflect.Method.invokeNative(Native Method)
		 at java.lang.reflect.Method.invoke(Method.java:525)
		 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
		 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
		 at dalvik.system.NativeStart.main(Native Method)
02-23 13:34:13.793 30872-30872/? D/AndroidRuntime: Shutting down VM
02-23 13:34:13.801 30872-30872/? W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0xa4b5e648)
02-23 13:34:13.813 30872-30872/? E/AndroidRuntime: FATAL EXCEPTION: main
	java.lang.RuntimeException: Unable to create application my.package.MyApplication: android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
		 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4447)
		 at android.app.ActivityThread.access$1300(ActivityThread.java:141)
		 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316)
		 at android.os.Handler.dispatchMessage(Handler.java:99)
		 at android.os.Looper.loop(Looper.java:137)
		 at android.app.ActivityThread.main(ActivityThread.java:5103)
		 at java.lang.reflect.Method.invokeNative(Native Method)
		 at java.lang.reflect.Method.invoke(Method.java:525)
		 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
		 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
		 at dalvik.system.NativeStart.main(Native Method)
	 Caused by: android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
		 at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
		 at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:209)
		 at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
		 at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
		 at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
		 at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
		 at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:804)
		 at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:792)
		 at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
		 at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:669)
		 at my.package.database.SQLiteHelper.<init>(SQLiteHelper.java:47)
		 at my.package.database.MyDao.<init>(MyDao.java:67)
		 at my.package.database.MyDao.getInstance(MyDao.java:59)
		 at my.package.MyApplication.onCreate(MyApplication.java:45)
		 at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
		 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4444)
		 at android.app.ActivityThread.access$1300(ActivityThread.java:141) 
		 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316) 
		 at android.os.Handler.dispatchMessage(Handler.java:99) 
		 at android.os.Looper.loop(Looper.java:137) 
		 at android.app.ActivityThread.main(ActivityThread.java:5103) 
		 at java.lang.reflect.Method.invokeNative(Native Method) 
		 at java.lang.reflect.Method.invoke(Method.java:525) 
		 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737) 
		 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
		 at dalvik.system.NativeStart.main(Native Method) 
02-23 13:34:13.817 30857-30857/? D/MyTag: Opening database
02-23 13:34:13.833 30857-30857/? E/SQLiteLog: (14) cannot open file at line 30191 of [00bb9c9ce4]
02-23 13:34:13.833 30857-30857/? E/SQLiteLog: (14) os_unix.c:30191: (2) open(/data/data/my.package.ads/databases/embedded.db) - 
02-23 13:34:13.845 30857-30860/? D/dalvikvm: GC_CONCURRENT freed 338K, 17% free 2643K/3148K, paused 3ms+1ms, total 8ms
02-23 13:34:13.845 30857-30857/? E/SQLiteDatabase: Failed to open database '/data/data/my.package.ads/databases/embedded.db'.
	android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
		 at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
		 at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:209)
		 at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
		 at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
		 at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
		 at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
		 at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:804)
		 at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:789)
		 at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
		 at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:669)
		 at my.package.database.SQLiteHelper.<init>(SQLiteHelper.java:43)
		 at my.package.database.MyDao.<init>(MyDao.java:67)
		 at my.package.database.MyDao.getInstance(MyDao.java:59)
		 at my.package.MyApplication.onCreate(MyApplication.java:45)
		 at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
		 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4444)
		 at android.app.ActivityThread.access$1300(ActivityThread.java:141)
		 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316)
		 at android.os.Handler.dispatchMessage(Handler.java:99)
		 at android.os.Looper.loop(Looper.java:137)
		 at android.app.ActivityThread.main(ActivityThread.java:5103)
		 at java.lang.reflect.Method.invokeNative(Native Method)
		 at java.lang.reflect.Method.invoke(Method.java:525)
		 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
		 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
		 at dalvik.system.NativeStart.main(Native Method)
02-23 13:34:13.849 30857-30857/? D/AndroidRuntime: Shutting down VM
02-23 13:34:13.849 30857-30857/? W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0xa4b5e648)
02-23 13:34:13.849 30857-30857/? E/ACRA: ACRA caught a RuntimeException for my.package.ads
  java.lang.RuntimeException: Unable to create application my.package.MyApplication: android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
		at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4447)
		at android.app.ActivityThread.access$1300(ActivityThread.java:141)
		at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316)
		at android.os.Handler.dispatchMessage(Handler.java:99)
		at android.os.Looper.loop(Looper.java:137)
		at android.app.ActivityThread.main(ActivityThread.java:5103)
		at java.lang.reflect.Method.invokeNative(Native Method)
		at java.lang.reflect.Method.invoke(Method.java:525)
		at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
		at dalvik.system.NativeStart.main(Native Method)
	Caused by: android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
		at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
		at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:209)
		at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
		at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
		at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
		at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
		at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:804)
		at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:789)
		at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
		at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:669)
		at my.package.database.SQLiteHelper.<init>(SQLiteHelper.java:43)
		at my.package.database.MyDao.<init>(MyDao.java:67)
		at my.package.database.MyDao.getInstance(MyDao.java:59)
		at my.package.MyApplication.onCreate(MyApplication.java:45)
		at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
		at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4444)
		at android.app.ActivityThread.access$1300(ActivityThread.java:141) 
		at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316) 
		at android.os.Handler.dispatchMessage(Handler.java:99) 
		at android.os.Looper.loop(Looper.java:137) 
		at android.app.ActivityThread.main(ActivityThread.java:5103) 
		at java.lang.reflect.Method.invokeNative(Native Method) 
		at java.lang.reflect.Method.invoke(Method.java:525) 
		at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737) 
		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
		at dalvik.system.NativeStart.main(Native Method) 
02-23 13:34:13.865 404-421/system_process D/dalvikvm: GC_FOR_ALLOC freed 628K, 45% free 6099K/10992K, paused 35ms, total 35ms
02-23 13:34:13.885 404-421/system_process D/dalvikvm: GC_FOR_ALLOC freed 34K, 44% free 6183K/10992K, paused 17ms, total 17ms
02-23 13:34:13.885 404-421/system_process I/dalvikvm-heap: Grow heap (frag case) to 7.277MB for 1127532-byte allocation
02-23 13:34:13.921 404-413/system_process D/dalvikvm: GC_FOR_ALLOC freed <1K, 34% free 7284K/10992K, paused 33ms, total 33ms
02-23 13:34:13.929 404-421/system_process W/ViewRootImpl: Dropping event due to no window focus: KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_ALT_RIGHT, scanCode=100, metaState=META_ALT_ON|META_ALT_RIGHT_ON, flags=0x8, repeatCount=21456, eventTime=3702074, downTime=2496637, deviceId=1, source=0x301 }
02-23 13:34:13.933 404-421/system_process W/ViewRootImpl: Dropping event due to no window focus: KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_ALT_RIGHT, scanCode=100, metaState=META_ALT_ON|META_ALT_RIGHT_ON, flags=0x8, repeatCount=21457, eventTime=3702375, downTime=2496637, deviceId=1, source=0x301 }
02-23 13:34:13.945 30857-30857/? E/ACRA: Not adding buildConfig to log. Class Not found : my.package.ads.BuildConfig. Please configure 'buildConfigClass' in your ACRA config
02-23 13:34:13.953 30857-30860/? D/dalvikvm: GC_CONCURRENT freed 329K, 16% free 2705K/3204K, paused 1ms+2ms, total 6ms
02-23 13:34:13.961 30857-30892/? E/AndroidRuntime: FATAL EXCEPTION: main
	java.lang.RuntimeException: Unable to create application my.package.MyApplication: android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
		 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4447)
		 at android.app.ActivityThread.access$1300(ActivityThread.java:141)
		 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316)
		 at android.os.Handler.dispatchMessage(Handler.java:99)
		 at android.os.Looper.loop(Looper.java:137)
		 at android.app.ActivityThread.main(ActivityThread.java:5103)
		 at java.lang.reflect.Method.invokeNative(Native Method)
		 at java.lang.reflect.Method.invoke(Method.java:525)
		 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
		 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
		 at dalvik.system.NativeStart.main(Native Method)
	 Caused by: android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
		 at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
		 at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:209)
		 at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
		 at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
		 at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
		 at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
		 at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:804)
		 at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:789)
		 at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
		 at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:669)
		 at my.package.database.SQLiteHelper.<init>(SQLiteHelper.java:43)
		 at my.package.database.MyDao.<init>(MyDao.java:67)
		 at my.package.database.MyDao.getInstance(MyDao.java:59)
		 at my.package.MyApplication.onCreate(MyApplication.java:45)
		 at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
		 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4444)
		 at android.app.ActivityThread.access$1300(ActivityThread.java:141) 
		 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316) 
		 at android.os.Handler.dispatchMessage(Handler.java:99) 
		 at android.os.Looper.loop(Looper.java:137) 
		 at android.app.ActivityThread.main(ActivityThread.java:5103) 
		 at java.lang.reflect.Method.invokeNative(Native Method) 
		 at java.lang.reflect.Method.invoke(Method.java:525) 
		 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737) 
		 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
		 at dalvik.system.NativeStart.main(Native Method) 
02-23 13:34:13.973 404-11059/system_process W/ActivityManager: Process my.package.ads has crashed too many times: killing!
02-23 13:34:13.973 404-11059/system_process W/ActivityManager:   Force finishing activity my.package.ads/.FragmentMainActivity
02-23 13:34:14.081 404-11059/system_process D/dalvikvm: GC_FOR_ALLOC freed 817K, 33% free 7410K/10992K, paused 12ms, total 12ms
02-23 13:34:14.081 404-11059/system_process I/ActivityManager: Killing proc 30857:my.package.ads/u0a10050: crash
02-23 13:34:14.097 404-459/system_process I/qtaguid: Failed write_ctrl(s 0 10050) res=-1 errno=1
02-23 13:34:14.097 404-459/system_process W/NetworkManagementSocketTagger: setKernelCountSet(10050, 0) failed with errno -1
02-23 13:34:14.097 404-463/system_process D/MobileDataStateTracker: default: setPolicyDataEnable(enabled=true)
02-23 13:34:14.105 598-598/com.android.launcher W/EGL_genymotion: eglSurfaceAttrib not implemented
02-23 13:34:14.957 404-463/system_process D/MobileDataStateTracker: default: setPolicyDataEnable(enabled=true)
02-23 13:34:15.193 404-463/system_process D/MobileDataStateTracker: default: setPolicyDataEnable(enabled=true)
02-23 13:34:15.253 404-463/system_process D/MobileDataStateTracker: default: setPolicyDataEnable(enabled=true)
02-23 13:34:15.305 404-463/system_process D/MobileDataStateTracker: default: setPolicyDataEnable(enabled=true)
02-23 13:34:15.341 404-463/system_process D/MobileDataStateTracker: default: setPolicyDataEnable(enabled=true)
02-23 13:34:15.385 404-463/system_process D/MobileDataStateTracker: default: setPolicyDataEnable(enabled=true)
02-23 13:34:33.965 404-421/system_process W/ActivityManager: Timeout executing service: ServiceRecord{528185b0 u0 my.package.ads/org.acra.sender.SenderService}
02-23 13:34:33.965 404-421/system_process I/ActivityManager: Crashing app skipping ANR: ProcessRecord{527fef10 30872:my.package.ads:acra/u0a10050} Executing service my.package.ads/org.acra.sender.SenderService
```

**Comment by koral--** [comment]
`Application#onCreate()` is called 2 times because ACRA 4.8.2 is creating separate process for sending reports.
One of the solutions is to check current process name and skip your DB initialization if that is ACRA service process (by default `<package id>:acra`). Eg. like that: http://stackoverflow.com/a/19632382/630398

**Comment by william-ferguson-au** [comment]
@koral-- is 100% correct. ACRA starts it's `SenderService` in a new process onStart and whenever a repport needs to be sent. This insulates the ACRA send mechanism from a potentially crashed VM state.

You can see how ACRA determines whether it is running as it's SenderService process here:
https://github.com/ACRA/acra/blob/master/src/main/java/org/acra/ACRA.java#L267

You need to lock your DB copy in some manner. Eg  creating some file system marker indicating copy underway. Though a *reasonably* strong mitigation is to check the processName and only proceed if it's your default process and it's the first time you have run..

**Comment by kaiwinter** [comment]
Ah I see. That was introduced in 4.8.2. Thank you for your suggestions, should help me make this working :-)
