### ISSUE TITLE
Android 4.0.4 can not send report

### ISSUE THREAD

**Issue by xinmeng1** [ACRA/acra#385]
1. Configure: (the configuration work on Android 5.1.1)

@ReportsCrashes(
        formUri = "",
        reportType = HttpSender.Type.JSON,
        httpMethod = HttpSender.Method.POST,
        formUriBasicAuthLogin = "",
        formUriBasicAuthPassword = "",
        //formKey = "", // This is required for backward compatibility but not used
        customReportContent = {
                ReportField.APP_VERSION_CODE,
                ReportField.APP_VERSION_NAME,
                ReportField.ANDROID_VERSION,
                ReportField.PACKAGE_NAME,
                ReportField.REPORT_ID,
                ReportField.BUILD,
                ReportField.STACK_TRACE,
                ReportField.LOGCAT,
                ReportField.CUSTOM_DATA
        }/*,
        mode = ReportingInteractionMode.TOAST,
        resToastText = R.string.toast_crash*/
)

2. The log

03-03 15:56:50.730 16527-16564/uk.co.emx2.acra_demo:acra E/ACRA: Failed to send crash report for /data/data/uk.co.emx2.acra_demo/app_ACRA-approved/2016-03-03T15:56:49.920+0000.stacktrace
                                                               **  org.acra.sender.ReportSenderException: Error while sending JSON report via Http POST**
                                                                     at org.acra.sender.HttpSender.send(HttpSender.java:236)
                                                                     at org.acra.sender.ReportDistributor.sendCrashReport(ReportDistributor.java:102)
                                                                     at org.acra.sender.ReportDistributor.distribute(ReportDistributor.java:70)
                                                                     at org.acra.sender.SenderService.onHandleIntent(SenderService.java:69)
                                                                     at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                     at android.os.Looper.loop(Looper.java:137)
                                                                     at android.os.HandlerThread.run(HandlerThread.java:60)
                                                                  **Caused by: java.net.SocketException: Socket is closed**
                                                                     at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.checkOpen(OpenSSLSocketImpl.java:262)
                                                                     at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:273)
                                                                     at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:257)
                                                                     at libcore.net.http.HttpConnection.setupSecureSocket(HttpConnection.java:210)
                                                                     at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.makeSslConnection(HttpsURLConnectionImpl.java:477)
                                                                     at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.connect(HttpsURLConnectionImpl.java:441)
                                                                     at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java:282)
                                                                     at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java:232)
                                                                     at libcore.net.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:80)
                                                                     at libcore.net.http.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:164)
                                                                     at org.acra.util.HttpRequest.send(HttpRequest.java:128)
                                                                     at org.acra.sender.HttpSender.send(HttpSender.java:233)
                                                                     at org.acra.sender.ReportDistributor.sendCrashReport(ReportDistributor.java:102) 
                                                                     at org.acra.sender.ReportDistributor.distribute(ReportDistributor.java:70) 
                                                                     at org.acra.sender.SenderService.onHandleIntent(SenderService.java:69) 
                                                                     at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                     at android.os.Looper.loop(Looper.java:137) 
                                                                     at android.os.HandlerThread.run(HandlerThread.java:60)

**Comment by xinmeng1** [comment]
I fount the reason is the SSL. I change the formUri = "", from **https ** to **http**, it works. So is there any more configuration on the old android os version?

**Comment by william-ferguson-au** [comment]
I don't understand your question.
NB you don't mention which version of ACRA you are using.
And you didn't show you formUri.

**Comment by xinmeng1** [comment]
I use the latest version of ACRA 4.8.2. Android Version 4.0.4
When use the https as follows:
`formUri = "https://mengxin.cloudant.com/acra-iclockin/_design/acra-storage/_update/report"` 
I will get the exception above. 
After I change to http as follows:
`formUri = "http://mengxin.cloudant.com/acra-iclockin/_design/acra-storage/_update/report",`
It works well.

(But when I use it in Android 5.1.1, this exception doesn't occur both of two choices.)

**Comment by william-ferguson-au** [comment]
It is likely that the Server is closing the socket on the connection.
See http://stackoverflow.com/questions/24620953/android-error-java-net-socketexception-socket-closed

The reason for the differences between the 2 versions of Android could well be down to different default socket timeouts. You can test this by setting the socket timeout as per
https://github.com/ACRA/acra/wiki/Report-Destinations#adjusting-the-socket-timeout

**Comment by mjsheng** [comment]
Did the problem be solved？ I met the same problem

**Comment by mjsheng** [comment]
大哥你是中国人吧

**Comment by xmeng1** [comment]
@mjsheng  不好意思～ 好久不用这个，不清楚啦
