### ISSUE TITLE
Proguard rule from AAR not applied

### ISSUE THREAD

**Issue by koral--** [ACRA/acra#397]
When using proguard ACRA 4.8.2 fails with the following exception.
```java
W/ACRA: Could not construct ReportSender from class a.a.b
                                         java.lang.InstantiationException: class a.a.b has no zero argument constructor
                                             at java.lang.Class.newInstance(Class.java:1641)
                                             at org.acra.sender.SenderService.getSenderInstances(SenderService.java:84)
                                             at org.acra.sender.SenderService.onHandleIntent(SenderService.java:45)
                                             at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                             at android.os.Looper.loop(Looper.java:145)
                                             at android.os.HandlerThread.run(HandlerThread.java:61)
                                          Caused by: java.lang.NoSuchMethodException: <init> []
                                             at java.lang.Class.getConstructor(Class.java:531)
                                             at java.lang.Class.getDeclaredConstructor(Class.java:510)
                                             at java.lang.Class.newInstance(Class.java:1639)
                                             at org.acra.sender.SenderService.getSenderInstances(SenderService.java:84) 
                                             at org.acra.sender.SenderService.onHandleIntent(SenderService.java:45) 
                                             at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65) 
                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                             at android.os.Looper.loop(Looper.java:145) 
                                             at android.os.HandlerThread.run(HandlerThread.java:61) 
```
Without proguard it is working correctly, similarly when I manually add this proguard rule: https://github.com/ACRA/acra/blob/master/src/main/proguard/proguard.cfg#L19
So for some reason that rule from AAR is not applied. It looks like other rules are applied, eg. this: `
-keepattributes SourceFile,LineNumberTable` because there are line numbers in stacktraces.
Relevant fragments of `build.gradle` files:
```
classpath 'com.android.tools.build:gradle:1.5.0'
proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
buildToolsVersion "23.0.2"
compile 'ch.acra:acra:4.8.2'
```

Contents of `proguard-rules.pro`:
```
#okio
-dontwarn okio.**

#retrolambda
-dontwarn javax.**
-dontwarn java.lang.invoke.**

#butterknife 7.0.1
-keep class butterknife.** { *; }
-dontwarn butterknife.internal.**
-keep class **$$ViewBinder { *; }

-keepclasseswithmembernames class * {
    @butterknife.* <fields>;
}

-keepclasseswithmembernames class * {
    @butterknife.* <methods>;
}

# RxJava 1.1.1
-dontwarn sun.misc.**

-keepclassmembers class rx.internal.util.unsafe.*ArrayQueue*Field* {
   long producerIndex;
   long consumerIndex;
}

-keepclassmembers class rx.internal.util.unsafe.BaseLinkedQueueProducerNodeRef {
    rx.internal.util.atomic.LinkedQueueNode producerNode;
}

-keepclassmembers class rx.internal.util.unsafe.BaseLinkedQueueConsumerNodeRef {
    rx.internal.util.atomic.LinkedQueueNode consumerNode;
}

-keep class rx.schedulers.Schedulers {
    public static <methods>;
}
-keep class rx.schedulers.ImmediateScheduler {
    public <methods>;
}
-keep class rx.schedulers.TestScheduler {
    public <methods>;
}
-keep class rx.schedulers.Schedulers {
    public static ** test();
}

#ACRA
-keep public class * implements org.acra.sender.ReportSenderFactory { public <methods>; }
```

**Comment by william-ferguson-au** [comment]
What ReportSender are you using?
Ie what's your ACRA config?

**Comment by koral--** [comment]
Application class fragments:
```
@ReportsCrashes(reportSenderFactoryClasses = {HockeySenderFactory.class},
		sendReportsInDevMode = false,
		deleteOldUnsentReportsOnApplicationStart = BuildConfig.DELETE_OLD_UNSENT_REPORTS_ON_APPLICATION_START,
		formUri = BuildConfig.HOCKEY_APP_ID)
(...)
	public void onCreate() {
		ACRA.init(this);
(...)
```
`HockeySenderFactory`:
```
public class HockeySenderFactory implements ReportSenderFactory {

	@NonNull
	@Override
	public ReportSender create(final Context context, final ACRAConfiguration config) {
		return new HockeySender(config.formUri());
	}
}
```

**Comment by william-ferguson-au** [comment]
So, is your Gradle config setup to merge in Proguard from libraries?
That is how that Proguard line should end up there by default.
Otherwise you need to add it manually.

**Comment by koral--** [comment]
I have not set any option whether consumer proguard rules from library are merged or not. So default setting should be applied, and it looks like they are, except that one final line.
This is the content of 'build/intermediates/exploded-aar/ch.acra/acra/4.8.2/proguard.txt':
```
#ACRA specifics
# Restore some Source file names and restore approximate line numbers in the stack traces,
# otherwise the stack traces are pretty useless
-keepattributes SourceFile,LineNumberTable

# ACRA needs "annotations" so add this...
# Note: This may already be defined in the default "proguard-android-optimize.txt"
# file in the SDK. If it is, then you don't need to duplicate it. See your
# "project.properties" file to get the path to the default "proguard-android-optimize.txt".
-keepattributes *Annotation*

# Keep all the ACRA classes
-keep class org.acra.** { *; }

# Don't warn about removed methods from AppCompat
-dontwarn android.support.v4.app.NotificationCompat*
```

**Comment by koral--** [comment]
I've just downloaded AAR directly from maven central:
http://search.maven.org/remotecontent?filepath=ch/acra/acra/4.8.2/acra-4.8.2.aar
and there is no that final line in `proguard.txt` inside AAR.

**Comment by william-ferguson-au** [comment]
Hm, not sure what happened. I thought replied to this yesterday.
The change you are after is https://github.com/ACRA/acra/issues/372
But that was after 4.8.2

So either take the head, or wait for 4.8.3 which I am hoping to release within the next week.
