### ISSUE TITLE
Java.lang.IllegalStateException: TrustManagerFactory is not initialized.

### ISSUE THREAD

**Issue by maciej-miszczak** [ACRA/acra#402]
Android 5.0.2
ACRA 4.8.4, run from source (in app\src\main\java\org\acra etc.)

Config:
@ReportsCrashes(
        formUri = "https://XXX.php",
        mode = ReportingInteractionMode.TOAST,
        resToastText = R.string.str_acra_crash_report_info)
Init: just ACRA.init(this) in App.onCreate().

Getting an error:
java.lang.IllegalStateException: TrustManagerFactory is not initialized
at com.android.org.conscrypt.TrustManagerFactoryImpl.engineGetTrustManagers(TrustManagerFactoryImpl.java:77)
at javax.net.ssl.TrustManagerFactory.getTrustManagers(TrustManagerFactory.java:219)
at org.acra.util.HttpRequest.send(HttpRequest.java:100)
at org.acra.sender.HttpSender.send(HttpSender.java:233)
at org.acra.sender.ReportDistributor.sendCrashReport(ReportDistributor.java:102)
at org.acra.sender.ReportDistributor.distribute(ReportDistributor.java:70)
at org.acra.sender.SenderService.onHandleIntent(SenderService.java:69)
at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by william-ferguson-au** [comment]
Do you want to supply a PR with the fix?

**Comment by maciej-miszczak** [comment]
Heh, I was just typing, that if I knew how to do it, I would do it with pleasure. :)
Checked, works:
if (config.keyStoreFactory() != null) {
	tmf.init(config.keyStoreFactory().create(context));
} else {
	tmf.init((KeyStore) null);
}

**Comment by maciej-miszczak** [comment]
I would be happy as hell now, if I didn't get a "Trust anchor for certification path not found." error. Damn.

**Comment by maciej-miszczak** [comment]
Hmm... Probably should be in an opposite order, just to stick to some good practices: (== null) first, then "else". :)

**Comment by F43nd1r** [comment]
That's all kinda my fault, so I'm happy to fix it.
