### ISSUE TITLE
ACRA is crashing on Kitkat

### ISSUE THREAD

**Issue by alemiser** [ACRA/acra#430]
Running  apk on android 5.1.1 works without issues.
Running same APK with ARCA on kitkt with Dalvik cause crash immediately because ARCA init failed.

```
E/dalvikvm(11066): Could not find class 'org.acra.log.AndroidLogDelegate', referenced from method org.acra.ACRA.<clinit>
W/dalvikvm(11066): VFY: unable to resolve new-instance 9562 (Lorg/acra/log/AndroidLogDelegate;) in Lorg/acra/ACRA;
E/dalvikvm(11066): Could not find class 'org.acra.config.ConfigurationBuilder', referenced from method org.acra.ACRA.getNewDefaultConfig
W/dalvikvm(11066): VFY: unable to resolve new-instance 9552 (Lorg/acra/config/ConfigurationBuilder;) in Lorg/acra/ACRA;
E/dalvikvm(11066): Could not find class 'org.acra.config.ConfigurationBuilder', referenced from method org.acra.ACRA.init
W/dalvikvm(11066): VFY: unable to resolve new-instance 9552 (Lorg/acra/config/ConfigurationBuilder;) in Lorg/acra/ACRA;
E/dalvikvm(11066): Could not find class 'org.acra.legacy.ReportMigrator', referenced from method org.acra.ACRA.init
W/dalvikvm(11066): VFY: unable to resolve new-instance 9560 (Lorg/acra/legacy/ReportMigrator;) in Lorg/acra/ACRA;
E/dalvikvm(11066): Could not find class 'org.acra.util.ApplicationStartupProcessor', referenced from method org.acra.ACRA.init
W/dalvikvm(11066): VFY: unable to resolve new-instance 9583 (Lorg/acra/util/ApplicationStartupProcessor;) in Lorg/acra/ACRA;
E/dalvikvm(11066): Could not find class 'org.acra.ACRA$1', referenced from method org.acra.ACRA.init
W/dalvikvm(11066): VFY: unable to resolve new-instance 9517 (Lorg/acra/ACRA$1;) in Lorg/acra/ACRA;
W/dalvikvm(11066): VFY: unable to resolve exception class 9551 (Lorg/acra/config/ACRAConfigurationException;)
W/dalvikvm(11066): VFY: unable to find exception handler at addr 0xec
W/dalvikvm(11066): VFY:  rejected Lorg/acra/ACRA;.init (Landroid/app/Application;Lorg/acra/config/ACRAConfiguration;Z)V
W/dalvikvm(11066): VFY:  rejecting opcode 0x0d at 0x00ec
W/dalvikvm(11066): VFY:  rejected Lorg/acra/ACRA;.init (Landroid/app/Application;Lorg/acra/config/ACRAConfiguration;Z)V
W/dalvikvm(11066): Verifier rejected class Lorg/acra/ACRA;
W/dalvikvm(11066): threadid=1: thread exiting with uncaught exception (group=0x416d2e18)
E/ActivityManager(  727): App crashed! Process: com.comtechtel.finderkit.locationagent
E/AndroidRuntime(11066): FATAL EXCEPTION: main
E/AndroidRuntime(11066): Process: com.comtechtel.finderkit.locationagent, PID: 11066
E/AndroidRuntime(11066): java.lang.VerifyError: org/acra/ACRA
E/AndroidRuntime(11066): 	at com.locationtoolkit.locationagent.ServiceApplication.onCreate(ServiceApplication.java:34)
E/AndroidRuntime(11066): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1020)
E/AndroidRuntime(11066): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5154)
E/AndroidRuntime(11066): 	at android.app.ActivityThread.access$1500(ActivityThread.java:156)
E/AndroidRuntime(11066): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1418)
E/AndroidRuntime(11066): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(11066): 	at android.os.Looper.loop(Looper.java:157)
E/AndroidRuntime(11066): 	at android.app.ActivityThread.main(ActivityThread.java:5872)
E/AndroidRuntime(11066): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(11066): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(11066): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:858)
E/AndroidRuntime(11066): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674)
E/AndroidRuntime(11066): 	at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager(  727):   Force finishing activity com.comtechtel.finderkit.locationagent/com.locationtoolkit.locationagent.ServiceActivity
```

**Comment by william-ferguson-au** [comment]
So the **exact ** same APK (not a rebuilt apk) deployed on 5.1.1 is throwing verification errors on android 4.4? I find that extremely hard to believe.

See http://stackoverflow.com/a/2518002/493682

**Comment by alemiser** [comment]
Just verified this, uninstalled and re-installed on both devices.
Samsung runs 5.1.1 starts without error.
Htc running 4.4.2 crash immediately with the same logcat output...

**Comment by william-ferguson-au** [comment]
So the question is: are you deploying the **_exact_** same APK to both devices?
Or are you building the APK for each device.

**Comment by alemiser** [comment]
It was exactly the same apk.
The release apk was build with intent to distribute to tester inside the company.
We tried to do a quick test prior to ship the said apk.
Succeeded with testing on all 3 devs in house except for one developer that had the older HTC device with kitkat.
We also verified this on an older Samsung with 4.4.2 as well.
So I guaranteed that it was the same exact apk file that was installed on all the devices.

**Comment by F43nd1r** [comment]
1. Which build method do you use? Please add your build script (build.gradle for gradle)
2. If you have access to a device with Kitkat and ART support (I believe switching was only possible on 4.4.4), please try it with ART enabled.

**Comment by william-ferguson-au** [comment]
This is almost certainly a multidex issue.

The top 4 answers on StackOverflow are:
http://stackoverflow.com/questions/29033800/noclassdeffounderror-below-sdk-21
http://stackoverflow.com/questions/26655541/multidex-noclassdeffound-error
http://stackoverflow.com/questions/32697460/android-studio-e-dalvikvm-could-not-find-class-databasehelper-referenced-fr
http://stackoverflow.com/questions/27340058/android-multidex-and-support-libraries

**Comment by alemiser** [comment]
The links were very helpful.
The only change I had to make is to extend from MultiDexApplication instead of Application.
It is running normally on kitkat now.

Thanks so much!
public class ServiceApplication extends MultiDexApplication {
    @Override
    public void onCreate() {
        // The following line triggers the initialization of ACRA
        super.onCreate();
        ACRA.init(this);
    }

}
