### ISSUE TITLE
create Repport getErrorReporter error

### ISSUE THREAD

**Issue by blade3** [ACRA/acra#469]
Hi,

I have an error with ACRA 4.9.0. I'm trying to use this to generate stackTrace in CATCH.

You will FIND:   

    1. Dependency call
    2. StackTrace
    3. IMPORT & ReportsCrashes
    4. Config init + throwing exception

_**Dependency call**_
`compile 'ch.acra:acra:4.9.0'`

_**StackTrace**_

    --------- beginning of crash 06-14 10:44:07.045 24277-24277/com.empire E/AndroidRuntime: FATAL EXCEPTION: main
                        Process: com.empire, PID: 24277
                        java.lang.RuntimeException: Unable to start activity ComponentInfo{com.empire/com.empire.HomeActivity}: java.lang.IllegalStateException: Cannot access ErrorReporter before ACRA#init
                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                        at android.app.ActivityThread.-wrap11(ActivityThread.java)
                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                        at android.os.Handler.dispatchMessage(Handler.java:102)
                        at android.os.Looper.loop(Looper.java:148)
                        at android.app.ActivityThread.main(ActivityThread.java:5417)
                        at java.lang.reflect.Method.invoke(Native Method)
                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
              Caused by: java.lang.IllegalStateException: Cannot access ErrorReporter before ACRA#init
                        at org.acra.ACRA.getErrorReporter(ACRA.java:331)
                        at com.empire.HomeActivity.setupOCR(HomeActivity.java:132)
                        at com.empire.HomeActivity.onCreate(HomeActivity.java:260)
                        at android.app.Activity.performCreate(Activity.java:6251)
                        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                        at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                        at android.os.Handler.dispatchMessage(Handler.java:102) 
                        at android.os.Looper.loop(Looper.java:148) 
                        at android.app.ActivityThread.main(ActivityThread.java:5417) 
                        at java.lang.reflect.Method.invoke(Native Method) 
                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) `

_**IMPORT & ReportsCrashes**_

    import org.acra.ACRA;
    import org.acra.ReportField;
    import org.acra.ReportingInteractionMode;
    import org.acra.annotation.ReportsCrashes;
    import org.acra.sender.HttpSender;

    @ReportsCrashes(
        formUri = "https://xxxxxx.cloudant.com/acra-xxxxx/_design/acra-storage/_update/report",
        reportType = HttpSender.Type.JSON,
        httpMethod = HttpSender.Method.POST,
        formUriBasicAuthLogin = "-------",
        formUriBasicAuthPassword = "------------------",
        //formKey = "", // This is required for backward compatibility but not used
        customReportContent = {
                ReportField.APP_VERSION_CODE,
                ReportField.APP_VERSION_NAME,
                ReportField.ANDROID_VERSION,
                ReportField.PACKAGE_NAME,
                ReportField.REPORT_ID,
                ReportField.BUILD,
                ReportField.STACK_TRACE
        },
        mode = ReportingInteractionMode.TOAST,
        resToastText = R.string.crash_toast_text
    )

_**Config init + throwing exception**_

    public class HomeActivity extends AppCompatActivity {

    @Override

    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        ACRA.init(getApplication());
       try {
            throw new NumberFormatException();
        } catch (NumberFormatException e){
            ACRA.getErrorReporter().handleException(e);
        }   
    }

thanks!

**Comment by F43nd1r** [comment]
Are there any other ACRA logs before the crash? If not, enable ACRA.DEV_LOGGING.

BTW: you normally should init ACRA in your application, not your activity. Is there a reason why you don't do that?

**Comment by blade3** [comment]
@F43nd1r , thanks for reply.. don't know where I should place  init if its not in the primary Activity..

Also, I got A msg after DEV_LOGGING WAS ENABLED:

     06-14 12:49:33.854 18675-18675/com.empire E/ACRA: ACRA#init(Application) called but no ReportsCrashes annotation on Application com.empire

I understand that my ReportsCrashes can't be into my homeActivity.java.

but I don't really know where is my "application" file where I can't init and add my reportsCrashes.. 

(homeActivity.java) is the files loaded by my apps and display the first layout with the onCreate

**Comment by F43nd1r** [comment]
https://github.com/ACRA/acra/wiki/BasicSetup#configure-your-application-class

**Comment by blade3** [comment]
Thanks @F43nd1r. I had misconfigured ACRA at the beginning.

thanks!
