### ISSUE TITLE
How to include HostnameVerifier instance in ACRAConfiguration for self signed certificate ?

### ISSUE THREAD

**Issue by Veeshal** [ACRA/acra#479]
I have added ssl certificate. But for further workin I couldn't find any reference to adding hostnameverifier in ACRAConfiguration.
Below is the error I am receiving while using the ssl certificate. And the same certificate I am able to use it for my other network requests and is working.

`Caused by: javax.net.ssl.SSLPeerUnverifiedException: Hostname <hostname> not verified:`

**Comment by william-ferguson-au** [comment]
What is the stacktrace?

**Comment by Veeshal** [comment]
```
org.acra.sender.ReportSenderException: Error while sending JSON report via Http POST
            at org.acra.sender.HttpSender.send(HttpSender.java:236)
            at org.acra.sender.ReportDistributor.sendCrashReport(ReportDistributor.java:102)
            at org.acra.sender.ReportDistributor.distribute(ReportDistributor.java:70)
            at org.acra.sender.SenderService.onHandleIntent(SenderService.java:69)
            at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:148)
            at android.os.HandlerThread.run(HandlerThread.java:61)
         Caused by: javax.net.ssl.SSLPeerUnverifiedException: Hostname 192.168.1.16 not verified:
            certificate: sha1/xWXGurbCS4aQRL9f3gd136c35HI=
            DN: CN=x360-05
            subjectAltNames: []
            at com.android.okhttp.internal.http.SocketConnector.connectTls(SocketConnector.java:120)
            at com.android.okhttp.Connection.connect(Connection.java:143)
            at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:185)
            at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128)
            at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:341)
            at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
            at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
            at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:437)
            at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:114)
            at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
            at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java)
            at org.acra.util.HttpRequest.send(HttpRequest.java:142)
            at org.acra.sender.HttpSender.send(HttpSender.java:233)
            	... 7 more
```

**Comment by william-ferguson-au** [comment]
So you are using an SSL cert that you have generated for hostname "192.168.1.16" ??
That is not a hostname, it is an IP address.

**Comment by Veeshal** [comment]
I am specifying System name, "x360-05" to verify using the code mentioned in link below. It works using HttpsURLConnection. Even the stacktrace mentions the name. There is a provision for adding it in Retrofit as well. I not able to find a way to add it in ACRA manual configuration.


https://developer.android.com/training/articles/security-ssl.html#CommonHostnameProbs.

**Comment by F43nd1r** [comment]
The page itself states that modifications at this point are very dangerous, so I'd rather have a different solution. Have you already read this? http://stackoverflow.com/a/30745599/4388512

**Comment by william-ferguson-au** [comment]
There is no intention to allow ACRA to use HostNameVerifier to water down security. Closing.
