### ISSUE TITLE
ACRA not attempting to send crash report

### ISSUE THREAD

**Issue by deshant** [ACRA/acra#490]
Followed basic setup guide and created a Tracepot account for backend. 
I see this in logcat and nothing is seen on Tracepot.

Added permissions for Internet and LOG access in manifest, annotation over Application class has only 1 field - formUri = "https://collector.tracepot.com/xxxxxxxxx" 

Created a deliberate NPE when in login fragment, that is of second Activity (after splash). I see nothing related to ACRA even attempting to send logs, the last line of following log snippet is the end. Really sorry to create issue if the problem is at my end,  am I missing something?

```
08-06 19:55:54.803 24181-24181/com.austinmachines.austin E/ACRA: ACRA caught a NullPointerException for com.austinmachines.austin
                                                                 java.lang.NullPointerException: Attempt to invoke virtual method 'float android.location.Location.getAccuracy()' on a null object reference
                                                                     at com.austinmachines.austin.fragments.LoginFragment$1.onClick(LoginFragment.java:111)
                                                                     at android.view.View.performClick(View.java:5280)
                                                                     at android.view.View$PerformClick.run(View.java:21239)
                                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                     at android.os.Looper.loop(Looper.java:234)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5526)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
08-06 19:55:55.036 24181-24181/com.austinmachines.austin I/Process: Sending signal. PID: 24181 SIG: 9
```

EDIT: I haved ACRA added jar in libs v4.9.0
Android version 6.0.1, Device: Xperia Z3+
Using Android Studio 2.0 on Win 10

**Comment by F43nd1r** [comment]
Don't use the jar. ACRA is shipped as an aar since 4.7 and won't work correctly as a jar.
If you are using android studio you are probably also using gradle. If so, just add the dependency in your build.gradle and gradle will resolve the correct file for you.

**Comment by deshant** [comment]
Yes I tried that initially, but due to internet issues I was not able to update support repo, now renamed to local maven repo. Will try via gradle again. Thanks.

**Comment by deshant** [comment]
Maybe it is something with the jar indeed. ACRA did send something after using aar dependency in gradle. Will close the issue now.
