### ISSUE TITLE
ACRA not sending report through URL

### ISSUE THREAD

**Issue by carlosfvieira** [ACRA/acra#497]
Hi, i've configured ACRA as in BasicSetup, but can't get it to work properly.

I can see in logcat that ACRA catches an exception, but nothing happens... ie, POST to my server URL does not happen:

```
D/EnvayaSMS(10456): ACRA init
I/ACRA    (10456): ACRA is enabled for org.envaya.sms, initializing...
E/ACRA    (10456): ACRA caught a RuntimeException for org.envaya.sms
E/ACRA    (10456): java.lang.RuntimeException: Unable to create application org.envaya.sms.App: java.lang.ArithmeticException: divide by zero
E/ACRA    (10456): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4660)
E/ACRA    (10456): 	at android.app.ActivityThread.access$1500(ActivityThread.java:155)
E/ACRA    (10456): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1384)
E/ACRA    (10456): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/ACRA    (10456): 	at android.os.Looper.loop(Looper.java:135)
E/ACRA    (10456): 	at android.app.ActivityThread.main(ActivityThread.java:5376)
E/ACRA    (10456): 	at java.lang.reflect.Method.invoke(Native Method)
E/ACRA    (10456): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/ACRA    (10456): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
E/ACRA    (10456): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
E/ACRA    (10456): Caused by: java.lang.ArithmeticException: divide by zero
E/ACRA    (10456): 	at org.envaya.sms.App.onCreate(App.java:236)
E/ACRA    (10456): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1011)
E/ACRA    (10456): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4657)
E/ACRA    (10456): 	... 9 more
```

Missing something here?
```
@ReportsCrashes(formUri = "<my_server_url>",
                httpMethod = org.acra.sender.HttpSender.Method.POST,
                mode = ReportingInteractionMode.SILENT
               )
public class App extends Application {
    @Override
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(base);
        
        log("ACRA init");
        
        // The following line triggers the initialization of ACRA
        ACRA.init(this);
    }
...
```

Any help would be appreciated. Thanks!

**Comment by F43nd1r** [comment]
Crashes in the application class might not be sent, as a working application class is required to start acras senderservice. Can't tell more without more logs.

**Comment by carlosfvieira** [comment]
Thanks for the feedback... i just configured this as the basic setup instructions...

The exception is being thrown in activity class.

What specific logs do yo need? The only ACRA logs are the ones i posted here...

**Comment by F43nd1r** [comment]
ACRA.DEV_LOGGING = true, post everything that is under the Acra log tag from the start on.

**Comment by carlosfvieira** [comment]
Ok, thanks... i'll get those...

This is exactly what i'm doing: https://github.com/TheMedo/acra_example

ACRA version used: 4.9.0

**Comment by carlosfvieira** [comment]
Here it is:

```
D/ACRA    (12716): Using custom Report Fields
D/ACRA    (12716): ACRA processName='org.envaya.sms'
I/ACRA    (12716): ACRA is enabled for org.envaya.sms, initializing...
D/ACRA    (12716): READ_LOGS granted! ACRA can include LogCat and DropBox data.
D/ACRA    (12716): Writing crash report file /data/data/org.envaya.sms/app_ACRA-unapproved/2016-08-17T19:11:05.781+01:00.stacktrace
D/ACRA    (12716): About to start SenderService
D/ACRA    (12716): READ_LOGS granted! ACRA can include LogCat and DropBox data.
D/ACRA    (12716): Waiting for 2000 millis from 1471457465735 currentMillis=1471457465885
D/ACRA    (12716): Writing crash report file /data/data/org.envaya.sms/app_ACRA-unapproved/2016-08-17T19:11:05.886+01:00-IS_SILENT.stacktrace
D/ACRA    (12716): About to start SenderService
D/ACRA    (12716): onActivityCreated class org.envaya.sms.ui.Main
D/ACRA    (12716): READ_LOGS granted! ACRA can include LogCat and DropBox data.
D/ACRA    (12716): Writing crash report file /data/data/org.envaya.sms/app_ACRA-unapproved/2016-08-17T19:11:05.898+01:00.stacktrace
D/ACRA    (12716): About to start SenderService
D/ACRA    (12716): Waiting for 2000 millis from 1471457465900 currentMillis=1471457465906
D/ACRA    (12716): READ_LOGS granted! ACRA can include LogCat and DropBox data.
D/ACRA    (12716): Writing crash report file /data/data/org.envaya.sms/app_ACRA-unapproved/2016-08-17T19:11:05.908+01:00-IS_SILENT.stacktrace
D/ACRA    (12716): About to start SenderService
E/ACRA    (12716): ACRA caught a RuntimeException for org.envaya.sms
E/ACRA    (12716): java.lang.RuntimeException: Unable to start activity ComponentInfo{org.envaya.sms/org.envaya.sms.ui.Main}: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
E/ACRA    (12716): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2345)
E/ACRA    (12716): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2405)
E/ACRA    (12716): 	at android.app.ActivityThread.access$800(ActivityThread.java:155)
E/ACRA    (12716): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1323)
E/ACRA    (12716): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/ACRA    (12716): 	at android.os.Looper.loop(Looper.java:135)
E/ACRA    (12716): 	at android.app.ActivityThread.main(ActivityThread.java:5376)
E/ACRA    (12716): 	at java.lang.reflect.Method.invoke(Native Method)
E/ACRA    (12716): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/ACRA    (12716): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
E/ACRA    (12716): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
E/ACRA    (12716): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
E/ACRA    (12716): 	at org.envaya.sms.ui.Main.onCreate(Main.java:33)
E/ACRA    (12716): 	at android.app.Activity.performCreate(Activity.java:6021)
E/ACRA    (12716): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
E/ACRA    (12716): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
E/ACRA    (12716): 	... 10 more
D/ACRA    (12716): Building report
D/ACRA    (12716): READ_LOGS granted! ACRA can include LogCat and DropBox data.
D/ACRA    (12716): Writing crash report file /data/data/org.envaya.sms/app_ACRA-unapproved/2016-08-17T19:11:05.930+01:00.stacktrace
D/ACRA    (12716): About to start SenderService
D/ACRA    (12716): Waiting for 2000 millis from 1471457465932 currentMillis=1471457465938
D/ACRA    (12716): Finished waiting for Toast
D/ACRA    (12716): Wait for Toast + worker ended. Kill Application ? false
D/ACRA    (12716): Finished waiting for Toast
D/ACRA    (12716): Wait for Toast + worker ended. Kill Application ? false
D/ACRA    (12716): Finished waiting for Toast
D/ACRA    (12716): Wait for Toast + worker ended. Kill Application ? true
D/ACRA    (12716): Finishing the last Activity prior to killing the Process
D/ACRA    (12716): Finished class org.envaya.sms.ui.Main
D/ACRA    (12744): Using custom Report Fields
D/ACRA    (12744): ACRA processName='org.envaya.sms'
I/ACRA    (12744): ACRA is enabled for org.envaya.sms, initializing...
D/ACRA    (12744): READ_LOGS granted! ACRA can include LogCat and DropBox data.
D/ACRA    (12744): Writing crash report file /data/data/org.envaya.sms/app_ACRA-unapproved/2016-08-17T19:11:08.188+01:00.stacktrace
D/ACRA    (12744): About to start SenderService
D/ACRA    (12744): READ_LOGS granted! ACRA can include LogCat and DropBox data.
D/ACRA    (12744): Waiting for 2000 millis from 1471457468155 currentMillis=1471457468282
D/ACRA    (12744): Writing crash report file /data/data/org.envaya.sms/app_ACRA-unapproved/2016-08-17T19:11:08.283+01:00-IS_SILENT.stacktrace
D/ACRA    (12744): About to start SenderService
D/ACRA    (12744): onActivityCreated class org.envaya.sms.ui.LogView
D/ACRA    (12744): onActivityStarted class org.envaya.sms.ui.LogView
D/ACRA    (12744): onActivityResumed class org.envaya.sms.ui.LogView
D/ACRA    (12744): Finished waiting for Toast
D/ACRA    (12744): Wait for Toast + worker ended. Kill Application ? false
```

**Comment by F43nd1r** [comment]
Do you use Acra as jar? If so, use the aar or copy the manifest entries fom the aar.

**Comment by carlosfvieira** [comment]
Yes, i use the .jar file. Ok, i'll try that!

**Comment by carlosfvieira** [comment]
Hi @F43nd1r , i tried it now and it works great :) many thanks for your help!

**Comment by padmajarani** [comment]
where can i get acra jar

**Comment by F43nd1r** [comment]
@padmajarani acra should no be used as a jar, use aar instead. There is no jar distribution of recent versions.
