### ISSUE TITLE
Empty report files with size 0 are not deleted when they are failed to be sent

### ISSUE THREAD

**Issue by kboyarshinov** [ACRA/acra#522]
Hello. 

We had another issue while trying to recover the reports from one device. At first we found that some reports are being rejected by CouchDB server with 400 response. Later we found that some reports in `app_ACRA-approved` folder in application internal storage had 0 bytes size. Probably those files were created but writing to them failed. And the problem was that they are not deleted after sending failed.

Having 0 sized reports that are not deleted lead to situation when no reports are sent at all. Since there is a limit of 5 reports to send having 5 empty non-deleted reports blocks others from being sent.
Deleting them manually from device storage solved the problem.

Steps to reproduce:

1. go to application internal storage: `adb shell run-as <package_name>`
2. go to `app_ACRA-approved`: `cd app_ACRA-approved`
3. create empty file: `echo "" > testreport.stacktrace`
4. launch the application with ACRA enabled as: `ACRA.init(application, acraConfiguration);`
5. See the stacktrace:
```
E/ACRA: Failed to send crash report for /data/data/<package_name>/app_ACRA-approved/testreport.stacktrace
                                                           org.acra.sender.ReportSenderException: Error while sending JSON report via Http POST
                                                               at org.acra.sender.HttpSender.send(HttpSender.java:239)
                                                               at org.acra.sender.ReportDistributor.sendCrashReport(ReportDistributor.java:102)
                                                               at org.acra.sender.ReportDistributor.distribute(ReportDistributor.java:70)
                                                               at org.acra.sender.SenderService.onHandleIntent(SenderService.java:69)
                                                               at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
                                                               at android.os.Handler.dispatchMessage(Handler.java:110)
                                                               at android.os.Looper.loop(Looper.java:193)
                                                               at android.os.HandlerThread.run(HandlerThread.java:61)
                                                            Caused by: java.io.IOException: Host returned error code 400
                                                               at org.acra.util.HttpRequest.send(HttpRequest.java:181)
                                                               at org.acra.sender.HttpSender.send(HttpSender.java:235)
                                                               at org.acra.sender.ReportDistributor.sendCrashReport(ReportDistributor.java:102) 
                                                               at org.acra.sender.ReportDistributor.distribute(ReportDistributor.java:70) 
                                                               at org.acra.sender.SenderService.onHandleIntent(SenderService.java:69) 
                                                               at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65) 
                                                               at android.os.Handler.dispatchMessage(Handler.java:110) 
                                                               at android.os.Looper.loop(Looper.java:193) 
                                                               at android.os.HandlerThread.run(HandlerThread.java:61) 
```

I think ACRA client needs to check if report file is empty and delete it without trying to send. Maybe simple change in `ReportDistributor` like that:

```
    public void distribute(@NonNull File reportFile) {
        ...

        if (reportFile.length() == 0) {
            deleteFile(reportFile);
            return;
        }

        ...
    }

```

Let me know what you think.
Thank you.

**Comment by william-ferguson-au** [comment]
I think that any HttpClient exception, ie any status between 400 <= HttpStatus < 500 should cause the request to be discarded (which means the report will be deleted).

**Comment by milesich** [comment]
I agree with @william-ferguson-au but I would like to suggest to not discard reports and retry again on these two error codes:

```
408 Request Timeout
429 Too Many Requests
```

**Comment by william-ferguson-au** [comment]
Agree with 408. 

But 429 means that the client has been sending too many error reports. Do we really want to keep this report so we can send it again?

**Comment by milesich** [comment]
I am trying to think about a possible scenario where would client get 429. ACRA will limit the number of reports sent on start. I could only think about when there is a large number of users behind a proxy with 1 IP address. Maybe 429 is not needed after all.

**Comment by kboyarshinov** [comment]
I just realized that empty reports were causing Comparator issue #516. I checked and calling `lastModified()` on empty file returned `1476264430000` which is year 48750. 
It means before sorting reports in `ReportLocator` they should be filtered to exclude empty files.

> any status between 400 <= HttpStatus < 500 should cause the request to be discarded
agree with that and 408 exclusion

**Comment by F43nd1r** [comment]
Once we switch to json as proposed in #517, we should probably just delete files which do not contain valid json. This would include empty files.

**Comment by william-ferguson-au** [comment]
Who wants to do the PR for treating any 4** status (except for 408) as a client failure that should be logged with message discarded (and file deleted).

**Comment by kboyarshinov** [comment]
@william-ferguson-au do intend to release this change in 4.9.2 any time soon?

**Comment by F43nd1r** [comment]
Unless there is something critical the next version will probably take some time. But you can grab a snapshot using this:

```groovy
repositories {
    maven {url = "https://oss.jfrog.org/libs-snapshot/" }
    //your other repos
}
```
```groovy
dependencies {
    compile 'com.faendir:acra:4.9.2-SNAPSHOT'
    //your other deps
}
```

**Comment by kboyarshinov** [comment]
@F43nd1r Thank you
