### ISSUE TITLE
 java.lang.NoSuchMethodError: java.lang.String.isEmpty

### ISSUE THREAD

**Issue by ckhmer1** [ACRA/acra#531]
Hi,
I'm using ACRA for bug reporting.
ACRA is crashing when I use my device (Samsung GT-I5500 with Android 2.2, API8) with the following exception:

E/AndroidRuntime: FATAL EXCEPTION: main
java.lang.NoSuchMethodError: java.lang.String.isEmpty
at org.acra.collector.ReflectionCollector.collectConstants(ReflectionCollector.java:53)
at org.acra.collector.ReflectionCollector.collectConstants(ReflectionCollector.java:111)
at org.acra.collector.CrashReportDataFactory.createCrashData(CrashReportDataFactory.java:309)
at org.acra.builder.ReportExecutor.execute(ReportExecutor.java:170)
at org.acra.builder.ReportBuilder.build(ReportBuilder.java:150)
at org.acra.ErrorReporter.handleSilentException(ErrorReporter.java:285)
.....

Could you please fix this issue?
Thanks

**Comment by william-ferguson-au** [comment]
What version of ACRA?

**Comment by ckhmer1** [comment]
I'm sorry, forgot my report. 
This bug is fixed on version 4.9.1.
Thanks again

**Comment by F43nd1r** [comment]
Just for reference: This was fixed in #15eea11
