### ISSUE TITLE
Crash on sending report

### ISSUE THREAD

**Issue by Ajtak** [ACRA/acra#541]
I want reporting crash in new version of Acra 
```
 Failed to send crash reports for /data/data/[...]/app_ACRA-approved/2017-01-23T22:41:28.770+01:00-IS_SILENT.stacktrace
                                                                        java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String[] org.acra.model.Element.flatten()' on a null object reference
                                                                            at org.acra.sender.HttpSender.remap(HttpSender.java:254)
                                                                            at org.acra.sender.HttpSender.send(HttpSender.java:221)
                                                                            at org.acra.sender.ReportDistributor.sendCrashReport(ReportDistributor.java:107)
                                                                            at org.acra.sender.ReportDistributor.distribute(ReportDistributor.java:74)
                                                                            at org.acra.sender.SenderService.onHandleIntent(SenderService.java:74)
                                                                            at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                            at android.os.Looper.loop(Looper.java:194)
                                                                            at android.os.HandlerThread.run(HandlerThread.java:61)
```

My Application header is:
```
@ReportsCrashes(formUri = "http://[...]/post.php",
        mode = ReportingInteractionMode.TOAST,
        httpMethod = HttpSender.Method.POST,
        resToastText = R.string.crash_toast_text)
```
and onCreate method is:
```
    @Override
    public void onCreate() {

        ACRA.init(this);
        super.onCreate();
    }
```

Version:

> compile 'ch.acra:acra:4.9.2'

Please fix it

**Comment by F43nd1r** [comment]
You can access a compiled version with the fix under 

    compile 'com.faendir:acra:4.9.3-SNAPSHOT'

repository:

    maven {url = "https://oss.jfrog.org/libs-snapshot/" }

Note that this is my working directory and may not always contain a working version, but its a nice temporary solution until a new release is made.

**Comment by DenisZhadan** [comment]
I think wrong code:
```
    public void onCreate() {
        ACRA.init(this);
        super.onCreate();
    }
```

must be: 
```
    public void onCreate() {
        super.onCreate();
        ACRA.init(this);     
    }
```

**Comment by StanislavChumarin** [comment]
This does not help. Still getting ACRA crashes trying to send report.

**Comment by F43nd1r** [comment]
The ordering of the `super` call and the `init` call do not matter. In fact we recommend to load ACRA even earlier, in `attachBaseContext`, see https://github.com/ACRA/acra/wiki/BasicSetup#configuring-acra---declaratively

**Comment by DorianScholz** [comment]
Ran into this bug as well.
Tried to work around it by using the 4.9.3 SNAPSHOT, but it does not seem to be available anymore.
Are there any other workarounds?
Or will 4.9.3 with the fix be released soon?

**Comment by F43nd1r** [comment]
The snapshot is still up. There is currently no schedule for a release.

**Comment by DorianScholz** [comment]
You're right, my mistake!
The snapshot is working fine, thanks!

**Comment by czjvic** [comment]
For me the snapshot doesn't work too. So I use an older version. This is bug only in version 4.9.2. So I include version 4.9.1 and it works well.
