### ISSUE TITLE
 java.lang.VerifyError: org/acra/ACRA when Using the support library of android version with 25.1.1

### ISSUE THREAD

**Issue by kumar5572** [ACRA/acra#547]
Could not find class 'org.acra.log.AndroidLogDelegate', referenced from method org.acra.ACRA.<clinit>
java.lang.VerifyError: org/acra/ACRA
at GlobalApp.onCreate(GlobalApp.java:57)
 at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4541)
at android.app.ActivityThread.access$1500(ActivityThread.java:151)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1381)
at android.os.Handler.dispatchMessage(Handler.java:110)
at android.os.Looper.loop(Looper.java:193)
 at android.app.ActivityThread.main(ActivityThread.java:5292)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
at dalvik.system.NativeStart.main(Native Method)

If i'm using the support library version with 23.1.1 its working fine

**Comment by F43nd1r** [comment]
While ACRA was built for 23.1.1, I could not observe any problems using 25.1.1
