### ISSUE TITLE
acra cause : Could not find method android.media.MediaCodecList.<init>

### ISSUE THREAD

**Issue by cdma3105** [ACRA/acra#549]
In my app, there is a MediaPlayer field.

my gradle script:
dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.android.support:appcompat-v7:25.0.1'
    compile 'com.google.android.gms:play-services-appindexing:9.8.0'
    compile 'com.android.support:design:25.0.1'
    compile 'com.android.support:support-v4:25.0.1'
    compile 'com.android.support:support-vector-drawable:25.0.1'
    debugCompile 'com.squareup.leakcanary:leakcanary-android:1.5'
    releaseCompile 'com.squareup.leakcanary:leakcanary-android-no-op:1.5'

I make a exception by: int ddd = 123/0;

then get  the error stack info:
....
I/dalvikvm: Could not find method android.media.MediaCodecList.<init>, referenced from method org.acra.collector.MediaCodecListCollector.collectMediaCodecList
W/dalvikvm: VFY: unable to resolve direct method 1097: Landroid/media/MediaCodecList;.<init> (I)V
D/dalvikvm: VFY: replacing opcode 0x70 at 0x001e
I/System: Failed to destroy process 7149
I/System: libcore.io.ErrnoException: kill failed: ESRCH (No such process)
              at libcore.io.Posix.kill(Native Method)
              at libcore.io.ForwardingOs.kill(ForwardingOs.java:86)
              at java.lang.ProcessManager$ProcessImpl.destroy(ProcessManager.java:260)
              at org.acra.collector.LogCatCollector.collectLogCat(LogCatCollector.java:108)
              at org.acra.collector.LogCatCollector.collect(LogCatCollector.java:140)
              at org.acra.collector.CrashReportDataFactory.createCrashData(CrashReportDataFactory.java:132)
              at org.acra.builder.ReportExecutor.execute(ReportExecutor.java:170)
              at org.acra.builder.ReportBuilder.build(ReportBuilder.java:150)
              at org.acra.ErrorReporter.uncaughtException(ErrorReporter.java:267)

**Comment by cdma3105** [comment]
Even in a hello app, get the similar error stack.

**Comment by F43nd1r** [comment]
To me this looks like a broken ROM. Did you test this with an emulator or a real device?

**Comment by cdma3105** [comment]
I tested arca with an emulator. I commented out some code of acra, now It works fine with  emulator and real devices.

**Comment by F43nd1r** [comment]
Which code exactly?

**Comment by cdma3105** [comment]
In CrashReportDataFactory.java line 169: collectors.add(new MediaCodecListCollector());

**Comment by F43nd1r** [comment]
Could you give some information on the device specs? e.g. android version, ROM version etc

**Comment by cczlg** [comment]
I have same question. I test arca with real device.
Smartisan OS v3.2.7
Android version: 4.4.2
Baseband verion:2.0.1-00154-MAAAAANPZM-L
Kernel version：3.4.0-perf-gfb1295d smartcm@hardcomp5 #1

**Comment by F43nd1r** [comment]
@cczlg could you post the full stacktrace of the crash?

**Comment by F43nd1r** [comment]
Outdated - closing

**Comment by pranaysharma** [comment]
Hi I too am getting a similar error on posting a silent NullPointer Exception:
`01-31 18:15:08.835 24953-24953/com.zenithpark.v2.www I/System: Failed to destroy process 25089
01-31 18:15:08.837 24953-24953/com.zenithpark.v2.www I/System: android.system.ErrnoException: kill failed: ESRCH (No such process)
                                                                   at libcore.io.Posix.kill(Native Method)
                                                                   at libcore.io.ForwardingOs.kill(ForwardingOs.java:101)
                                                                   at java.lang.ProcessManager$ProcessImpl.destroy(ProcessManager.java:260)
                                                                   at org.acra.collector.LogCatCollector.collectLogCat(LogCatCollector.java:108)
                                                                   at org.acra.collector.LogCatCollector.collect(LogCatCollector.java:140)
                                                                   at org.acra.collector.CrashReportDataFactory.createCrashData(CrashReportDataFactory.java:132)
                                                                   at org.acra.builder.ReportExecutor.execute(ReportExecutor.java:170)
                                                                   at org.acra.builder.ReportBuilder.build(ReportBuilder.java:150)
                                                                   at org.acra.ErrorReporter.handleSilentException(ErrorReporter.java:288)
                                                                   at com.mypackagename.handleSilentException(MiscUtilities.java:somelinenumber)`
