### ISSUE TITLE
Getting java.lang.IllegalStateException: Cannot access ErrorReporter before ACRA#init Even though ACRA is initialized in attachBaseContext

### ISSUE THREAD

**Issue by nirmalspeed** [ACRA/acra#588]
Hello,
On ACRA 4.9.2, 
I am getting the "java.lang.IllegalStateException: Cannot access ErrorReporter before ACRA#init" exception even though I have  
```
@Override
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(base);
        ACRA.init(this);
    }
```
In my Application.java file. I also verified that the init method in ACRA library is being hit.

I also have the `@ReportCrashes` annotation above my application declaration. 
I followed the BasicSetup for setting this up.

**Comment by F43nd1r** [comment]
Is there anything in the logcat?

**Comment by nirmalspeed** [comment]
```
06-28 11:22:54.094 24559-24683/com.MyApp.wireless W/WebRequest: throwable caught while notifying listener: java.lang.SecurityException: MODE_WORLD_READABLE no longer supported
06-28 11:22:54.095 24559-24683/com.MyApp.wireless I/art: Starting a blocking GC Explicit
06-28 11:22:54.107 24559-24559/com.MyApp.wireless D/[WebRequestDispatcher]: Adding Request to queue : {Censored URL}
06-28 11:22:54.108 24559-24559/com.MyApp.wireless D/TabsNavFragmentActivity: onStart
06-28 11:22:54.134 24559-24683/com.MyApp.wireless I/art: Explicit concurrent mark sweep GC freed 1643(570KB) AllocSpace objects, 0(0B) LOS objects, 40% free, 19MB/32MB, paused 477us total 37.555ms
06-28 11:22:54.139 24559-24683/com.MyApp.wireless W/[WebRequestDispatcher]: throwable caught while executing request: java.lang.IllegalStateException: Cannot access ErrorReporter before ACRA#init
06-28 11:22:54.139 24559-24683/com.MyApp.wireless I/art: Starting a blocking GC Explicit
06-28 11:22:54.166 24559-24683/com.MyApp.wireless I/art: Explicit concurrent mark sweep GC freed 101(7KB) AllocSpace objects, 0(0B) LOS objects, 40% free, 19MB/32MB, paused 396us total 25.350ms
06-28 11:22:54.173 24559-24683/com.MyApp.wireless E/AndroidRuntime: FATAL EXCEPTION: Thread-6
                                                                      Process: com.MyApp.wireless, PID: 24559
                                                                      java.lang.IllegalStateException: Cannot access ErrorReporter before ACRA#init
                                                                          at org.acra.ACRA.getErrorReporter(ACRA.java:316)
                                                                          at com.MyApp.wireless.services.webrequestdispatcher.WebRequestDispatcher$1.run(WebRequestDispatcher.java:98)
```
Right before the crash, I'm opening a URL as the logs mention.

**Comment by F43nd1r** [comment]
Please set `ACRA.DEV_LOGGING = true;` right before `Acra.init` and filter the log for messages with the tag `ACRA`

**Comment by nirmalspeed** [comment]
```
06-28 11:30:34.614 31270-31270/com.MyApp.wireless W/ACRA: Configuration Error - ACRA not started : Class com.MyApp.wireless.MyApp$CrashReportSenderFactory is missing a no-args Constructor.
```
Is what that reveals.
My CrashReportSenderFactory code: 
```
public class CrashReportSenderFactory implements ReportSenderFactory {

		public ReportSender create(Context context, ACRAConfiguration config) {

			return new CrashReportSender();
		}
	}
```

My CrashReportSender:
```
public class CrashReportSender implements ReportSender, WebRequestCallBackListener {

		public CrashReportSender() {
			ACRA.getErrorReporter().putCustomData("crashreporttype", "crash");
		}

		@Override
		public void send(Context context, CrashReportData report) throws ReportSenderException {
			// my implementation
		 }

		@Override
		public void onPostExecute(WebRequest request) {
			//empty
		}
}
```

**Comment by F43nd1r** [comment]
Is your `CrashReportSenderFactory` an inner class?

The problem is here https://github.com/ACRA/acra/blob/master/acra/src/main/java/org/acra/config/ConfigurationBuilder.java#L116. It looks like it can't find a constructor on your class, but it should have a default constructor
As a workaround, add an empty public constructor.

**Comment by nirmalspeed** [comment]
Yes it is an inner class. I'll give that public constructor a try.

**Comment by nirmalspeed** [comment]
I moved it out and it fixed the issue. Thanks!
