### ISSUE TITLE
Manual setup in v5 - combine multiple configs

### ISSUE THREAD

**Issue by MFlisar** [ACRA/acra#610]
I want to update my acra version to v5 and am currently setting up everything in code without annotations.

Now I want so setup 3 configs:

	CoreConfiguration coreConfig = new CoreConfigurationBuilder(app)
		// ...
		.build();
	DialogConfiguration dialogConfig = new DialogConfigurationBuilder(app)
		// ...
		.build();
	MailSenderConfiguration mailConfig = new MailSenderConfigurationBuilder(app)
		// ...
		.build();
		
		
And then I use the config:

	 ACRA.init(app, coreConfig);
	 
	 
How do I add the `dialogConfig` and `mailConfig` to `ACRA` now? I looked at `ACRA` and `CoreConfig` but can't find something...

**basic setup issue**

The urls here do not work: https://github.com/ACRA/acra/wiki/BasicSetup

Looks like v5 release version is added like `implementation "ch.acra:acra-core:$rootProject.versions.acra"` instead of what the link looks like in the BasicSetup?

**Comment by F43nd1r** [comment]
Instead of `new DialogConfigurationBuilder()` call `coreConfigBuilder.getPluginConfigurationBuilder(DialogConfigurationBuilder.class)`

Also note that you have to call `<pluginBuilder>.setEnabled(true)` for each plugin (or add the respective annotation).

I've updated the urls in the setup guide (those were still values used for the prereleases), however there seems to be an issue with the javadoc, I'll investigate further.

**Comment by MFlisar** [comment]
Thanks, that makes it clear now. And I've enabled all plugins anyways. I came up with following now:

	CoreConfigurationBuilder configBuilder = new CoreConfigurationBuilder(app)
			.setEnabled(true)
			.setReportFormat(StringFormat.KEY_VALUE_LIST)
			.setReportContent(
					//ReportField.USER_COMMENT,
					ReportField.REPORT_ID,
					ReportField.APP_VERSION_NAME,
					ReportField.APP_VERSION_CODE,
					ReportField.ANDROID_VERSION,
					ReportField.PHONE_MODEL,
					ReportField.PACKAGE_NAME,
					ReportField.CRASH_CONFIGURATION,
					ReportField.CUSTOM_DATA,
					ReportField.STACK_TRACE,
					ReportField.APPLICATION_LOG,
					ReportField.BUILD)
			.setAttachmentUris(Uri.parse("content://" + app.getPackageName() + ".acra/root" + FileLoggingUtil.getDefaultLogFile(fileLoggingSetup)).toString())
//                    .setBuildConfigClass(BuildConfig.class)
			;
	configBuilder.getPluginConfigurationBuilder(DialogConfigurationBuilder.class)
			.setEnabled(true)
			.setResIcon(appIcon)
			.setResText(R.string.crash_dialog_text)
			.setResTitle(R.string.crash_dialog_title);
	configBuilder.getPluginConfigurationBuilder(MailSenderConfigurationBuilder.class)
			.setEnabled(true)
			.setMailTo(app.getString(R.string.email))
			.setReportAsFile(true);
	CoreConfiguration config = configBuilder.build();

	ACRA.init(app, config);

Should this work? Should a dialog be shown like this? I get the `DialogConfigurationBuilder` from the `CoreConfigurationBuilder`, enable it and set it up and then init ACRA. Correct?

Because the example above does not show a dialog. Can you tell my what I'm missing?

**Comment by MFlisar** [comment]
Thanks, this helped.

I try following:

    ACRA.init(app, config);
    ACRA.getErrorReporter().putCustomData("AppName", app.getString(R.string.app_name));
    ACRA.getErrorReporter().putCustomData("Developer", String.valueOf(Tools.isDeveloper(app)));

But this throws an exception that I can't call `getErrorReporter` before calling `ACRA.init` which apparently do. How should I adjust this piece of code?

**Comment by F43nd1r** [comment]
Check your log - there is probably an exception before the ErrorReporter is initialized.

**Comment by MFlisar** [comment]
I debugged the app and see, that above does work. My app starts normally without exceptions or logged errors (`errorReporterSingleton` gets created in `ACRA`) . But as soon as I throw an exception in code I get following (as if the app process is recreated instantly and the singleton is gone):

	E/Zygote: v2
	I/libpersona: KNOX_SDCARD checking this for 10315
	I/libpersona: KNOX_SDCARD not a persona
	E/Zygote: accessInfo : 0
	W/SELinux: SELinux selinux_android_compute_policy_index : Policy Index[2],  Con:u:r:zygote:s0 RAM:SEPF_SECMOBILE_7.0_0005, [-1 -1 -1 -1 0 1]
	I/SELinux: SELinux: seapp_context_lookup: seinfo=untrusted, level=s0:c512,c768, pkgname=com.my.app.debug:acra 
	I/art: Late-enabling -Xcheck:jni
	D/TimaKeyStoreProvider: TimaKeyStore is not enabled: cannot add TimaSignature Service and generateKeyPair Service
	/com.my.app.debug:acra W/System: ClassLoader referenced unknown path: /data/app/com.my.app.debug-1/lib/arm64
	/com.my.app.debug:acra D/AndroidRuntime: Shutting down VM
	/com.my.app.debug:acra E/AndroidRuntime: FATAL EXCEPTION: main
	   Process: com.my.app.debug:acra, PID: 31715
	   java.lang.RuntimeException: Unable to instantiate application com.my.app.app.MainApp: java.lang.IllegalStateException: Cannot access ErrorReporter before ACRA#init
		   at android.app.LoadedApk.makeApplication(LoadedApk.java:846)
		   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5850)
		   at android.app.ActivityThread.-wrap3(ActivityThread.java)
		   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1699)
		   at android.os.Handler.dispatchMessage(Handler.java:102)
		   at android.os.Looper.loop(Looper.java:154)
		   at android.app.ActivityThread.main(ActivityThread.java:6682)
		   at java.lang.reflect.Method.invoke(Native Method)
		   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
		   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
		Caused by: java.lang.IllegalStateException: Cannot access ErrorReporter before ACRA#init
		   at org.acra.ACRA.getErrorReporter(ACRA.java:280)
		   at com.my.app.acra.AcraUtil.init(AcraUtil.java:92)
		   at com.my.app.application.BaseApp.initAcra(BaseApp.java:123)
		   at com.my.app.application.BaseApp.attachBaseContext(BaseApp.java:92)
		   at android.app.Application.attach(Application.java:213)
		   at android.app.Instrumentation.newApplication(Instrumentation.java:1016)
		   at android.app.Instrumentation.newApplication(Instrumentation.java:1000)
		   at android.app.LoadedApk.makeApplication(LoadedApk.java:835)
		   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5850) 
		   at android.app.ActivityThread.-wrap3(ActivityThread.java) 
		   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1699) 
		   at android.os.Handler.dispatchMessage(Handler.java:102) 
		   at android.os.Looper.loop(Looper.java:154) 
		   at android.app.ActivityThread.main(ActivityThread.java:6682) 
		   at java.lang.reflect.Method.invoke(Native Method) 
		   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520) 
		   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410) 

Any other ideas or hints where I could look at?

**Comment by F43nd1r** [comment]
ah - yes `ErrorReporter` is not initialized in our `SenderService` process (mainly to prevent infinite crash loops).

Wrap your `getErrorReporter` calls with `if(!ACRA.isACRASenderServiceProcess())`.

**Comment by MFlisar** [comment]
Perfect, everything is working as before now for me. Thanks for the help
