### ISSUE TITLE
Could not instantiate any classes loaded by ServiceLoader on HTC Desire

### ISSUE THREAD

**Issue by koral--** [ACRA/acra#619]
ACRA version: 5.0.0.
Device: HTC Desire 820G Plus with Android 4.4.2

One of the stacktraces:
```
Unable to load ConfigurationBuilderFactory
                                         java.util.ServiceConfigurationError: Couldn't instantiate class org.acra.config.HttpSenderConfigurationBuilderFactory
                                             at java.util.ServiceLoader$ServiceIterator.next(ServiceLoader.java:216)
                                             at org.acra.config.BaseCoreConfigurationBuilder.<init>(BaseCoreConfigurationBuilder.java:58)
                                             at org.acra.config.CoreConfigurationBuilder.<init>(CoreConfigurationBuilder.java:132)
                                             at org.acra.config.CoreConfigurationBuilder.<init>(CoreConfigurationBuilder.java:94)
                                             at <stripped>
                                             at <stripped>
                                             at android.app.Application.attach(Application.java:181)
                                             at android.app.Instrumentation.newApplication(Instrumentation.java:991)
                                             at android.app.Instrumentation.newApplication(Instrumentation.java:975)
                                             at android.app.LoadedApk.makeApplication(LoadedApk.java:511)
                                             at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4555)
                                             at android.app.ActivityThread.access$1500(ActivityThread.java:151)
                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1402)
                                             at android.os.Handler.dispatchMessage(Handler.java:110)
                                             at android.os.Looper.loop(Looper.java:193)
                                             at android.app.ActivityThread.main(ActivityThread.java:5333)
                                             at java.lang.reflect.Method.invokeNative(Native Method)
                                             at java.lang.reflect.Method.invoke(Method.java:515)
                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
                                             at dalvik.system.NativeStart.main(Native Method)
                                          Caused by: java.lang.ClassNotFoundException: Didn't find class "org.acra.config.HttpSenderConfigurationBuilderFactory" on path: DexPathList[[zip file "/data/app<stripped>.apk"],nativeLibraryDirectories=[/data/app-lib/<stripped>, /vendor/lib, /system/lib]]
                                             at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                             at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
                                             at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
                                             at java.util.ServiceLoader$ServiceIterator.next(ServiceLoader.java:214)
                                             at org.acra.config.BaseCoreConfigurationBuilder.<init>(BaseCoreConfigurationBuilder.java:58) 
                                             at org.acra.config.CoreConfigurationBuilder.<init>(CoreConfigurationBuilder.java:132) 
                                             at org.acra.config.CoreConfigurationBuilder.<init>(CoreConfigurationBuilder.java:94) 
                                             at <stripped>
                                             at <stripped>
                                             at android.app.Application.attach(Application.java:181) 
                                             at android.app.Instrumentation.newApplication(Instrumentation.java:991) 
                                             at android.app.Instrumentation.newApplication(Instrumentation.java:975) 
                                             at android.app.LoadedApk.makeApplication(LoadedApk.java:511) 
                                             at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4555) 
                                             at android.app.ActivityThread.access$1500(ActivityThread.java:151) 
                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1402) 
                                             at android.os.Handler.dispatchMessage(Handler.java:110) 
                                             at android.os.Looper.loop(Looper.java:193) 
                                             at android.app.ActivityThread.main(ActivityThread.java:5333) 
                                             at java.lang.reflect.Method.invokeNative(Native Method) 
                                             at java.lang.reflect.Method.invoke(Method.java:515) 
                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829) 
                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645) 
                                             at dalvik.system.NativeStart.main(Native Method) 
```
Output of `adb logcat |grep instantiate`:
```
E/ACRA    (20200): java.util.ServiceConfigurationError: Couldn't instantiate class org.acra.config.HttpSenderConfigurationBuilderFactory
E/ACRA    (20200): java.util.ServiceConfigurationError: Couldn't instantiate class org.acra.collector.ConfigurationCollector
E/ACRA    (20200): java.util.ServiceConfigurationError: Couldn't instantiate class org.acra.collector.CustomDataCollector
E/ACRA    (20200): java.util.ServiceConfigurationError: Couldn't instantiate class org.acra.collector.DeviceFeaturesCollector
E/ACRA    (20200): java.util.ServiceConfigurationError: Couldn't instantiate class org.acra.collector.DeviceIdCollector
E/ACRA    (20200): java.util.ServiceConfigurationError: Couldn't instantiate class org.acra.collector.DisplayManagerCollector
E/ACRA    (20200): java.util.ServiceConfigurationError: Couldn't instantiate class org.acra.collector.DropBoxCollector
E/ACRA    (20200): java.util.ServiceConfigurationError: Couldn't instantiate class org.acra.collector.LogCatCollector
E/ACRA    (20200): java.util.ServiceConfigurationError: Couldn't instantiate class org.acra.collector.LogFileCollector
E/ACRA    (20200): java.util.ServiceConfigurationError: Couldn't instantiate class org.acra.collector.MediaCodecListCollector
E/ACRA    (20200): java.util.ServiceConfigurationError: Couldn't instantiate class org.acra.collector.MemoryInfoCollector
E/ACRA    (20200): java.util.ServiceConfigurationError: Couldn't instantiate class org.acra.collector.PackageManagerCollector
E/ACRA    (20200): java.util.ServiceConfigurationError: Couldn't instantiate class org.acra.collector.ReflectionCollector
E/ACRA    (20200): java.util.ServiceConfigurationError: Couldn't instantiate class org.acra.collector.SettingsCollector
E/ACRA    (20200): java.util.ServiceConfigurationError: Couldn't instantiate class org.acra.collector.SharedPreferencesCollector
E/ACRA    (20200): java.util.ServiceConfigurationError: Couldn't instantiate class org.acra.collector.SimpleValuesCollector
E/ACRA    (20200): java.util.ServiceConfigurationError: Couldn't instantiate class org.acra.collector.StacktraceCollector
E/ACRA    (20200): java.util.ServiceConfigurationError: Couldn't instantiate class org.acra.collector.ThreadCollector
E/ACRA    (20200): java.util.ServiceConfigurationError: Couldn't instantiate class org.acra.collector.TimeCollector
```

**Comment by F43nd1r** [comment]
Which android version?
Could you check if there are any files in META_INF/services in the apk?
Are you using proguard?

**Comment by koral--** [comment]
It's development build, there is no proguard, dexguard nor shrinker etc. enabled. However, instant run might be used. I'll check that and the APK ASAP.

**Comment by koral--** [comment]
There are 3 property files from ACRA. Issue is always reproducible on that device. Tried without instant run.

**Comment by F43nd1r** [comment]
I just confirmed I no problems using acra on an API 19 emulator. I do not have a physical device with pre-lollipop android.

**Comment by koral--** [comment]
I've found a reason. Issue occurs if those classes loaded by `ServiceLoader` are located outside primary dex file.
So to reproduce you have to use project with > 64K methods and enable multidex.

Fix is to add either `multiDexKeepFile` or `multiDexKeepProguard` properties inside build type block. More info: https://developer.android.com/studio/build/multidex.html#keep

I think that this information should be included in readme. It seems that there is no property like `consumerMultiDexKeepProguard` so each ACRA user which uses multidex with minSdkVersion <= 19 has to add `multiDexKeepFile` or `multiDexKeepProguard` manually.

**Comment by F43nd1r** [comment]
My tests with multidex work, if Multidex.install is called before ACRA.init. Please confirm you are calling ACRA after multidex.

**Comment by koral--** [comment]
🤦‍♂️ my fault, ACRA was initialized before multidex. After switching initialization order everything works properly. Thanks.
