### ISSUE TITLE
NullPointerException in resTitle method when using notification version 5.0.0

### ISSUE THREAD

**Issue by DanteNguyen1008** [ACRA/acra#635]
If I remove dependency of notification 5.0.0. it started working again. 

`@AcraToast(resText = R.string.toast_acra)
public class MyApplication extends Application{

    @Override
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(base);

        CoreConfigurationBuilder builder = new CoreConfigurationBuilder(this);
        builder.setBuildConfigClass(BuildConfig.class).setReportFormat(StringFormat.JSON);
        builder.getPluginConfigurationBuilder(ToastConfigurationBuilder.class).setResText(R.string.toast_acra);
        builder.getPluginConfigurationBuilder(ToastConfigurationBuilder.class).setEnabled(true);

        try {
            ACRA.init(this, builder.build());
        } catch (ACRAConfigurationException e) {
            e.printStackTrace();
        }
    }
}
`

Error from notification 5.0.0 (notification does not have 5.0.2)

`Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
                                                       at org.acra.config.NotificationConfigurationBuilder.resTitle(NotificationConfigurationBuilder.java:132)
                                                       at org.acra.config.NotificationConfiguration.<init>(NotificationConfiguration.java:72)
                                                       at org.acra.config.NotificationConfigurationBuilder.build(NotificationConfigurationBuilder.java:418)
                                                       at org.acra.config.NotificationConfigurationBuilder.build(NotificationConfigurationBuilder.java:23)
                                                       at org.acra.config.BaseCoreConfigurationBuilder.preBuild(BaseCoreConfigurationBuilder.java:71)
                                                       at org.acra.config.CoreConfigurationBuilder.build(CoreConfigurationBuilder.java:689)
                                                       at com.example.anguyen.acrademo.MyApplication.attachBaseContext(MyApplication.java:32)`

**Comment by F43nd1r** [comment]
Seems like 5.0.2 omitted the pom.xml from the upload. You can use 5.0.1 or 5.1.0
