### ISSUE TITLE
Error org.acra.config.MailSenderConfiguration is no registered configuration

### ISSUE THREAD

**Issue by pouriabagheri** [ACRA/acra#684]
I have been using  ch.acra:acra:4.9.2 and faced after tarking android 8.0 I faced  #630. so decided to upgrade to 5.1.3 following the guides

Gradle: 
```
def acraVersion = '5.1.3'
implementation "ch.acra:acra-core:$acraVersion"
implementation "ch.acra:acra-http:$acraVersion"
implementation "ch.acra:acra-dialog:$acraVersion"
implementation "ch.acra:acra-toast:$acraVersion"
implementation "ch.acra:acra-mail:$acraVersion"
```
AcraApplication Setup:
```
public class AcraApplication extends OtherApplication{
    @Override
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(base);
        CoreConfigurationBuilder builder = new CoreConfigurationBuilder(this)
                .setBuildConfigClass(BuildConfig.class)
                .setReportFormat(StringFormat.KEY_VALUE_LIST)
                .setReportContent(
                        //ReportField.USER_COMMENT,
                        ReportField.REPORT_ID,
                        ReportField.APP_VERSION_NAME,
                        ReportField.APP_VERSION_CODE,
                        ReportField.ANDROID_VERSION,
                        ReportField.PHONE_MODEL,
                        ReportField.PACKAGE_NAME,
                        ReportField.CRASH_CONFIGURATION,
                        ReportField.CUSTOM_DATA,
                        ReportField.STACK_TRACE,
                        ReportField.APPLICATION_LOG,
                        ReportField.BUILD);
        builder.getPluginConfigurationBuilder(ToastConfigurationBuilder.class)
                .setEnabled(true)
                .setResText(R.string.crash_dialog_text);

// email config
        builder.getPluginConfigurationBuilder(HttpSenderConfigurationBuilder.class)
                .setUri(getResources().getString(R.string.error_end_point))
                .setHttpMethod(HttpSender.Method.POST)
                .setEnabled(true);

// dialog config
        builder.getPluginConfigurationBuilder(DialogConfigurationBuilder.class)
                .setResText(R.string.crash_dialog_text)
                .setResIcon(android.R.drawable.ic_dialog_info)
                .setTitle(getResources().getString(R.string.crash_dialog_title))
                .setResCommentPrompt(R.string.crash_dialog_comment_prompt)
                .setResTheme(R.style.AppTheme_Dialog_ACRA)
                .setEnabled(true);

// Mail config
        builder.getPluginConfigurationBuilder(MailSenderConfigurationBuilder.class)
                .setEnabled(true)
                .setMailTo(getResources().getString(R.string.myemail))
                .setReportAsFile(true);

        ACRA.init(this, builder);
        ACRA.getErrorReporter().putCustomData("Build Type ", BuildConfig.BUILD_TYPE);
}
```
I've tried removing the mail config or http sender it always returns the same error and when i throws exception it does not show any toast or dialog but the still shows `org.acra.config.MailSenderConfiguration is no registered configuration`

Error statck :
```
E/ACRA: java.lang.IllegalArgumentException: org.acra.config.MailSenderConfiguration is no registered configuration
                                             at org.acra.config.ConfigUtils.getPluginConfiguration(SourceFile:37)
                                             at org.acra.sender.BaseReportSenderFactory.enabled(SourceFile:39)
                                             at org.acra.sender.DefaultReportSenderFactory.create(SourceFile:49)
                                             at org.acra.sender.SenderService.getSenderInstances(SourceFile:114)
                                             at org.acra.sender.SenderService.onHandleWork(SourceFile:67)
                                             at android.support.v4.app.w$a.a(SourceFile:391)
                                             at android.support.v4.app.w$a.doInBackground(SourceFile:382)
                                             at android.os.AsyncTask$2.call(AsyncTask.java:333)
                                             at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                             at java.lang.Thread.run(Thread.java:764)
```

**Comment by F43nd1r** [comment]
Could you try with acra 5.2.0-rc2?

**Comment by F43nd1r** [comment]
I was unable to reproduce the issue with either 5.1.3 or 5.2.0-rc2

**Comment by pouriabagheri** [comment]
My bad, It seems to be a compiler issue. after a clean build works on both  5.1.3 and 5.2.0-rc2
@F43nd1r  thanks
