### ISSUE TITLE
 ACRA failed to capture the error - handing off to native error reporter

### ISSUE THREAD

**Issue by izjumovfs** [ACRA/acra#692]
Hi
I have got this issue on my Android 4.2.2 tablet. On higher Android versions everything is working okay

 E/ACRA: ACRA failed to capture the error - handing off to native error reporter
    java.lang.IllegalArgumentException: org.acra.config.DialogConfiguration is no registered configuration
        at org.acra.config.ConfigUtils.getPluginConfiguration(ConfigUtils.java:37)
        at org.acra.interaction.BaseReportInteraction.enabled(BaseReportInteraction.java:39)
        at org.acra.interaction.ReportInteractionExecutor.<init>(ReportInteractionExecutor.java:53)
        at org.acra.builder.ReportExecutor.execute(ReportExecutor.java:171)
        at org.acra.builder.ReportBuilder.build(ReportBuilder.java:183)
        at org.acra.reporter.ErrorReporterImpl.uncaughtException(ErrorReporterImpl.java:148)
        at android.support.v7.app.AppCompatDelegateImpl$1.uncaughtException(AppCompatDelegateImpl.java:143)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
        at dalvik.system.NativeStart.main(Native Method)

 I/ACRA: ACRA is disabled for ............. - forwarding uncaught Exception on to default ExceptionHandler

**This is my config**

@AcraCore(
        reportContent = {
            APP_VERSION_NAME,
            ANDROID_VERSION,
            PHONE_MODEL,
            BRAND,
            STACK_TRACE,
            USER_COMMENT,
            USER_EMAIL
        },
        buildConfigClass = BuildConfig.class,
        reportFormat = StringFormat.KEY_VALUE_LIST
)
@AcraHttpSender(uri = "someurl",
        httpMethod = HttpSender.Method.POST
)
@AcraDialog(resText = R.string.crash_dialog_text,
        resCommentPrompt = R.string.crash_dialog_comment_prompt,
        resEmailPrompt = R.string.crash_user_email_label,
        resIcon = android.R.drawable.ic_dialog_info,
        resTitle = R.string.crash_dialog_title,
        reportDialogClass = ErrorReportDialog.class
)

**Comment by F43nd1r** [comment]
Possible duplicate #684

**Comment by izjumovfs** [comment]
Changed to ACRA 5.2.0-rc2 - now got this issue 
Caused by: java.lang.ClassNotFoundException: Didn't find class "org.acra.collector.SimpleValuesCollector"

**Comment by F43nd1r** [comment]
Another possible duplicate #619

**Comment by izjumovfs** [comment]
Thanks #619 helped to solve my issue
