### ISSUE TITLE
Exception causes appear multiple times in stack trace

### ISSUE THREAD

**Issue by mhsmith** [ACRA/acra#695]
The following code prints each cause in the exception chain:

https://github.com/ACRA/acra/blob/9d35cf00d8e3a28f8bacb48a9a16aeceb974325d/acra-core/src/main/java/org/acra/collector/StacktraceCollector.java#L81-L87

But this is completely unnecessary, because the top-level stack trace already included a complete chain of causes. The result will look something like this:

```
A
caused by B
caused by C
caused by D
B
caused by C
caused by D
C
caused by D
D
```
... except that A, B, C and D may each be many lines long.

**Comment by F43nd1r** [comment]
That code is ancient. It is at least 7 years old: https://github.com/ACRA/acra/blob/fcb2b316e4502a35076aa5aa4126b2bda31a8f76/acra/src/main/java/org/acra/CrashReportDataFactory.java#L302-L308

As it is practically impossible to prove that there is no case where this is needed, I'd rather not remove it.

**Comment by mhsmith** [comment]
The only explanation I can think of is that there was some ancient version of Android which didn't print causes in stack traces. But ACRA now requires a minimum API level of 14, so I doubt this is still an issue.

**Comment by F43nd1r** [comment]
```
java.lang.RuntimeException: An error occured while executing doInBackground()
    at android.os.AsyncTask$3.done(AsyncTask.java:300)
    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
    at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
    at java.util.concurrent.FutureTask.run(FutureTask.java:242)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:841)
Caused by: java.lang.RuntimeException
    at com.faendir.acratest.context.MainActivity$1.doInBackground(MainActivity.java:39)
    at com.faendir.acratest.context.MainActivity$1.doInBackground(MainActivity.java:35)
    at android.os.AsyncTask$2.call(AsyncTask.java:288)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    ... 4 more
java.lang.RuntimeException
    at com.faendir.acratest.context.MainActivity$1.doInBackground(MainActivity.java:39)
    at com.faendir.acratest.context.MainActivity$1.doInBackground(MainActivity.java:35)
    at android.os.AsyncTask$2.call(AsyncTask.java:288)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)at java.lang.Thread.run(Thread.java:841)
```
As you can see, stacktraces are often printed with `x more` at the end, so I think this was implemented to circumvent that.

**Comment by mhsmith** [comment]
The `x more` doesn't mean any information is missing As explained [here](https://docs.oracle.com/javase/7/docs/api/java/lang/Throwable.html#printStackTrace()), the lines it represents are already visible in the higher-level stack trace. You can see that in your example.
