### ISSUE TITLE
ReportSender not working on MIUI 8.1.0

### ISSUE THREAD

**Issue by may17s** [ACRA/acra#707]
It's work on 4.4, 6.0.1, 8.0 (android emulator) android device, but not work on android 8.1.0. I try it on acra 5.2.0 and 5.1.3.
Help me please..

@AcraCore(buildConfigClass = BuildConfig.class,
        reportFormat = StringFormat.JSON,
        reportSenderFactoryClasses = ACRAMsSqlSenderFactory.class
    )
@AcraToast(resText=R.string.acraMessage)
public class QRApplication extends Application {

@Override
protected void attachBaseContext(Context base) {
    super.attachBaseContext(base);

    if (BuildConfig.DEBUG)
    {
        ACRA.DEV_LOGGING = true;
    }
    ACRA.init(this);
}
}

public class ACRAMsSqlSenderFactory implements ReportSenderFactory {
    final String TAG = "mytag";
    @Override
    public ReportSender create(Context context, CoreConfiguration config) {
        Log.e(TAG, "create ACRAMsSqlSenderFactory");
        return new ACRAMsSqlSender(config);
    }
    @Override
    public boolean enabled(@NonNull CoreConfiguration coreConfig) {
        return true;
    }
}

public class ACRAMsSqlSender implements ReportSender {
    final String TAG = "mytag";
    private final CoreConfiguration config;
    public ACRAMsSqlSender(@NonNull CoreConfiguration config) {
        Log.e(TAG, "create ACRAMsSqlSender");
        this.config = config;
    }
    @Override
    public void send(Context context, CrashReportData errorContent) throws ReportSenderException {
        Log.e(TAG, "send ACRAMsSqlSender");
	  // here my code which send data to my mssql server
          // but in android 8.1 I'm not come in here
    }
}

build.gradle:
android {
compileSdkVersion 27
compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
}

defaultConfig {
    applicationId "ru.atomexp.qr"
    minSdkVersion 19
    targetSdkVersion 24
    versionName "${getVersionNameTimestamp()}"
    versionCode getVersionCodeTimestamp()
    testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    vectorDrawables.useSupportLibrary = true
}
buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    ...
    // acra
    //def acraVersion = '5.1.3'
    def acraVersion = '5.2.0'
    implementation "ch.acra:acra-toast:$acraVersion"
}

2018-10-04 14:27:21.670 8089-8089/ru.atomexp.qr D/ACRA: Finished class ru.atomexp.qr.MainActivity
2018-10-04 14:27:21.671 8089-8089/ru.atomexp.qr D/ACRA: Writing crash report file /data/user/0/ru.atomexp.qr/app_ACRA-unapproved/2018-10-04T14:27:21.604+03:00-IS_SILENT.stacktrace
2018-10-04 14:27:21.717 8089-8181/ru.atomexp.qr D/ACRA: Calling ReportInteraction of class org.acra.interaction.ToastInteraction
2018-10-04 14:27:23.746 8089-8089/ru.atomexp.qr D/ACRA: About to start SenderService
2018-10-04 14:27:23.921 8089-8089/ru.atomexp.qr D/ACRA: Wait for Interactions + worker ended. Kill Application ? true
2018-10-04 14:27:23.923 8089-8089/ru.atomexp.qr W/ACRA: Warning: Acra may behave differently with a debugger attached

**Comment by F43nd1r** [comment]
> Warning: Acra may behave differently with a debugger attached

Please run your app without a debugger

**Comment by may17s** [comment]
I turned off the debugger, and restarted the device, but still the report is not sent

**Comment by F43nd1r** [comment]
Could not reproduce. Log from a 8.1 emulator with the code you provided:
```java
10-08 01:02:30.135 5910-5927/com.faendir.acratest:acra D/ACRA: About to start sending reports from SenderService
10-08 01:02:30.136 5910-5927/com.faendir.acratest:acra E/mytag: create ACRAMsSqlSenderFactory
    create ACRAMsSqlSender
10-08 01:02:30.136 5910-5927/com.faendir.acratest:acra I/ACRA: Sending report /data/user/0/com.faendir.acratest/app_ACRA-approved/2018-10-08T01:02:27.418+02:00-IS_SILENT.stacktrace
10-08 01:02:30.155 5910-5927/com.faendir.acratest:acra D/ACRA: Sending report using com.faendir.acratest.context.App$ACRAMsSqlSender
10-08 01:02:30.155 5910-5927/com.faendir.acratest:acra E/mytag: send ACRAMsSqlSender
10-08 01:02:30.156 5910-5927/com.faendir.acratest:acra D/ACRA: Sent report using com.faendir.acratest.context.App$ACRAMsSqlSender
    Report was sent by all senders
    Finished sending reports from SenderService
```

**Comment by may17s** [comment]
I tested it on several devices, and found this: it works on pure android 8.1.0 (Xiaomi Mi A1)! And on android 8.1.0 with MIUI (Xiaomi Redmi 6A) does not work.

Here is the Xiaomi Redmi 6A error report:

[2018-10-16T13_06_48.795+03_00-IS_SILENT.stacktrace.txt](https://github.com/ACRA/acra/files/2482579/2018-10-16T13_06_48.795%2B03_00-IS_SILENT.stacktrace.txt)

It may not work due to the following problem:

2018-10-16 13:06:48.793 338-338/? E/SELinux: avc:  denied  { find } for service=meminfo pid=12661 uid=10145 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:meminfo_service:s0 

Here is a more detailed log:

2018-10-16 13:06:48.738 12601-12601/ru.atomexp.qr E/ACRA: ACRA caught a NullPointerException for ru.atomexp.qr
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getAction()' on a null object reference
        at ru.atomexp.qr.fragments.ActionFragment$2.onClick(ActionFragment.java:83)
        at android.view.View.performClick(View.java:6310)
        at android.view.View$PerformClick.run(View.java:24970)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:171)
        at android.app.ActivityThread.main(ActivityThread.java:6627)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:518)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
2018-10-16 13:06:48.738 12601-12601/ru.atomexp.qr D/ACRA: Building report
2018-10-16 13:06:48.741 12601-12650/ru.atomexp.qr D/ACRA: Calling collector org.acra.collector.DropBoxCollector
2018-10-16 13:06:48.741 12601-12650/ru.atomexp.qr D/ACRA: Collector org.acra.collector.DropBoxCollector completed
2018-10-16 13:06:48.742 12601-12651/ru.atomexp.qr D/ACRA: Calling collector org.acra.collector.LogCatCollector
2018-10-16 13:06:48.743 12601-12652/ru.atomexp.qr D/ACRA: Calling collector org.acra.collector.StacktraceCollector
2018-10-16 13:06:48.743 12601-12650/ru.atomexp.qr D/ACRA: Calling collector org.acra.collector.ConfigurationCollector
2018-10-16 13:06:48.745 12601-12652/ru.atomexp.qr D/ACRA: Collector org.acra.collector.StacktraceCollector completed
2018-10-16 13:06:48.746 12601-12652/ru.atomexp.qr D/ACRA: Calling collector org.acra.collector.DisplayManagerCollector
2018-10-16 13:06:48.747 12601-12656/ru.atomexp.qr D/ACRA: Calling collector org.acra.collector.DeviceIdCollector
2018-10-16 13:06:48.749 12601-12656/ru.atomexp.qr D/ACRA: Collector org.acra.collector.DeviceIdCollector completed
2018-10-16 13:06:48.749 12601-12651/ru.atomexp.qr D/ACRA: Retrieving logcat output (buffer:default)...
2018-10-16 13:06:48.752 12601-12650/ru.atomexp.qr D/ACRA: Collector org.acra.collector.ConfigurationCollector completed
2018-10-16 13:06:48.754 12601-12657/ru.atomexp.qr D/ACRA: Calling collector org.acra.collector.MemoryInfoCollector
2018-10-16 13:06:48.754 12601-12656/ru.atomexp.qr D/ACRA: Calling collector org.acra.collector.SettingsCollector
2018-10-16 13:06:48.754 12601-12650/ru.atomexp.qr D/ACRA: Calling collector org.acra.collector.ReflectionCollector
2018-10-16 13:06:48.754 12601-12656/ru.atomexp.qr D/ACRA: Collector org.acra.collector.SettingsCollector completed
2018-10-16 13:06:48.754 12601-12653/ru.atomexp.qr D/ACRA: Calling collector org.acra.collector.CustomDataCollector
2018-10-16 13:06:48.757 12601-12653/ru.atomexp.qr D/ACRA: Collector org.acra.collector.CustomDataCollector completed
2018-10-16 13:06:48.758 12601-12655/ru.atomexp.qr D/ACRA: Calling collector org.acra.collector.DeviceFeaturesCollector
2018-10-16 13:06:48.758 12601-12656/ru.atomexp.qr D/ACRA: Calling collector org.acra.collector.SimpleValuesCollector
2018-10-16 13:06:48.760 12601-12659/ru.atomexp.qr D/ACRA: Calling collector org.acra.collector.PackageManagerCollector
2018-10-16 13:06:48.762 12601-12653/ru.atomexp.qr D/ACRA: Calling collector org.acra.collector.LogFileCollector
2018-10-16 13:06:48.763 12601-12653/ru.atomexp.qr D/ACRA: Collector org.acra.collector.LogFileCollector completed
2018-10-16 13:06:48.774 12601-12655/ru.atomexp.qr D/ACRA: Collector org.acra.collector.DeviceFeaturesCollector completed
2018-10-16 13:06:48.775 12601-12659/ru.atomexp.qr D/ACRA: Collector org.acra.collector.PackageManagerCollector completed
2018-10-16 13:06:48.776 12601-12660/ru.atomexp.qr D/ACRA: Calling collector org.acra.collector.SharedPreferencesCollector
2018-10-16 13:06:48.780 12601-12656/ru.atomexp.qr D/ACRA: Collector org.acra.collector.SimpleValuesCollector completed
2018-10-16 13:06:48.786 12601-12662/ru.atomexp.qr D/ACRA: Calling collector org.acra.collector.TimeCollector
2018-10-16 13:06:48.788 12601-12660/ru.atomexp.qr D/ACRA: Collector org.acra.collector.SharedPreferencesCollector completed
2018-10-16 13:06:48.790 12601-12663/ru.atomexp.qr D/ACRA: Calling collector org.acra.collector.MediaCodecListCollector
2018-10-16 13:06:48.790 12601-12663/ru.atomexp.qr D/ACRA: Collector org.acra.collector.MediaCodecListCollector completed
2018-10-16 13:06:48.793 338-338/? E/SELinux: avc:  denied  { find } for service=meminfo pid=12661 uid=10145 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:meminfo_service:s0 tclass=service_manager permissive=0
2018-10-16 13:06:48.796 12601-12657/ru.atomexp.qr D/ACRA: Collector org.acra.collector.MemoryInfoCollector completed
2018-10-16 13:06:48.798 12601-12662/ru.atomexp.qr D/ACRA: Collector org.acra.collector.TimeCollector completed
2018-10-16 13:06:48.799 12601-12652/ru.atomexp.qr D/ACRA: Collector org.acra.collector.DisplayManagerCollector completed
2018-10-16 13:06:48.801 12601-12665/ru.atomexp.qr D/ACRA: Calling collector org.acra.collector.ThreadCollector
2018-10-16 13:06:48.801 12601-12665/ru.atomexp.qr D/ACRA: Collector org.acra.collector.ThreadCollector completed
2018-10-16 13:06:48.812 12601-12651/ru.atomexp.qr D/ACRA: Collector org.acra.collector.LogCatCollector completed
2018-10-16 13:06:48.817 12601-12650/ru.atomexp.qr D/ACRA: Collector org.acra.collector.ReflectionCollector completed
2018-10-16 13:06:48.818 12601-12601/ru.atomexp.qr D/ACRA: Finishing the last Activity prior to killing the Process
2018-10-16 13:06:48.828 12601-12601/ru.atomexp.qr D/ACRA: Finished class ru.atomexp.qr.MainActivity
2018-10-16 13:06:48.829 12601-12601/ru.atomexp.qr D/ACRA: Writing crash report file /data/user/0/ru.atomexp.qr/app_ACRA-unapproved/2018-10-16T13:06:48.795+03:00-IS_SILENT.stacktrace

**Comment by F43nd1r** [comment]
The SELinux line is likely related to a system service used in a collector. It is very unlikely that the launch of a service in the same app would even touch SELinux at all. 
As I do not have a MIUI device, I cannot test this any further.
The log looks normal, apart from the line you identified. However, I'd expect some more messages at the end. Did you truncate it?

**Comment by khejing** [comment]
是不是自启动权限没开？

**Comment by F43nd1r** [comment]
Please test if the issue persists with 5.3.0-b01

**Comment by F43nd1r** [comment]
Yeah, b01 is broken, see #720

**Comment by DanielWu-China** [comment]
> 是不是自启动权限没开？

开了自启动就好，但是用户不会去开啊

**Comment by F43nd1r** [comment]
Clsoing as this is MIUIs fault. See #732 and https://stackoverflow.com/questions/52927465/jobscheduler-is-not-working-in-xiaomi-when-app-is-not-in-background-and-auto-sta for more info
