### ISSUE TITLE
httpsender and limit data

### ISSUE THREAD

**Issue by mariuspena** [ACRA/acra#712]
Hi

My scenario is to use ACRA for a wear os stand alone app in a location without internet access, but with a server on premise that is accepting http calls.

I configured it like this:
`
CoreConfigurationBuilder builder = new CoreConfigurationBuilder(this)
                .setBuildConfigClass(BuildConfig.class)
                .setReportFormat(StringFormat.JSON);

        Map<String, String> authHeaderMap = new HashMap<>();
        authHeaderMap.put("Authorization", "Bearer " + sharedPreferencesManager.getAccessToken());

        builder.getPluginConfigurationBuilder(HttpSenderConfigurationBuilder.class)
                .setUri("http://192.168.0.102/api/v1/events/track/acra")
                .setHttpMethod(HttpSender.Method.POST)
                .setHttpHeaders(authHeaderMap)
                .setEnabled(true);

        ACRA.init(this, builder);`

I made the app crash with intention, but I do not see any http calls.

1. when does acra decide to send the logs/crashes to the server ? I see nothing in the logcat related to acra, I also used stetho to check for network calls. 

2. does the http sender work by only configuring the auth headers ? (with existing access token)

3. The server/backend must accept a body formated as json right ? What else do I need to know here to implement it correctly ?

4. Can I trigger the http sender manually ?

5. I am worried about the space taken by the logs saved by acra on disk. What is the strategy for keeping them low ?

**Comment by mariuspena** [comment]
I updated to the latest version 5.2.0 and now I see a crash in logcat

W/ACRA: org.acra.collector.CollectorException: Error while retrieving APPLICATION_LOG data:/data/user/0/ro.pena.test/files (Is a directory)
        at org.acra.collector.BaseReportFieldCollector.collect(BaseReportFieldCollector.java:77)
        at org.acra.data.CrashReportDataFactory.lambda$createCrashData$1$CrashReportDataFactory(CrashReportDataFactory.java:88)
        at org.acra.data.CrashReportDataFactory$$Lambda$1.run(Unknown Source:8)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.io.FileNotFoundException: /data/user/0/ro.pena.test/files (Is a directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:200)
        at java.io.FileInputStream.<init>(FileInputStream.java:150)
        at org.acra.util.StreamReader.<init>(StreamReader.java:56)
        at org.acra.collector.LogFileCollector.collect(LogFileCollector.java:52)
        at org.acra.collector.BaseReportFieldCollector.collect(BaseReportFieldCollector.java:73)
        at org.acra.data.CrashReportDataFactory.lambda$createCrashData$1$CrashReportDataFactory(CrashReportDataFactory.java:88) 
        at org.acra.data.CrashReportDataFactory$$Lambda$1.run(Unknown Source:8) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764)

**Comment by F43nd1r** [comment]
> when does acra decide to send the logs/crashes to the server ?

If you do not use the advanced scheduler, instantly after the crash.

> does the http sender work by only configuring the auth headers ?

ACRA supports basic http authentication, other headers have to be set manually. Note that in a closed ecosystem, you might not need to implement any authentication at all.

> The server/backend must accept a body formated as json right ? What else do I need to know here to implement it correctly ?

Yes. I can't think of anything else relevant here, except that ACRA expects a 2xx status code in the response, if the report was recevied successfully.

> I am worried about the space taken by the logs saved by acra on disk. What is the strategy for keeping them low ?

[`AcraLimiter#failedReportLimit()`](http://www.acra.ch/javadoc/latest/org/acra/annotation/AcraLimiter.html#failedReportLimit--)

> I updated to the latest version 5.2.0 and now I see a crash in logcat

This means the `ReportField.APPLICATION_LOG` is active, but not configured correctly. It should not stop ACRA from working.

If you call `ACRA.DEV_LOGGING = true` before `ACRA.init`, you should see exactly what ACRA is doing. However, there should be some messages at `Info` loglevel, even without debug logging turned on.

**Comment by mariuspena** [comment]
@F43nd1r thank you for the fast answer. It works beautifully!
