### ISSUE TITLE
Creating Error Reporter

### ISSUE THREAD

**Issue by ramirizk** [ACRA/acra#74]
I folowed the advanced Usage tutorial in creating my own error Reporter, but when I try and run it i recieve this error: java.lang.IllegalStateException: Cannot access ErrorReporter before ACRA#init.  My code is below for the application class:  
    @Override
    public void onCreate(){
        super.onCreate();
        SaveCrash crash = new SaveCrash(this);
        ACRA.init(this);
        ACRA.getErrorReporter().setReportSender(crash);
    }

I apologize if it is something easy i am missing, but i followed the instructions on Advanced Usage page to the tee.

**Comment by Djek-grif** [comment]
I had the same problem. But my problem was with ReportsCrashes. I don't use this annotation. Also I saw it case in sources. When I call init I receive
"ACRA#init called but no ReportsCrashes annotation on Application ", and ErrorReporter is not initialized. Then I receive - throw new IllegalStateException("Cannot access ErrorReporter before ACRA#init");

**Comment by william-ferguson-au** [comment]
@Djek-grif You cannot use `ACRA.init(Application)` if your Application class does not have annotations.

**Comment by Djek-grif** [comment]
Yes, now I see it. But I thought that I could do it when I use a custom sender :)

**Comment by blade3** [comment]
Hi,

I have this error too:

with dependency: `compile 'ch.acra:acra:4.9.0'`

`--------- beginning of crash
06-14 10:44:07.045 24277-24277/com.empire E/AndroidRuntime: FATAL EXCEPTION: main
                        Process: com.empire, PID: 24277
                        java.lang.RuntimeException: Unable to start activity ComponentInfo{com.empire/com.empire.HomeActivity}: java.lang.IllegalStateException: Cannot access ErrorReporter before ACRA#init
                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                        at android.app.ActivityThread.-wrap11(ActivityThread.java)
                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                        at android.os.Handler.dispatchMessage(Handler.java:102)
                        at android.os.Looper.loop(Looper.java:148)
                        at android.app.ActivityThread.main(ActivityThread.java:5417)
                        at java.lang.reflect.Method.invoke(Native Method)
                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
              Caused by: java.lang.IllegalStateException: Cannot access ErrorReporter before ACRA#init
                        at org.acra.ACRA.getErrorReporter(ACRA.java:331)
                        at com.empire.HomeActivity.setupOCR(HomeActivity.java:132)
                        at com.empire.HomeActivity.onCreate(HomeActivity.java:260)
                        at android.app.Activity.performCreate(Activity.java:6251)
                        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                        at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                        at android.os.Handler.dispatchMessage(Handler.java:102) 
                        at android.os.Looper.loop(Looper.java:148) 
                        at android.app.ActivityThread.main(ActivityThread.java:5417) 
                        at java.lang.reflect.Method.invoke(Native Method) 
                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) `

`import org.acra.ACRA;
import org.acra.ReportField;
import org.acra.ReportingInteractionMode;
import org.acra.annotation.ReportsCrashes;
import org.acra.sender.HttpSender;

@ReportsCrashes(
        formUri = "https://xxxxxx.cloudant.com/acra-xxxxx/_design/acra-storage/_update/report",
        reportType = HttpSender.Type.JSON,
        httpMethod = HttpSender.Method.POST,
        formUriBasicAuthLogin = "-------",
        formUriBasicAuthPassword = "------------------",
        //formKey = "", // This is required for backward compatibility but not used
        customReportContent = {
                ReportField.APP_VERSION_CODE,
                ReportField.APP_VERSION_NAME,
                ReportField.ANDROID_VERSION,
                ReportField.PACKAGE_NAME,
                ReportField.REPORT_ID,
                ReportField.BUILD,
                ReportField.STACK_TRACE
        },
        mode = ReportingInteractionMode.TOAST,
        resToastText = R.string.crash_toast_text
)`

The config : 


public class HomeActivity extends AppCompatActivity {
 @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
       ACRA.init(getApplication());
       try {
            throw new NumberFormatException();
        } catch (NumberFormatException e){
            ACRA.getErrorReporter().handleException(e);
        }   
}

thanks!
