### ISSUE TITLE
WorkManager error in applications that already utilize WorkManager

### ISSUE THREAD

**Issue by Adonai** [ACRA/acra#747]
OS: Android emulator 7.0, x86_64

I have an application that schedules jobs to WorkManager in its `Application.onCreate()`.
When it crashes, ACRA doesn't show any dialogs, instead crashes too, with following error:

```
2019-05-11 11:54:33.399 13071-13071/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.kanedias.dybr.fair.debug:acra, PID: 13071
    java.lang.RuntimeException: Unable to create application com.kanedias.dybr.fair.MainApplication: java.lang.IllegalStateException: WorkManager is not initialized properly.  The most likely cause is that you disabled WorkManagerInitializer in your manifest but forgot to call WorkManager#initialize in your Application#onCreate or a ContentProvider.
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5364)
        at android.app.ActivityThread.-wrap2(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1528)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
     Caused by: java.lang.IllegalStateException: WorkManager is not initialized properly.  The most likely cause is that you disabled WorkManagerInitializer in your manifest but forgot to call WorkManager#initialize in your Application#onCreate or a ContentProvider.
        at androidx.work.WorkManager.getInstance(WorkManager.java:141)
        at com.adonai.MainApplication.rescheduleJobs(MainApplication.kt:71)
        at com.adonai.MainApplication.onCreate(MainApplication.kt:56)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5361)
        at android.app.ActivityThread.-wrap2(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1528) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6077) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756) 
```

**Comment by Adonai** [comment]
Solved by follwing code:

```java
// don't schedule anything in crash reporter process
if (ACRA.isACRASenderServiceProcess())
    return
```

What does ACRA use WorkManager for internally?

**Comment by benibela** [comment]
> What does ACRA use WorkManager for internally?

It is not using workmanager for anything after 1767b85a23076ad8ff9008389809f8f31110a697 ?

**Comment by Adonai** [comment]
Understood

**Comment by mueller-ma** [comment]
I have the same crash with ACRA 5.7.0 mail and notification modules.

**Comment by F43nd1r** [comment]
@mueller-ma see fix above. ACRA is not using WorkManager.
