### ISSUE TITLE
android.os.TransactionTooLargeException on large report in MailSender even with reportAsFile=true

### ISSUE THREAD

**Issue by cy-ddg** [ACRA/acra#775]
While trying to generate a report containing a multi megabyte log file with version `5.5.0` I get the following exception:

```
2020-03-18 09:57:04.597 29849-29890/[...]:acra E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 12217760)
2020-03-18 09:57:04.608 29849-29890/[...]:acra E/ACRA: Failed to send crash reports for /data/user/0/[...]/app_ACRA-approved/2020-03-18T09:56:56.879+01:00.stacktrace
    java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 12217760 bytes
        at android.app.ApplicationPackageManager.resolveActivityAsUser(ApplicationPackageManager.java:1064)
        at android.app.ApplicationPackageManager.resolveActivity(ApplicationPackageManager.java:1052)
        at android.content.Intent.resolveActivity(Intent.java:8277)
        at org.acra.sender.EmailIntentSender.send(EmailIntentSender.java:82)
        at org.acra.sender.ReportSender.send(ReportSender.java:54)
        at org.acra.sender.ReportDistributor.sendCrashReport(ReportDistributor.java:115)
        at org.acra.sender.ReportDistributor.distribute(ReportDistributor.java:80)
        at org.acra.sender.SendingConductor.sendReports(SendingConductor.java:70)
        at org.acra.sender.JobSenderService.lambda$onStartJob$0$JobSenderService(JobSenderService.java:26)
        at org.acra.sender.-$$Lambda$JobSenderService$MqtyYgRmL36rkxc02MCfjNMMifI.run(Unknown Source:8)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: android.os.TransactionTooLargeException: data parcel size 12217760 bytes
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:784)
        at android.content.pm.IPackageManager$Stub$Proxy.resolveIntent(IPackageManager.java:4617)
        at android.app.ApplicationPackageManager.resolveActivityAsUser(ApplicationPackageManager.java:1058)
        at android.app.ApplicationPackageManager.resolveActivity(ApplicationPackageManager.java:1052) 
        at android.content.Intent.resolveActivity(Intent.java:8277) 
        at org.acra.sender.EmailIntentSender.send(EmailIntentSender.java:82) 
        at org.acra.sender.ReportSender.send(ReportSender.java:54) 
        at org.acra.sender.ReportDistributor.sendCrashReport(ReportDistributor.java:115) 
        at org.acra.sender.ReportDistributor.distribute(ReportDistributor.java:80) 
        at org.acra.sender.SendingConductor.sendReports(SendingConductor.java:70) 
        at org.acra.sender.JobSenderService.lambda$onStartJob$0$JobSenderService(JobSenderService.java:26) 
        at org.acra.sender.-$$Lambda$JobSenderService$MqtyYgRmL36rkxc02MCfjNMMifI.run(Unknown Source:8) 
        at java.lang.Thread.run(Thread.java:764) 
```

Device information:
```json
{
    "ANDROID_VERSION": "8.1.0",
    "AVAILABLE_MEM_SIZE": 22300217344,
    "BRAND": "samsung",
    "BUILD": {
        "BOARD": "universal7870",
        "BOOTLOADER": "T585XXU4CRJ8",
        "BRAND": "samsung",
        "CPU_ABI": "armeabi-v7a",
        "CPU_ABI2": "armeabi",
        "DEVICE": "gtaxllte",
        "DISPLAY": "M1AJQ.T585XXU4CRJ8",
        "HARDWARE": "samsungexynos7870",
        "HOST": "21HHAE13",
        "ID": "M1AJQ",
        "IS_CONTAINER": false,
        "IS_DEBUGGABLE": false,
        "IS_EMULATOR": false,
        "IS_ENG": false,
        "IS_TREBLE_ENABLED": false,
        "IS_USER": true,
        "IS_USERDEBUG": false,
        "MANUFACTURER": "samsung",
        "MODEL": "SM-T585",
        "PERMISSIONS_REVIEW_REQUIRED": false,
        "PRODUCT": "gtaxlltexx",
        "RADIO": "T585XXU4CRJA",
        "SUPPORTED_32_BIT_ABIS": [
            "armeabi-v7a",
            "armeabi"
        ],
        "SUPPORTED_64_BIT_ABIS": [],
        "SUPPORTED_ABIS": [
            "armeabi-v7a",
            "armeabi"
        ],
        "TAGS": "release-keys",
        "TIME": 1540215356000,
        "TYPE": "user",
        "UNKNOWN": "unknown",
        "USER": "dpi",
        "VERSION": {
            "ACTIVE_CODENAMES": [],
            "BASE_OS": "",
            "CODENAME": "REL",
            "INCREMENTAL": "T585XXU4CRJ8",
            "PREVIEW_SDK_INT": 0,
            "RELEASE": "8.1.0",
            "RESOURCES_SDK_INT": 27,
            "SDK": "27",
            "SDK_INT": 27,
            "SECURITY_INDEX": "1",
            "SECURITY_PATCH": "2018-11-01",
            "SEM_INT": 2701,
            "SEM_PLATFORM_INT": 90500
        }
    },
    "DEVICE_FEATURES": {
        "com.samsung.android.sdk.camera.processor": true,
        "com.sec.feature.motionrecognition_service": true,
        "android.hardware.sensor.accelerometer": true,
        "android.hardware.faketouch": true,
        "com.samsung.feature.virtualscreen": true,
        "android.hardware.usb.accessory": true,
        "android.software.backup": true,
        "android.hardware.touchscreen": true,
        "android.hardware.touchscreen.multitouch": true,
        "android.software.print": true,
        "android.software.activities_on_secondary_displays": true,
        "android.software.voice_recognizers": true,
        "android.software.picture_in_picture": true,
        "com.samsung.android.knox.knoxsdk": true,
        "com.sec.feature.slocation": true,
        "com.samsung.android.sdk.camera.processor.haze": true,
        "com.sec.feature.secretmode_service": true,
        "com.samsung.feature.device_category_tablet": true,
        "android.hardware.opengles.aep": true,
        "com.sec.feature.overlaymagnifier": true,
        "android.hardware.bluetooth": true,
        "android.hardware.camera.autofocus": true,
        "android.hardware.telephony.gsm": true,
        "android.software.sip.voip": true,
        "com.samsung.feature.samsung_experience_mobile": true,
        "android.hardware.usb.host": true,
        "android.hardware.audio.output": true,
        "android.hardware.camera.flash": true,
        "android.hardware.camera.front": true,
        "com.samsung.feature.clockpack_v05": true,
        "android.hardware.screen.portrait": true,
        "com.sec.android.mdm": true,
        "android.software.home_screen": true,
        "android.hardware.microphone": true,
        "android.software.autofill": true,
        "android.hardware.bluetooth_le": true,
        "android.hardware.touchscreen.multitouch.jazzhand": true,
        "android.software.app_widgets": true,
        "android.software.input_methods": true,
        "android.hardware.sensor.light": true,
        "android.hardware.vulkan.version": true,
        "android.software.companion_device_setup": true,
        "com.samsung.feature.galaxyfinder_v7": true,
        "android.software.device_admin": true,
        "android.hardware.camera": true,
        "android.hardware.screen.landscape": true,
        "android.hardware.ram.normal": true,
        "com.samsung.android.api.version.2402": true,
        "com.samsung.android.api.version.2403": true,
        "com.samsung.android.api.version.2501": true,
        "com.samsung.android.api.version.2502": true,
        "com.samsung.android.api.version.2601": true,
        "com.samsung.android.api.version.2701": true,
        "com.sec.feature.cover": true,
        "com.sec.feature.findo": true,
        "android.software.managed_users": true,
        "com.sec.feature.nsflp": true,
        "android.software.webview": true,
        "android.hardware.camera.any": true,
        "com.samsung.android.sdk.camera.processor.dof": true,
        "com.samsung.android.sdk.camera.processor.gif": true,
        "com.samsung.android.sdk.camera.processor.hdr": true,
        "com.samsung.android.sdk.camera.processor.lls": true,
        "com.samsung.feature.device_category_tablet_low_end": true,
        "android.software.connectionservice": true,
        "android.hardware.touchscreen.multitouch.distinct": true,
        "android.hardware.location.network": true,
        "android.software.cts": true,
        "android.software.sip": true,
        "android.hardware.wifi.direct": true,
        "android.software.live_wallpaper": true,
        "android.software.freeform_window_management": true,
        "android.hardware.location.gps": true,
        "com.sec.feature.fingerprint_ui": true,
        "android.software.midi": true,
        "com.sec.feature.support_mst": true,
        "android.hardware.wifi": true,
        "android.hardware.location": true,
        "android.hardware.vulkan.level": true,
        "com.sec.feature.cover.flip": true,
        "android.hardware.telephony": true,
        "com.sec.android.smartface.smart_stay": true,
        "glEsVersion": "3.2"
    },
    "PHONE_MODEL": "SM-T585",
    "PRODUCT": "gtaxlltexx",
    "TOTAL_MEM_SIZE": 26809225216
}
```
ACRA configuration
```kotlin
val builder = CoreConfigurationBuilder(this)
    .setBuildConfigClass(BuildConfig::class.java)
    .setApplicationLogFileDir(Directory.FILES)
    .setApplicationLogFile("$subLogDir/$logFileName")
    .setApplicationLogFileLines(-1) // should mean: all lines
    .setReportContent(
        ReportField.ANDROID_VERSION,
        ReportField.APP_VERSION_CODE,
        ReportField.APP_VERSION_NAME,
        ReportField.APPLICATION_LOG,
        ReportField.AVAILABLE_MEM_SIZE,
        ReportField.BRAND,
        ReportField.BUILD_CONFIG,
        ReportField.BUILD,
        ReportField.CRASH_CONFIGURATION,
        ReportField.CUSTOM_DATA,
        ReportField.DEVICE_FEATURES,
        ReportField.DEVICE_FEATURES,
        ReportField.DISPLAY,
        ReportField.DUMPSYS_MEMINFO,
        ReportField.FILE_PATH,
        ReportField.INITIAL_CONFIGURATION,
        ReportField.IS_SILENT,
        ReportField.LOGCAT,
        ReportField.PACKAGE_NAME,
        ReportField.PHONE_MODEL,
        ReportField.PRODUCT,
        ReportField.REPORT_ID,
        ReportField.SHARED_PREFERENCES,
        ReportField.STACK_TRACE,
        ReportField.TOTAL_MEM_SIZE,
        ReportField.USER_APP_START_DATE,
        ReportField.USER_CRASH_DATE
    )
builder.getPluginConfigurationBuilder(SchedulerConfigurationBuilder::class.java)
    .setRestartAfterCrash(true)
    .setEnabled(true)
builder.getPluginConfigurationBuilder(MailSenderConfigurationBuilder::class.java)
    .setReportAsFile(true)
    .setReportFileName(getString(R.string.report_filename))
    .setSubject(getString(R.string.report_mail_subject))
    .setBody(getString(R.string.report_mail_body))
    .setMailTo(getString(R.string.report_mail_to))
    .setEnabled(true)
```

**Comment by cy-ddg** [comment]
I was able to work around the issue by creating a custom report sender:

LargeFileMailSender.kt
```kotlin
class LargeFileMailSender(config: CoreConfiguration) : EmailIntentSender(config) {

    override fun buildResolveIntent(subject: String, body: String): Intent {
        val intent = super.buildResolveIntent(subject, body)
        // we want to avoid [this error](https://github.com/ACRA/acra/issues/775), so for the
        // resolve intent we use an empty body
        intent.putExtra(Intent.EXTRA_TEXT, "");
        return intent;
    }

}
```
Register it using a custom factory:
```kotlin
@AutoService(ReportSenderFactory::class)
class LargeFileMailSenderFactory: ReportSenderFactory {
    override fun create(context: Context, config: CoreConfiguration): ReportSender {
        return LargeFileMailSender(config)
    }
}
```
and disable the built in mail reporter
```kotlin
builder.getPluginConfigurationBuilder(MailSenderConfigurationBuilder::class.java)
    .setReportAsFile(true)
    .setReportFileName(getString(R.string.report_filename))
    .setSubject(getString(R.string.report_mail_subject))
    .setBody(getString(R.string.report_mail_body))
    .setMailTo(getString(R.string.report_mail_to))
    // we don't want the built in EmailIntentSender to be used, so we disable it here.
    // our own reporter will still be created using the LargeFileMailSenderFactory
    .setEnabled(false)
```

**Comment by F43nd1r** [comment]
Try using attachment instead of applicationlog:

```java
.setAttachmentUris("content://$applicationId.acra/files/$subLogDir/$logFileName")
``` 
instead of
```java
.setApplicationLogFileDir(Directory.FILES)
.setApplicationLogFile("$subLogDir/$logFileName")
.setApplicationLogFileLines(-1) // should mean: all lines
```

I'm thinking of deprecating application log in favor of attachments, as its only advantage is the ability to limit lines, while attachments provide a lot more flexibility in general.
