### ISSUE TITLE
Unable to configure ACRA 5.1.3 at runtime

### ISSUE THREAD

**Issue by hshandilya-navana** [ACRA/acra#781]
I'm trying to configure ACRA like so in `attachBaseContext`, after calling `super`.

```java
final CoreConfigurationBuilder configurationBuilder = new CoreConfigurationBuilder(this);
configurationBuilder.setBuildConfigClass(BuildConfig.class)
    .setReportFormat(StringFormat.JSON);
configurationBuilder
    .getPluginConfigurationBuilder(NotificationConfigurationBuilder.class)
    .setChannelName(getString(R.string.acra_notification_title))
    .setTitle(getString(R.string.acra_notification_title))
    .setText(getString(R.string.acra_notification_text));
configurationBuilder.getPluginConfigurationBuilder(HttpSenderConfigurationBuilder.class)
    .setBasicAuthLogin("foo")
    .setBasicAuthPassword("bar")
    .setUri("https://example.com")
    .setHttpMethod(HttpSender.Method.POST);
ACRA.init(this, configurationBuilder);
```

This is causing my Application class to fail to start, with this error:

```java
FATAL EXCEPTION: main
Process: com.navana.chatbotdemo, PID: 27254
java.lang.RuntimeException: Unable to instantiate application com.navana.chatbotdemo.Application: java.lang.IllegalAccessException: java.lang.Class<com.navana.chatbotdemo.Application> is not accessible from java.lang.Class<android.app.AppComponentFactory>
    at android.app.LoadedApk.makeApplication(LoadedApk.java:1296)
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6830)
    at android.app.ActivityThread.access$1300(ActivityThread.java:268)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1982)
    at android.os.Handler.dispatchMessage(Handler.java:107)
    at android.os.Looper.loop(Looper.java:237)
    at android.app.ActivityThread.main(ActivityThread.java:7814)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1068)
Caused by: java.lang.IllegalAccessException: java.lang.Class<com.navana.chatbotdemo.Application> is not accessible from java.lang.Class<android.app.AppComponentFactory>
    at java.lang.Class.newInstance(Native Method)
    at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
    at androidx.core.app.CoreComponentFactory.instantiateApplication(CoreComponentFactory.java:47)
    at android.app.Instrumentation.newApplication(Instrumentation.java:1156)
    at android.app.LoadedApk.makeApplication(LoadedApk.java:1288)
    ... 9 more
```

The device I'm testing on is a Samsung SM-M307F running Android 10-based OneUI 2.0.

**Comment by hshandilya-navana** [comment]
For whatever it's worth, configuring through the annotations also fails similarly.

**Comment by F43nd1r** [comment]
Are you using legacy multidex? https://github.com/ACRA/acra/wiki/Troubleshooting-Guide#legacy-multidex

**Comment by hshandilya-navana** [comment]
> Are you using legacy multidex? https://github.com/ACRA/acra/wiki/Troubleshooting-Guide#legacy-multidex

Nope, single DEX file.

**Comment by F43nd1r** [comment]
Well, the stacktrace shows nothing ACRA specific, so I can only guess... is your application class not public?

**Comment by hshandilya-navana** [comment]
> Well, the stacktrace shows nothing ACRA specific, so I can only guess... is your application class not public?

Welp, that was it, now I just feel stupid for overlooking that. Thanks for your help and for the work on ACRA and Acrarium!
