### ISSUE TITLE
Acra scheduler not restarting the app

### ISSUE THREAD

**Issue by pzienowicz** [ACRA/acra#783]
android 8.1
dependencies:
`implementation "ch.acra:acra-http:5.5.1"`
`implementation "ch.acra:acra-advanced-scheduler:5.5.1"`

configuration:
`
@AcraScheduler(
    restartAfterCrash = true
)
`

1. When crash happens, app is not restarted and in logs I can see:

> 2020-06-11 21:37:27.638 19846-19899/pl.pzienowicz.quizbox E/ACRA: ACRA caught a IllegalArgumentException for pl.pzienowicz.quizbox
    java.lang.IllegalArgumentException: You're trying to build a job with no constraints, this is not allowed.
        at android.app.job.JobInfo$Builder.build(JobInfo.java:1125)
        at org.acra.scheduler.DefaultSenderScheduler.scheduleReportSending(DefaultSenderScheduler.java:62)
        at org.acra.scheduler.SchedulerStarter.scheduleReports(SchedulerStarter.java:66)
        at org.acra.startup.StartupProcessorExecutor.lambda$null$0$StartupProcessorExecutor(StartupProcessorExecutor.java:86)
        at org.acra.startup.-$$Lambda$StartupProcessorExecutor$G9i7BXvdx8yfFTQ9dkfd2bK9Cf8.run(Unknown Source:6)
        at java.lang.Thread.run(Thread.java:764)

2. My next step was to add `requiresNetworkType` to scheduler configuration like this:
`
@AcraScheduler(
    requiresNetworkType = JobInfo.NETWORK_TYPE_ANY,
    restartAfterCrash = true
)`

And after build, restarts work as expected. But.... it works only for this build. When I build app one more time, restarts don't work again. Log with crash error is sent to my acralyzer correctly but nothing more. No other errors in console.
I realized that it works only when it is preceded by exception from step 1 but I don't see any dependence here.
Do you have any idea what is wrong?

**Comment by F43nd1r** [comment]
1. this error is a regression introduced with 40ab1a7e7e5ff97b2b98380dbd6e8356736f97f9. Should only happen if you apply no constraints.

2. Very weird behaviour, restarts should be independent of scheduling.

**Comment by pzienowicz** [comment]
> 1. this error is a regression introduced with [40ab1a7](https://github.com/ACRA/acra/commit/40ab1a7e7e5ff97b2b98380dbd6e8356736f97f9). Should only happen if you apply no constraints.

Exactly, but it happens on the newest version for Oreo.

> 2. Very weird behaviour, restarts should be independent of scheduling.

I am going to check this issue on another device with another android version.

**Comment by pzienowicz** [comment]
Found some log that could be helpful. It occurs after the crash.

> 06-12 09:38:55.372 9256-9347/pl.pzienowicz.quizbox I/System: android.system.ErrnoException: kill failed: ESRCH (No such process)
        at libcore.io.Posix.kill(Native Method)
        at libcore.io.ForwardingOs.kill(ForwardingOs.java:105)
        at java.lang.ProcessManager$ProcessImpl.destroy(ProcessManager.java:260)
        at org.acra.collector.LogCatCollector.collectLogCat(LogCatCollector.java:98)
        at org.acra.collector.LogCatCollector.collect(LogCatCollector.java:123)
        at org.acra.collector.BaseReportFieldCollector.collect(BaseReportFieldCollector.java:73)
        at org.acra.data.CrashReportDataFactory.lambda$createCrashData$1$CrashReportDataFactory(CrashReportDataFactory.java:88)
        at org.acra.data.-$$Lambda$CrashReportDataFactory$JhNXduZFyp6NfMtDKKl8MZ9kTPI.run(lambda)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)


Of course when this error appears, app is not restarted.

**Comment by F43nd1r** [comment]
Hmm, there should be a CollectorException associated with that.
I'll need some more logs. Please turn on `ACRA.DEV_LOGGING` and post the unfiltered log from crash to finish.

**Comment by pzienowicz** [comment]
Sure, full log is here.
[acra.txt](https://github.com/ACRA/acra/files/4800954/acra.txt)

**Comment by F43nd1r** [comment]
Still not sure what is going on, but here's an idea: It seems android prevents an activity from starting if it didn't finish its last creation. Or in other words: an exception in onCreate seems to prevent us from restarting.
Could you test to trigger an exception with e.g. a button?

**Comment by pzienowicz** [comment]
The same.
Logs here: [acra2.txt](https://github.com/ACRA/acra/files/4832853/acra2.txt)

**Comment by F43nd1r** [comment]
Are you sure the RestartingAdministrator is even active? Can't find any reference in any of your logs.

**Comment by pzienowicz** [comment]
@F43nd1r you mean this configuration?
> @AcraScheduler( restartAfterCrash = true )

Yes, it is still in the code.
Should I find some specific logs for this RestartingAdministrator?

**Comment by F43nd1r** [comment]
On App startup with dev loggin active you should find `Loaded ReportingAdministrator of type org.acra.scheduler.RestartingAdministrator` in the logs.

**Comment by pzienowicz** [comment]
Sorry, my bad - dev logging flag was enabled after init function.
Here new logs, with flag set correctly: [acra3.txt](https://github.com/ACRA/acra/files/4852570/acra3.txt)
Exception thrown from onTouchListener, app not restarted.

**Comment by F43nd1r** [comment]
Yeah, I finally managed to reproduce. Fix is on the master branch

**Comment by pzienowicz** [comment]
Nice! :) When can we expect the release?

**Comment by F43nd1r** [comment]
I'm currently waiting on the gradle plugin portal to approve my fork of the gradle-release plugin, as the official release has problems with ACRAs build. Shouldn't take longer than a few days. (next release will be 5.6.2, probably with only this change).

**Comment by F43nd1r** [comment]
@pzienowicz released now.
