### ISSUE TITLE
Acra Http SSL problems on older Android

### ISSUE THREAD

**Issue by ehrlichja** [ACRA/acra#792]
- Acra 5.1.3
- Android 17 runtime
- I am also importing okhttp 3.12.11, not sure if this is causing any override

```
 org.acra.sender.ReportSenderException: Policy marked this task as incomplete. ACRA will try to send this report again.
        at org.acra.sender.ReportDistributor.sendCrashReport(ReportDistributor.java:123)
        at org.acra.sender.ReportDistributor.distribute(ReportDistributor.java:76)
        at org.acra.sender.SenderService.onHandleWork(SenderService.java:94)
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:392)
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383)
        at android.os.AsyncTask$2.call(AsyncTask.java:288)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:841)
     Caused by: org.acra.sender.ReportSenderException: Error while sending JSON report via Http POST
        at org.acra.sender.HttpSender.send(HttpSender.java:161)
        at org.acra.sender.ReportDistributor.sendCrashReport(ReportDistributor.java:111)
        at org.acra.sender.ReportDistributor.distribute(ReportDistributor.java:76) 
        at org.acra.sender.SenderService.onHandleWork(SenderService.java:94) 
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:392) 
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383) 
        at android.os.AsyncTask$2.call(AsyncTask.java:288) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:841) 
     Caused by: javax.net.ssl.SSLException: SSL handshake aborted: ssl=0xb833c310: I/O error during system call, Connection reset by peer
        at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
        at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:405)
        at com.android.okhttp.Connection.upgradeToTls(Connection.java:146)
        at com.android.okhttp.Connection.connect(Connection.java:107)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:294)
        at com.android.okhttp.internal.http.HttpEngine.sendSocketRequest(HttpEngine.java:255)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:206)
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:345)
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:89)
        at com.android.okhttp.internal.http.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:161)
        at org.acra.http.BaseHttpRequest.writeContent(BaseHttpRequest.java:179)
        at org.acra.http.BaseHttpRequest.send(BaseHttpRequest.java:103)
        at org.acra.sender.HttpSender.sendWithoutAttachments(HttpSender.java:190)
        at org.acra.sender.HttpSender.sendHttpRequests(HttpSender.java:172)
        at org.acra.sender.HttpSender.send(HttpSender.java:156)
        at org.acra.sender.ReportDistributor.sendCrashReport(ReportDistributor.java:111) 
        at org.acra.sender.ReportDistributor.distribute(ReportDistributor.java:76) 
        at org.acra.sender.SenderService.onHandleWork(SenderService.java:94) 
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:392) 
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383) 
        at android.os.AsyncTask$2.call(AsyncTask.java:288) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:841) 
```

In other parts of my code, I had to create a custom Tls SocketFactory to explicitly enable TLS 1.2 on such an old android version. Maybe this is related? Any way to make Acra use my custom SocketFactory?

If I run the same code on Android 27, it works.

**Comment by F43nd1r** [comment]
I've created a PR which'll allow you to set your supported tls versions. It also comes with a default configuration which enables all tls versions.

**Comment by ehrlichja** [comment]
Thank you! Looking forward to using this enhancement.

**Comment by ehrlichja** [comment]
I upgraded the acra library but am still getting the same error on android 17. Also tried with adding ```.setTlsProtocols(TLS.V1, TLS.V1_1, TLS.V1_2, TLS.V1_3)``` when building the configuration of the http sender.

**Comment by F43nd1r** [comment]
I've tested sending to a TLSV1.2 only server from an android 16 emulator with and without okhttp 3.12.11. Everything worked out. Is your server TLSV1.3 only? If not, the problem lies elsewhere. 
In that case this could become complicated, quoting https://stackoverflow.com/a/31345743/4388512 :
> After googling I found that the issue is everywhere but without any concrete resolution.
