### ISSUE TITLE
AcraHttpSender fails with javax.net.ssl.SSLHandshakeException on Android 4.4.4 [ACRA 5.7.0]

### ISSUE THREAD

**Issue by Yakobo-tz** [ACRA/acra#809]
AcraHttpSender fails to send bug reports to my cloudant backend with the following Log:

```
09-15 10:07:12.974 28029-28068/org.yakobo.smartmineralogist I/ACRA: Sending report /data/data/org.yakobo.smartmineralogist/app_ACRA-approved/2020-09-09T12:05:53.186+03:00-IS_SILENT.stacktrace
09-15 10:07:12.994 28029-28068/org.yakobo.smartmineralogist D/ACRA: Sending report using org.acra.sender.HttpSender
09-15 10:07:12.994 28029-28068/org.yakobo.smartmineralogist D/ACRA: Connect to https://'my_acralyzer_back_end'/_design/acra-storage/_update/report
09-15 10:07:13.014 28029-28068/org.yakobo.smartmineralogist D/ACRA: Checking plugin Configurations : ImmutableList{[org.acra.config.HttpSenderConfiguration@42a8e458]} for class : class org.acra.config.HttpSenderConfiguration
09-15 10:07:13.014 28029-28068/org.yakobo.smartmineralogist D/ACRA: Checking plugin Configuration : org.acra.config.HttpSenderConfiguration@42a8e458 against plugin class : class org.acra.config.HttpSenderConfiguration
09-15 10:07:13.024 28029-28068/org.yakobo.smartmineralogist D/ACRA: Checking plugin Configurations : ImmutableList{[org.acra.config.HttpSenderConfiguration@42a8e458]} for class : class org.acra.config.HttpSenderConfiguration
09-15 10:07:13.024 28029-28068/org.yakobo.smartmineralogist D/ACRA: Checking plugin Configuration : org.acra.config.HttpSenderConfiguration@42a8e458 against plugin class : class org.acra.config.HttpSenderConfiguration
09-15 10:07:13.104 28029-28068/org.yakobo.smartmineralogist D/ACRA: Sending request to https://'my_acralyzer_back_end'/_design/acra-storage/_update/report/edb9157f-031e-4637-a20f-94ed5592aba6
09-15 10:07:13.104 28029-28068/org.yakobo.smartmineralogist D/ACRA: Http PUT content : 
09-15 10:07:13.104 28029-28068/org.yakobo.smartmineralogist D/ACRA: {"REPORT_ID":"my_generated_report_id"}
09-15 10:07:14.544 28029-28068/org.yakobo.smartmineralogist E/ACRA: Failed to send crash report for /data/data/org.yakobo.smartmineralogist/app_ACRA-approved/2020-09-09T12:05:53.186+03:00-IS_SILENT.stacktrace
    org.acra.sender.ReportSenderException: Policy marked this task as incomplete. ACRA will try to send this report again.
        at org.acra.sender.ReportDistributor.sendCrashReport(ReportDistributor.java:127)
        at org.acra.sender.ReportDistributor.distribute(ReportDistributor.java:80)
        at org.acra.sender.SendingConductor.sendReports(SendingConductor.java:70)
        at org.acra.sender.LegacySenderService.lambda$onStartCommand$0$LegacySenderService(LegacySenderService.java:46)
        at org.acra.sender.-$$Lambda$LegacySenderService$G1vex_uwj9g85Q9UEGdH0tH4PPw.run(lambda)
        at java.lang.Thread.run(Thread.java:841)
     Caused by: org.acra.sender.ReportSenderException: Error while sending JSON report via Http PUT
        at org.acra.sender.HttpSender.send(HttpSender.java:137)
        at org.acra.sender.ReportSender$-CC.$default$send(ReportSender.java:54)
        at org.acra.sender.HttpSender.send(HttpSender.java)
        at org.acra.sender.ReportDistributor.sendCrashReport(ReportDistributor.java:115)
        at org.acra.sender.ReportDistributor.distribute(ReportDistributor.java:80) 
        at org.acra.sender.SendingConductor.sendReports(SendingConductor.java:70) 
        at org.acra.sender.LegacySenderService.lambda$onStartCommand$0$LegacySenderService(LegacySenderService.java:46) 
        at org.acra.sender.-$$Lambda$LegacySenderService$G1vex_uwj9g85Q9UEGdH0tH4PPw.run(lambda) 
        at java.lang.Thread.run(Thread.java:841) 
     Caused by: javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x76028e78: Failure in SSL library, usually a protocol error
    error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:741 0x733cdd74:0x00000000)
        at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:448)
        at com.android.okhttp.Connection.upgradeToTls(Connection.java:146)
        at com.android.okhttp.Connection.connect(Connection.java:107)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:294)
        at com.android.okhttp.internal.http.HttpEngine.sendSocketRequest(HttpEngine.java:255)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:206)
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:345)
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:89)
        at com.android.okhttp.internal.http.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:161)
        at org.acra.http.BaseHttpRequest.writeContent(BaseHttpRequest.java:185)
        at org.acra.http.BaseHttpRequest.send(BaseHttpRequest.java:107)
        at org.acra.sender.HttpSender.sendWithoutAttachments(HttpSender.java:166)
        at org.acra.sender.HttpSender.sendHttpRequests(HttpSender.java:154)
        at org.acra.sender.HttpSender.send(HttpSender.java:132)
        	... 8 more
     Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x76028e78: Failure in SSL library, usually a protocol error
    error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:741 0x733cdd74:0x00000000)
        at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
        at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:405)
        	... 21 more
```

**Version**
This occurs on Android 4.4.4 with the Google LG Nexus 5, I did not test if older versions are affected. This does not occur on Android 5.0 and higher.

My Application class:

```java
@AcraCore(buildConfigClass = BuildConfig.class, reportFormat = StringFormat.JSON)
@AcraHttpSender(uri = "my_backend_uri",
        httpMethod = HttpSender.Method.PUT,
        basicAuthLogin="some_user",
        basicAuthPassword="some_password")
public final class MyApplication extends Application{

	@Override
	protected void attachBaseContext(Context base){
		super.attachBaseContext(base);
        	//TODO Remove this before shipping
        	ACRA.DEV_LOGGING = true;
		ACRA.init(this);
	}
}
```

**Comment by F43nd1r** [comment]
Seems like your device is falling back to sslv3, which means a tls connection must've been rejected by the server. Do you have any logs from the server side?

**Comment by Yakobo-tz** [comment]
Backend is handled by Cloudant + acralyzer. Didn't check the server logs but the Cloudant monitoring dashboard does not detect any rejected incoming connections.
