### ISSUE TITLE
Cannot send report to Tracepot

### ISSUE THREAD

**Issue by karelkryda** [ACRA/acra#818]
Hello,
I'm trying to set up ACRA integration with the Tracepot backend. I'm getting the following error
```
D/ACRA: Sending report using org.acra.sender.HttpSender
    Connect to https://collector.tracepot.com/xxxxx
E/ACRA: Failed to send crash reports for /data/user/0/com.example.android/app_ACRA-approved/2020-12-17T22:34:43.305+01:00.stacktrace
    org.acra.sender.ReportSenderException: Policy marked this task as incomplete. ACRA will try to send this report again.
        at org.acra.sender.ReportDistributor.sendCrashReport(ReportDistributor.kt:104)
        at org.acra.sender.ReportDistributor.distribute(ReportDistributor.kt:60)
        at org.acra.sender.SendingConductor.sendReports(SendingConductor.kt:50)
        at org.acra.sender.JobSenderService$onStartJob$1.run(JobSenderService.kt:24)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: org.acra.sender.ReportSenderException: Error while sending JSON report via Http POST
        at org.acra.sender.HttpSender.send(HttpSender.kt:108)
        at org.acra.sender.ReportSender$DefaultImpls.send(ReportSender.kt:55)
        at org.acra.sender.HttpSender.send(HttpSender.kt:69)
        at org.acra.sender.ReportDistributor.sendCrashReport(ReportDistributor.kt:96)
        at org.acra.sender.ReportDistributor.distribute(ReportDistributor.kt:60) 
        at org.acra.sender.SendingConductor.sendReports(SendingConductor.kt:50) 
        at org.acra.sender.JobSenderService$onStartJob$1.run(JobSenderService.kt:24) 
        at java.lang.Thread.run(Thread.java:919) 
     Caused by: java.lang.NullPointerException
        at org.acra.sender.HttpSender.send(HttpSender.kt:96)
        at org.acra.sender.ReportSender$DefaultImpls.send(ReportSender.kt:55) 
        at org.acra.sender.HttpSender.send(HttpSender.kt:69) 
        at org.acra.sender.ReportDistributor.sendCrashReport(ReportDistributor.kt:96) 
        at org.acra.sender.ReportDistributor.distribute(ReportDistributor.kt:60) 
        at org.acra.sender.SendingConductor.sendReports(SendingConductor.kt:50) 
        at org.acra.sender.JobSenderService$onStartJob$1.run(JobSenderService.kt:24) 
        at java.lang.Thread.run(Thread.java:919) 
```

Android code

```
CoreConfigurationBuilder builder = new CoreConfigurationBuilder(this);
        builder.setBuildConfigClass(BuildConfig.class);

        builder.getPluginConfigurationBuilder(HttpSenderConfigurationBuilder.class).setUri("https://collector.tracepot.com/xxxxx");
        builder.getPluginConfigurationBuilder(ToastConfigurationBuilder.class).setText(getResources().getString(R.string.acra_toast_text));
        builder.getPluginConfigurationBuilder(SchedulerConfigurationBuilder.class).setRestartAfterCrash(true);
        builder.getPluginConfigurationBuilder(SchedulerConfigurationBuilder.class).setRequiresNetworkType(JobInfo.NETWORK_TYPE_UNMETERED);

        builder.getPluginConfigurationBuilder(HttpSenderConfigurationBuilder.class).setEnabled(true);
        builder.getPluginConfigurationBuilder(ToastConfigurationBuilder.class).setEnabled(true);
        builder.getPluginConfigurationBuilder(SchedulerConfigurationBuilder.class).setEnabled(true);

        ACRA.DEV_LOGGING = true;
        ACRA.init(this, builder);
```

Thanks for help

**Comment by F43nd1r** [comment]
Please include your ACRA & Android versions.

**Comment by karelkryda** [comment]
@F43nd1r I downgraded version from 5.8.0-alpha to 5.7.0 and now it is working :)

**Comment by karelkryda** [comment]
But toast notification and auto restart after crash are not working now...

I should read doc again tomorrow...

**Comment by haaami01** [comment]
Thank you very much! 😊
