### ISSUE TITLE
Loading ACRA through module not showing dialog

### ISSUE THREAD

**Issue by arcanewater** [ACRA/acra#828]
**Describe the bug**
I am trying to load ACRA through module in my app where i forward onCreate call to my module class, it seems it initilized normally but when app crashes dialog is not shown. Is only possible to init ACRA in attachBaseContext or should work with onCreate too ?

Here is full log of init/crash:
```
2021-02-09 08:05:45.757 6741-6741/com.sample.app D/ACRA: ServicePluginLoader loading services from ServiceLoader : java.util.ServiceLoader[org.acra.config.ConfigurationBuilderFactory]
2021-02-09 08:05:45.771 6741-6741/com.sample.app D/ACRA: Loaded ConfigurationBuilderFactory of type org.acra.config.DialogConfigurationBuilderFactory
2021-02-09 08:05:45.771 6741-6741/com.sample.app D/ACRA: Loaded ConfigurationBuilderFactory of type org.acra.config.MailSenderConfigurationBuilderFactory
2021-02-09 08:05:45.771 6741-6741/com.sample.app D/ACRA: Found ConfigurationBuilderFactories : [org.acra.config.DialogConfigurationBuilderFactory@31d1c, org.acra.config.MailSenderConfigurationBuilderFactory@3da1d25]
2021-02-09 08:05:45.776 6741-6741/com.sample.app D/ACRA: Found ConfigurationBuilders : [org.acra.config.DialogConfigurationBuilderImpl@85ddefa, org.acra.config.MailSenderConfigurationBuilderImpl@9444cab]
2021-02-09 08:05:45.781 6741-6741/com.sample.app D/ACRA: Using default Report Fields
2021-02-09 08:05:45.785 6741-6741/com.sample.app D/ACRA: ACRA processName='com.sample.app'
2021-02-09 08:05:45.789 6741-6741/com.sample.app I/ACRA: ACRA is enabled for com.sample.app, initializing...
2021-02-09 08:05:45.791 6741-6741/com.sample.app D/ACRA: ServicePluginLoader loading services from ServiceLoader : java.util.ServiceLoader[org.acra.collector.Collector]
2021-02-09 08:05:45.799 6741-6741/com.sample.app D/ACRA: Loaded Collector of type org.acra.collector.ConfigurationCollector
2021-02-09 08:05:45.799 6741-6741/com.sample.app D/ACRA: Loaded Collector of type org.acra.collector.CustomDataCollector
2021-02-09 08:05:45.800 6741-6741/com.sample.app D/ACRA: Loaded Collector of type org.acra.collector.DeviceFeaturesCollector
2021-02-09 08:05:45.800 6741-6741/com.sample.app D/ACRA: Loaded Collector of type org.acra.collector.DeviceIdCollector
2021-02-09 08:05:45.803 6741-6741/com.sample.app D/ACRA: Loaded Collector of type org.acra.collector.DisplayManagerCollector
2021-02-09 08:05:45.804 6741-6741/com.sample.app D/ACRA: Loaded Collector of type org.acra.collector.DropBoxCollector
2021-02-09 08:05:45.805 6741-6741/com.sample.app D/ACRA: Loaded Collector of type org.acra.collector.LogCatCollector
2021-02-09 08:05:45.806 6741-6741/com.sample.app D/ACRA: Loaded Collector of type org.acra.collector.LogFileCollector
2021-02-09 08:05:45.807 6741-6741/com.sample.app D/ACRA: Loaded Collector of type org.acra.collector.MediaCodecListCollector
2021-02-09 08:05:45.808 6741-6741/com.sample.app D/ACRA: Loaded Collector of type org.acra.collector.MemoryInfoCollector
2021-02-09 08:05:45.809 6741-6741/com.sample.app D/ACRA: Loaded Collector of type org.acra.collector.PackageManagerCollector
2021-02-09 08:05:45.810 6741-6741/com.sample.app D/ACRA: Loaded Collector of type org.acra.collector.ReflectionCollector
2021-02-09 08:05:45.810 6741-6741/com.sample.app D/ACRA: Loaded Collector of type org.acra.collector.SettingsCollector
2021-02-09 08:05:45.811 6741-6741/com.sample.app D/ACRA: Loaded Collector of type org.acra.collector.SharedPreferencesCollector
2021-02-09 08:05:45.812 6741-6741/com.sample.app D/ACRA: Loaded Collector of type org.acra.collector.SimpleValuesCollector
2021-02-09 08:05:45.812 6741-6741/com.sample.app D/ACRA: Loaded Collector of type org.acra.collector.StacktraceCollector
2021-02-09 08:05:45.813 6741-6741/com.sample.app D/ACRA: Loaded Collector of type org.acra.collector.ThreadCollector
2021-02-09 08:05:45.847 6741-6741/com.sample.app D/ACRA: Loaded Collector of type org.acra.collector.TimeCollector
2021-02-09 08:05:45.858 6741-6741/com.sample.app D/ACRA: ServicePluginLoader loading services from ServiceLoader : java.util.ServiceLoader[org.acra.scheduler.SenderSchedulerFactory]
2021-02-09 08:05:45.869 6741-6741/com.sample.app D/ACRA: ServicePluginLoader loading services from ServiceLoader : java.util.ServiceLoader[org.acra.config.ReportingAdministrator]
2021-02-09 08:05:46.050 6741-6741/com.sample.app D/ACRA: onActivityCreated class com.sample.app.MainActivity
2021-02-09 08:05:46.783 6741-6741/com.sample.app D/ACRA: onActivityStarted class com.sample.app.MainActivity
2021-02-09 08:05:46.916 6741-6741/com.sample.app D/ACRA: onActivityResumed class com.sample.app.MainActivity
2021-02-09 08:05:46.965 6741-6867/com.sample.app D/ACRA: ServicePluginLoader loading services from ServiceLoader : java.util.ServiceLoader[org.acra.startup.StartupProcessor]
2021-02-09 08:05:46.976 6741-6867/com.sample.app D/ACRA: Loaded StartupProcessor of type org.acra.startup.UnapprovedStartupProcessor
2021-02-09 08:05:46.987 6741-6867/com.sample.app D/ACRA: Schedule report sending
2021-02-09 08:05:47.063 6741-6867/com.sample.app D/ACRA: config#reportSenderFactoryClasses : ImmutableList{[]}
2021-02-09 08:05:47.063 6741-6867/com.sample.app D/ACRA: Using PluginLoader to find ReportSender factories
2021-02-09 08:05:47.064 6741-6867/com.sample.app D/ACRA: ServicePluginLoader loading services from ServiceLoader : java.util.ServiceLoader[org.acra.sender.ReportSenderFactory]
2021-02-09 08:05:47.073 6741-6867/com.sample.app D/ACRA: Checking plugin Configurations : ImmutableList{[org.acra.config.DialogConfiguration@fcd1103, org.acra.config.MailSenderConfiguration@ab1b798]} for class : class org.acra.config.MailSenderConfiguration
2021-02-09 08:05:47.074 6741-6867/com.sample.app D/ACRA: Checking plugin Configuration : org.acra.config.DialogConfiguration@fcd1103 against plugin class : class org.acra.config.MailSenderConfiguration
2021-02-09 08:05:47.074 6741-6867/com.sample.app D/ACRA: Checking plugin Configuration : org.acra.config.MailSenderConfiguration@ab1b798 against plugin class : class org.acra.config.MailSenderConfiguration
2021-02-09 08:05:47.074 6741-6867/com.sample.app D/ACRA: Ignoring disabled ReportSenderFactory of type EmailIntentSenderFactory
2021-02-09 08:05:47.075 6741-6867/com.sample.app D/ACRA: reportSenderFactories : []
2021-02-09 08:05:47.075 6741-6867/com.sample.app D/ACRA: config#reportSenderFactoryClasses : ImmutableList{[]}
2021-02-09 08:05:47.075 6741-6867/com.sample.app D/ACRA: Using PluginLoader to find ReportSender factories
2021-02-09 08:05:47.075 6741-6867/com.sample.app D/ACRA: ServicePluginLoader loading services from ServiceLoader : java.util.ServiceLoader[org.acra.sender.ReportSenderFactory]
2021-02-09 08:05:47.080 6741-6867/com.sample.app D/ACRA: Checking plugin Configurations : ImmutableList{[org.acra.config.DialogConfiguration@fcd1103, org.acra.config.MailSenderConfiguration@ab1b798]} for class : class org.acra.config.MailSenderConfiguration
2021-02-09 08:05:47.080 6741-6867/com.sample.app D/ACRA: Checking plugin Configuration : org.acra.config.DialogConfiguration@fcd1103 against plugin class : class org.acra.config.MailSenderConfiguration
2021-02-09 08:05:47.081 6741-6867/com.sample.app D/ACRA: Checking plugin Configuration : org.acra.config.MailSenderConfiguration@ab1b798 against plugin class : class org.acra.config.MailSenderConfiguration
2021-02-09 08:05:47.081 6741-6867/com.sample.app D/ACRA: Ignoring disabled ReportSenderFactory of type EmailIntentSenderFactory
2021-02-09 08:05:47.081 6741-6867/com.sample.app D/ACRA: reportSenderFactories : []
2021-02-09 08:06:21.014 6741-6741/com.sample.app E/ACRA: ACRA caught a RuntimeException for com.sample.app
    java.lang.RuntimeException: This is a crash
        at com.sample.app.errorreporting.ErrorReportingFragment$onViewCreated$1.onClick(ErrorReportingFragment.kt:27)
        at android.view.View.performClick(View.java:7448)
        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:992)
        at android.view.View.performClickInternal(View.java:7425)
        at android.view.View.access$3600(View.java:810)
        at android.view.View$PerformClick.run(View.java:28305)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
2021-02-09 08:06:21.014 6741-6741/com.sample.app D/ACRA: Building report
2021-02-09 08:06:21.021 6741-6902/com.sample.app D/ACRA: Calling collector org.acra.collector.LogCatCollector
2021-02-09 08:06:21.024 6741-6901/com.sample.app D/ACRA: Calling collector org.acra.collector.DropBoxCollector
2021-02-09 08:06:21.025 6741-6904/com.sample.app D/ACRA: Calling collector org.acra.collector.ConfigurationCollector
2021-02-09 08:06:21.025 6741-6903/com.sample.app D/ACRA: Calling collector org.acra.collector.StacktraceCollector
2021-02-09 08:06:21.025 6741-6901/com.sample.app D/ACRA: Collector org.acra.collector.DropBoxCollector completed
2021-02-09 08:06:21.026 6741-6906/com.sample.app D/ACRA: Calling collector org.acra.collector.CustomDataCollector
2021-02-09 08:06:21.027 6741-6906/com.sample.app D/ACRA: Collector org.acra.collector.CustomDataCollector completed
2021-02-09 08:06:21.033 6741-6903/com.sample.app D/ACRA: Collector org.acra.collector.StacktraceCollector completed
2021-02-09 08:06:21.033 6741-6904/com.sample.app D/ACRA: Collector org.acra.collector.ConfigurationCollector completed
2021-02-09 08:06:21.033 6741-6906/com.sample.app D/ACRA: Calling collector org.acra.collector.DisplayManagerCollector
2021-02-09 08:06:21.034 6741-6901/com.sample.app D/ACRA: Calling collector org.acra.collector.MemoryInfoCollector
2021-02-09 08:06:21.034 6741-6902/com.sample.app D/ACRA: Retrieving logcat output (buffer:default)...
2021-02-09 08:06:21.038 6741-6907/com.sample.app D/ACRA: Calling collector org.acra.collector.DeviceFeaturesCollector
2021-02-09 08:06:21.039 6741-6908/com.sample.app D/ACRA: Calling collector org.acra.collector.DeviceIdCollector
2021-02-09 08:06:21.043 6741-6906/com.sample.app D/ACRA: Collector org.acra.collector.DisplayManagerCollector completed
2021-02-09 08:06:21.043 6741-6908/com.sample.app D/ACRA: Collector org.acra.collector.DeviceIdCollector completed
2021-02-09 08:06:21.044 6741-6908/com.sample.app D/ACRA: Calling collector org.acra.collector.ReflectionCollector
2021-02-09 08:06:21.045 6741-6904/com.sample.app D/ACRA: Calling collector org.acra.collector.SharedPreferencesCollector
2021-02-09 08:06:21.047 6741-6906/com.sample.app D/ACRA: Calling collector org.acra.collector.SettingsCollector
2021-02-09 08:06:21.047 6741-6906/com.sample.app D/ACRA: Collector org.acra.collector.SettingsCollector completed
2021-02-09 08:06:21.048 6741-6904/com.sample.app D/ACRA: Collector org.acra.collector.SharedPreferencesCollector completed
2021-02-09 08:06:21.049 6741-6903/com.sample.app D/ACRA: Calling collector org.acra.collector.SimpleValuesCollector
2021-02-09 08:06:21.050 6741-6911/com.sample.app D/ACRA: Calling collector org.acra.collector.PackageManagerCollector
2021-02-09 08:06:21.051 6741-6913/com.sample.app D/ACRA: Calling collector org.acra.collector.TimeCollector
2021-02-09 08:06:21.051 6741-6906/com.sample.app D/ACRA: Calling collector org.acra.collector.MediaCodecListCollector
2021-02-09 08:06:21.052 6741-6906/com.sample.app D/ACRA: Collector org.acra.collector.MediaCodecListCollector completed
2021-02-09 08:06:21.052 6741-6904/com.sample.app D/ACRA: Calling collector org.acra.collector.LogFileCollector
2021-02-09 08:06:21.052 6741-6904/com.sample.app D/ACRA: Collector org.acra.collector.LogFileCollector completed
2021-02-09 08:06:21.053 6741-6907/com.sample.app D/ACRA: Collector org.acra.collector.DeviceFeaturesCollector completed
2021-02-09 08:06:21.054 6741-6911/com.sample.app D/ACRA: Collector org.acra.collector.PackageManagerCollector completed
2021-02-09 08:06:21.056 6741-6903/com.sample.app D/ACRA: Collector org.acra.collector.SimpleValuesCollector completed
2021-02-09 08:06:21.058 6741-6913/com.sample.app D/ACRA: Collector org.acra.collector.TimeCollector completed
2021-02-09 08:06:21.064 6741-6914/com.sample.app D/ACRA: Calling collector org.acra.collector.ThreadCollector
2021-02-09 08:06:21.064 6741-6914/com.sample.app D/ACRA: Collector org.acra.collector.ThreadCollector completed
2021-02-09 08:06:21.072 6741-6901/com.sample.app D/ACRA: Collector org.acra.collector.MemoryInfoCollector completed
2021-02-09 08:06:21.081 6741-6902/com.sample.app D/ACRA: Collector org.acra.collector.LogCatCollector completed
2021-02-09 08:06:21.101 6741-6908/com.sample.app D/ACRA: Collector org.acra.collector.ReflectionCollector completed
2021-02-09 08:06:21.102 6741-6741/com.sample.app D/ACRA: Finishing activities prior to killing the Process
2021-02-09 08:06:21.145 6741-6741/com.sample.app D/ACRA: Finished class com.sample.app.MainActivity
2021-02-09 08:06:21.146 6741-6741/com.sample.app D/ACRA: Writing crash report file /data/user/0/com.sample.app/app_ACRA-unapproved/2021-02-09T07:06:21.056+00:00.stacktrace
2021-02-09 08:06:21.176 6741-6741/com.sample.app D/ACRA: ServicePluginLoader loading services from ServiceLoader : java.util.ServiceLoader[org.acra.interaction.ReportInteraction]
2021-02-09 08:06:21.186 6741-6741/com.sample.app D/ACRA: Checking plugin Configurations : ImmutableList{[org.acra.config.DialogConfiguration@fcd1103, org.acra.config.MailSenderConfiguration@ab1b798]} for class : class org.acra.config.DialogConfiguration
2021-02-09 08:06:21.186 6741-6741/com.sample.app D/ACRA: Checking plugin Configuration : org.acra.config.DialogConfiguration@fcd1103 against plugin class : class org.acra.config.DialogConfiguration
2021-02-09 08:06:21.186 6741-6741/com.sample.app D/ACRA: Ignoring disabled ReportInteraction of type DialogInteraction
2021-02-09 08:06:21.186 6741-6741/com.sample.app D/ACRA: Mark 2021-02-09T07:06:21.056+00:00.stacktrace as approved.
2021-02-09 08:06:21.187 6741-6741/com.sample.app D/ACRA: Schedule report sending
2021-02-09 08:06:21.201 6741-6741/com.sample.app D/ACRA: config#reportSenderFactoryClasses : ImmutableList{[]}
2021-02-09 08:06:21.201 6741-6741/com.sample.app D/ACRA: Using PluginLoader to find ReportSender factories
2021-02-09 08:06:21.201 6741-6741/com.sample.app D/ACRA: ServicePluginLoader loading services from ServiceLoader : java.util.ServiceLoader[org.acra.sender.ReportSenderFactory]
2021-02-09 08:06:21.207 6741-6741/com.sample.app D/ACRA: Checking plugin Configurations : ImmutableList{[org.acra.config.DialogConfiguration@fcd1103, org.acra.config.MailSenderConfiguration@ab1b798]} for class : class org.acra.config.MailSenderConfiguration
2021-02-09 08:06:21.207 6741-6741/com.sample.app D/ACRA: Checking plugin Configuration : org.acra.config.DialogConfiguration@fcd1103 against plugin class : class org.acra.config.MailSenderConfiguration
2021-02-09 08:06:21.207 6741-6741/com.sample.app D/ACRA: Checking plugin Configuration : org.acra.config.MailSenderConfiguration@ab1b798 against plugin class : class org.acra.config.MailSenderConfiguration
2021-02-09 08:06:21.208 6741-6741/com.sample.app D/ACRA: Ignoring disabled ReportSenderFactory of type EmailIntentSenderFactory
2021-02-09 08:06:21.208 6741-6741/com.sample.app D/ACRA: reportSenderFactories : []
2021-02-09 08:06:21.208 6741-6741/com.sample.app D/ACRA: config#reportSenderFactoryClasses : ImmutableList{[]}
2021-02-09 08:06:21.208 6741-6741/com.sample.app D/ACRA: Using PluginLoader to find ReportSender factories
2021-02-09 08:06:21.208 6741-6741/com.sample.app D/ACRA: ServicePluginLoader loading services from ServiceLoader : java.util.ServiceLoader[org.acra.sender.ReportSenderFactory]
2021-02-09 08:06:21.213 6741-6741/com.sample.app D/ACRA: Checking plugin Configurations : ImmutableList{[org.acra.config.DialogConfiguration@fcd1103, org.acra.config.MailSenderConfiguration@ab1b798]} for class : class org.acra.config.MailSenderConfiguration
2021-02-09 08:06:21.214 6741-6741/com.sample.app D/ACRA: Checking plugin Configuration : org.acra.config.DialogConfiguration@fcd1103 against plugin class : class org.acra.config.MailSenderConfiguration
2021-02-09 08:06:21.214 6741-6741/com.sample.app D/ACRA: Checking plugin Configuration : org.acra.config.MailSenderConfiguration@ab1b798 against plugin class : class org.acra.config.MailSenderConfiguration
2021-02-09 08:06:21.214 6741-6741/com.sample.app D/ACRA: Ignoring disabled ReportSenderFactory of type EmailIntentSenderFactory
2021-02-09 08:06:21.214 6741-6741/com.sample.app D/ACRA: reportSenderFactories : []
2021-02-09 08:06:21.214 6741-6741/com.sample.app D/ACRA: Wait for Interactions + worker ended. Kill Application ? true


```

**Version**
 - Android: 11
 - ACRA: 5.7.0

**Comment by F43nd1r** [comment]
> Ignoring disabled ReportInteraction of type DialogInteraction

Your dialog isn't enabled.

**Comment by arcanewater** [comment]
Somehow i was able to init it with configuration builder but not with anotations, will check if i can check why.
