### ISSUE TITLE
ACRA fails when core library desugaring is enabled 

### ISSUE THREAD

**Issue by fareed945** [ACRA/acra#842]
Hey,
I came across this issue today, when I enabled the corelibrarydesugaringmode on android, I wasn't able to run my APP due to a crash in ACRA.
Following was the error
Caused by: java.lang.ClassNotFoundException: Didn't find class "java.util.function.Consumer" on path: DexPathList

this is the stacktrace
 java.lang.NoClassDefFoundError: java.util.function.Consumer
        at libcore.reflect.InternalNames.getClass(InternalNames.java:55)
        at java.lang.Class.getDexCacheType(Class.java:476)
        at java.lang.reflect.AbstractMethod.getParameterTypes(AbstractMethod.java:166)
        at java.lang.reflect.Method.getParameterTypes(Method.java:170)
        at java.lang.Class.getDeclaredMethods(Class.java:673)
        at java.io.ObjectStreamClass.computeSerialVersionUID(ObjectStreamClass.java:566)
        at java.io.ObjectStreamClass.createClassDesc(ObjectStreamClass.java:279)
        at java.io.ObjectStreamClass.lookupStreamClass(ObjectStreamClass.java:1087)
        at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1554)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
        at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:959)
        at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:360)
        at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1054)
        at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1384)
        at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
        at org.acra.util.IOUtils.serialize(IOUtils.java:75)
        at org.acra.scheduler.DefaultSenderScheduler.scheduleReportSending(DefaultSenderScheduler.java:52)
        at org.acra.scheduler.SchedulerStarter.scheduleReports(SchedulerStarter.java:66)
        at org.acra.startup.StartupProcessorExecutor.lambda$null$0$StartupProcessorExecutor(StartupProcessorExecutor.java:86)
        at org.acra.startup.-$$Lambda$StartupProcessorExecutor$vr-B3Kby1WTBs7c-61N3dOEKizo.run(lambda)
        at java.lang.Thread.run(Thread.java:818)

Has anyone come across this ? Android version - 6, SDK - 23

**Comment by F43nd1r** [comment]
Please state your acra version.

**Comment by fareed945** [comment]
5.7.0

**Comment by F43nd1r** [comment]
Could not reproduce with the latest desugaring library (1.1.5)

**Comment by fareed945** [comment]
May I know as to which Android SDK you used for the test?

**Comment by F43nd1r** [comment]
Tried with both 23 and 30
Here's the relevant part of my build.gradle.kts
```kotlin
android {
    compileSdkVersion(23)

    defaultConfig {
        applicationId = "com.faendir.acratest"
        minSdkVersion(16)
        targetSdkVersion(23)
        multiDexEnabled = true
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
        isCoreLibraryDesugaringEnabled = true
    }
}

dependencies {
    val acraVersion = "5.7.0"
    implementation("ch.acra:acra-http:$acraVersion")
    coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:1.1.5")
}
```

**Comment by fareed945** [comment]
hey,
My version is same as the one you mentioned above
  coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.1.5'

This is my configuration: 
 minSdkVersion 23
 targetSdkVersion 30
compileSdkVersion 30

 implementation "ch.acra:acra-mail:5.7.0"
------------------------------------------------------------
This is the config in the application module

 CoreConfigurationBuilder builder = new CoreConfigurationBuilder(this)
                .setBuildConfigClass(BuildConfig.class)
                .setReportFormat(StringFormat.JSON);
        
        builder.getPluginConfigurationBuilder(MailSenderConfigurationBuilder.class)
                .setSubject("Crash report")
                .setBody("PFA the crash report")
                .setReportAsFile(true)
                .setReportFileName("Crash Report.txt")
                .setEnabled(true);

        ACRA.init(this, builder);

**Comment by mikehardy** [comment]
AnkiDroid is using 
- 1.1.5 desugaring https://github.com/ankidroid/Anki-Android/blob/a1ebaa00664bdb54a439da83dc6207194228e9d4/AnkiDroid/build.gradle#L225
- acra http/dialog/toast/limiter 5.5.1 (don't laugh, we're a bit behind :sweat_smile: ) https://github.com/ankidroid/Anki-Android/blob/a1ebaa00664bdb54a439da83dc6207194228e9d4/AnkiDroid/build.gradle#L263

and it appears to be running fine for us, FWIW

I have it on my list to update ACRA I'll give it a whirl

**Comment by mikehardy** [comment]
I just updated AnkiDroid to 5.7.0 (haven't made the PR yet, it's local still) and I cannot reproduce this with the 4 plugins I mention above, if that is useful information at all. Startup was fine, test crash was fine.

**Comment by mikehardy** [comment]
Only thing I can think of is maybe a multidex issue, that's the "usual" thing when a class that should be there is not on the classpath list.

**Comment by fareed945** [comment]
hey @mikehardy , sorry for the confusion. May I know what AnkiDroid is ?
@F43nd1r can you let me know if there is anything wrong with my configuration of the library ?
I'm using the Email version only..
And I repeat, As soon as I remove these lines of code from My Application, everything works fine

**Comment by F43nd1r** [comment]
Try turning on multidex as mike mentioned.

AnkiDroid is just an app using ACRA.

**Comment by fareed945** [comment]
I have multidexenabled true as well

**Comment by mikehardy** [comment]
Yeah - sorry if I was confusing, I am just an ACRA supporter and thought I could at least try for a reproduction and report if it was failing everywhere or at least was working in some other location - so I was just reporting that I am some other app and it's working. MultiDex requires 3 steps - I wrote them up here for users of another library I maintain https://rnfirebase.io/enabling-multidex - maybe one is missing? I'll admit the idea of multidex is a weak guess, it may have nothing to do with the issue. Sorry I couldn't reproduce it to help you nail the issue.

Cheers!

**Comment by fareed945** [comment]
Nope @mikehardy , thanks for your comments. I truly appreciate it.
Unfortunately I tried out the steps mentioned above, was not able to get rid of the error.
So basically, I found another thing on my way of experimenting stuff. 
This failure was happening only on this line
.setMailTo("xyz@xyz.com")

ie.. The to report email Id. Which is obviously important for me

**Comment by fareed945** [comment]
@F43nd1r  apologies I didn't include the  .setMailTo in the initial code snippet.
It fails on setting it this way (.setMailTo) to the builder or while using the annotation based approach.
Please check if you're able to reproduce this :<

**Comment by F43nd1r** [comment]
Still can't reproduce. Maybe try the 5.8 beta just as a moonshot?

Otherwise you'll need to provide a minimum viable sample project, otherwise I won't be able to identify this issue.

**Comment by fareed945** [comment]
hey people, has the config changed for 5.8 beta versions ? or are there any documentation changes

**Comment by F43nd1r** [comment]
Annotation config stayed the same, but is deprecated. Runtime config has changed, see here https://github.com/ACRA/acra/releases/tag/acra-5.8.0-alpha1

**Comment by fareed945** [comment]
Issue resolved, the problem was due to the saved crash reports in the cache. Just cleared them by using the file explorer from android studio. All good !
Closing this issue (not an issue actually) :)
