### ISSUE TITLE
Acra init failed

### ISSUE THREAD

**Issue by hopelesszxq** [ACRA/acra#844]
my code 
CoreConfigurationBuilder builder = new CoreConfigurationBuilder(this);
        builder.setBuildConfigClass(BuildConfig.class)
                .setReportFormat(StringFormat.JSON);

        builder.getPluginConfigurationBuilder(HttpSenderConfigurationBuilder.class)
                .setUri("http://192.168.57.129:8080/arca/arca")
                .setHttpMethod(HttpSender.Method.POST)
                .setEnabled(true);
        ACRA.init(this, builder);

error info

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.acra.sample, PID: 2786
    java.lang.RuntimeException: Unable to instantiate application com.acra.sample.AcraApplication: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.SharedPreferences android.content.Context.getSharedPreferences(java.lang.String, int)' on a null object reference
        at android.app.LoadedApk.makeApplication(LoadedApk.java:588)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4819)
        at android.app.ActivityThread.-wrap1(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1481)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5606)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.SharedPreferences android.content.Context.getSharedPreferences(java.lang.String, int)' on a null object reference
        at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:171)
        at org.acra.prefs.SharedPreferencesFactory.create(SharedPreferencesFactory.java:74)
        at org.acra.ACRA.init(ACRA.java:222)
        at org.acra.ACRA.init(ACRA.java:160)
        at org.acra.ACRA.init(ACRA.java:144)
        at com.acra.sample.AcraApplication.attachBaseContext(AcraApplication.java:48)
        at android.app.Application.attach(Application.java:187)
        at android.app.Instrumentation.newApplication(Instrumentation.java:997)
        at android.app.Instrumentation.newApplication(Instrumentation.java:981)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:583)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4819) 
        at android.app.ActivityThread.-wrap1(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1481) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5606) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635)

**Comment by F43nd1r** [comment]
Make sure you're calling ACRA.init after super.attachBaseContext

**Comment by hopelesszxq** [comment]
thanks,the issue is ok,forget add super.attachBaseContext
