### ISSUE TITLE
AcraHttpSender fails

### ISSUE THREAD

**Issue by hopelesszxq** [ACRA/acra#845]
my code 

CoreConfigurationBuilder builder = new CoreConfigurationBuilder(this);
        builder.setBuildConfigClass(BuildConfig.class)
                .setEnabled(true)
                .setReportFormat(StringFormat.JSON);

        builder.getPluginConfigurationBuilder(HttpSenderConfigurationBuilder.class)
                .setUri("http://192.168.57.129:8080/arca/arca")
                .setHttpMethod(HttpSender.Method.POST)
                .setEnabled(true);
        ACRA.init(this, builder);

E/ACRA: ACRA caught a RuntimeException for com.acra.sample
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.acra.sample/com.acra.sample.MainActivity}: java.lang.NullPointerException: throw with null exception
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6097)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:928)
     Caused by: java.lang.NullPointerException: throw with null exception
        at com.acra.sample.MainActivity.onCreate(MainActivity.java:49)
        at android.app.Activity.performCreate(Activity.java:6725)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)

my server api can not recieve exception data

**Comment by F43nd1r** [comment]
Double check your url.
- arca might be a typo
- note that sending reports from an emulator to the host requires you to use the special 10.0.2.2 ip.

If that doesn't help gather and post full logs.
