### ISSUE TITLE
Huawei Honor not sending logs

### ISSUE THREAD

**Issue by arcanewater** [ACRA/acra#846]
So i especially get this issue on Huawei Honor, when i force to send logs i see following in logcat, i get the notification toast but nothing else mail does not open (no attachments nothing)

```
04-30 14:47:52.652 31264 31280 E ACRA    : Failed to send crash reports for /data/user/0/com.app.sampleapp/app_ACRA-approved/2021-04-30T14:47:48.654+02:00.stacktrace
04-30 14:47:52.652 31264 31280 E ACRA    : java.lang.RuntimeException: Failure from system
04-30 14:47:52.652 31264 31280 E ACRA    : 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1759)
04-30 14:47:52.652 31264 31280 E ACRA    : 	at android.app.ContextImpl.startActivity(ContextImpl.java:1048)
04-30 14:47:52.652 31264 31280 E ACRA    : 	at android.app.ContextImpl.startActivity(ContextImpl.java:1005)
04-30 14:47:52.652 31264 31280 E ACRA    : 	at android.content.ContextWrapper.startActivity(ContextWrapper.java:379)
04-30 14:47:52.652 31264 31280 E ACRA    : 	at org.acra.sender.EmailIntentSender.sendLegacy(EmailIntentSender.kt:103)
04-30 14:47:52.652 31264 31280 E ACRA    : 	at org.acra.sender.EmailIntentSender.send(EmailIntentSender.kt:69)
04-30 14:47:52.652 31264 31280 E ACRA    : 	at zzwjb.zzwjb.zzwjb.zzwjb.zzwjb.zzwjv.zzwjt.send(InternalReportSender.kt:3)
04-30 14:47:52.652 31264 31280 E ACRA    : 	at org.acra.sender.ReportSender$DefaultImpls.send(ReportSender.kt:57)
04-30 14:47:52.652 31264 31280 E ACRA    : 	at org.acra.sender.EmailIntentSender.send(EmailIntentSender.kt:50)
04-30 14:47:52.652 31264 31280 E ACRA    : 	at org.acra.sender.ReportDistributor.sendCrashReport(ReportDistributor.kt:96)
04-30 14:47:52.652 31264 31280 E ACRA    : 	at org.acra.sender.ReportDistributor.distribute(ReportDistributor.kt:60)
04-30 14:47:52.652 31264 31280 E ACRA    : 	at org.acra.sender.SendingConductor.sendReports(SendingConductor.kt:50)
04-30 14:47:52.652 31264 31280 E ACRA    : 	at org.acra.sender.JobSenderService$onStartJob$1.run(JobSenderService.kt:24)
04-30 14:47:52.652 31264 31280 E ACRA    : 	at java.lang.Thread.run(Thread.java:784)
04-30 14:47:52.652 31264 31280 E ACRA    : Caused by: android.os.TransactionTooLargeException: data parcel size 1202052 bytes
04-30 14:47:52.652 31264 31280 E ACRA    : 	at android.os.BinderProxy.transactNative(Native Method)
04-30 14:47:52.652 31264 31280 E ACRA    : 	at android.os.BinderProxy.transact(Binder.java:1147)
04-30 14:47:52.652 31264 31280 E ACRA    : 	at android.app.IActivityManager$Stub$Proxy.startActivity(IActivityManager.java:3732)
04-30 14:47:52.652 31264 31280 E ACRA    : 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1753)
04-30 14:47:52.652 31264 31280 E ACRA    : 	... 13 more
```

Before this error i get:

```
04-30 14:48:04.450  1303  8334 D PackageManager: resolve intent for uid:12737, matchs:2, res:ResolveInfo{2cdce07 com.google.android.gm/.ComposeActivityGmailExternal m=0x208000}
04-30 14:48:04.453 31264 31310 W ACRA    : No email client supporting attachments found. Attachments will be ignored
04-30 14:48:04.459 31264 31274 E         : [ZeroHung]zrhung_get_config: Get config failed for wp[0x0008]
```

So Gmail is also installed / set as default.

**Comment by F43nd1r** [comment]
ACRA and Android Version?

**Comment by arcanewater** [comment]
5.8.1-beta10
Honor View 20 (PCT-L29)
Android 9
