### ISSUE TITLE
Crash in ACRA when need to open mailsender

### ISSUE THREAD

**Issue by abkoradiya** [ACRA/acra#908]
**Describe the bug**
After implementing mailsender, when crash occur in my app at that time ACRA don't show mailsender and I have checked following logs from ACRA.

I/ACRA: Sending report /data/user/0/com.test/app_ACRA-approved/2021-09-02T10:25:25.529+05:30.stacktrace
W/Bundle: Key android.intent.extra.TEXT expected ArrayList<CharSequence> but value was a java.lang.String.  The default value <null> was returned.
W/Bundle: Attempt to cast generated internal exception:
    java.lang.ClassCastException: java.lang.String cannot be cast to java.util.ArrayList
        at android.os.BaseBundle.getCharSequenceArrayList(BaseBundle.java:1307)
        at android.os.Bundle.getCharSequenceArrayList(Bundle.java:1095)
        at android.content.Intent.getCharSequenceArrayListExtra(Intent.java:8016)
        at android.content.Intent.migrateExtraStreamToClipData(Intent.java:10962)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1702)
        at android.app.ContextImpl.startActivity(ContextImpl.java:957)
        at android.app.ContextImpl.startActivity(ContextImpl.java:928)
        at android.content.ContextWrapper.startActivity(ContextWrapper.java:383)
        at org.acra.sender.EmailIntentSender.sendWithSelector(EmailIntentSender.kt:119)
        at org.acra.sender.EmailIntentSender.send(EmailIntentSender.kt:67)
        at org.acra.sender.ReportSender.send(ReportSender.kt:59)
        at org.acra.sender.ReportDistributor.sendCrashReport(ReportDistributor.kt:96)
        at org.acra.sender.ReportDistributor.distribute(ReportDistributor.kt:60)
        at org.acra.sender.SendingConductor.sendReports(SendingConductor.kt:50)
        at org.acra.scheduler.DefaultSenderScheduler.scheduleReportSending(DefaultSenderScheduler.kt:61)
        at org.acra.scheduler.SchedulerStarter.scheduleReports(SchedulerStarter.kt:49)
        at org.acra.builder.ReportExecutor.sendReport(ReportExecutor.kt:197)
        at org.acra.builder.ReportExecutor.execute(ReportExecutor.kt:135)
        at org.acra.builder.ReportBuilder.build(ReportBuilder.kt:151)
        at org.acra.reporter.ErrorReporterImpl.uncaughtException(ErrorReporterImpl.kt:105)
        at com.google.firebase.crashlytics.internal.common.CrashlyticsUncaughtExceptionHandler.uncaughtException(CrashlyticsUncaughtExceptionHandler.java:63)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
        at kotlinx.coroutines.android.AndroidExceptionPreHandler.handleException(AndroidExceptionPreHandler.kt:47)
        at kotlinx.coroutines.CoroutineExceptionHandlerImplKt.handleCoroutineExceptionImpl(CoroutineExceptionHandlerImpl.kt:29)
        at kotlinx.coroutines.CoroutineExceptionHandlerKt.handleCoroutineException(CoroutineExceptionHandler.kt:33)
        at kotlinx.coroutines.StandaloneCoroutine.handleJobException(Builders.common.kt:189)
        at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:229)
        at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:903)
        at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:860)
        at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:825)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:111)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.UndispatchedCoroutine.afterResume(Builders.common.kt:214)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Expected behavior**
MailSender should be open.

**Version**
 - Android: [e.g. 10]
 - ACRA mail[5.8.4]

**Comment by F43nd1r** [comment]
If you're on a Xiaomi device, see #804. If not, search for more logs, as the exception you posted shows up often but doesn't mean anything.

**Comment by F43nd1r** [comment]
No response - closing
